// Code generated by entdomain extension from schema "Account" (entschema/schema/account.go). DO NOT EDIT.
// Source template: backend/pkg/entdomain/templates/base_handler.tmpl
// Regenerate with: make generate

package ent

import (
	"context"

	"github.com/google/uuid"
)

// BaseAccountHandler provides ent→response conversion helpers for Account.
// Embed this in your handler struct so that handler code never imports the ent package directly.
type BaseAccountHandler struct{}

// ToResponse converts an ent Account entity to a response DTO.
func (h *BaseAccountHandler) ToResponse(entity *Account) *AccountResponse {
	return AccountEntToResponse(entity)
}

// ToResponseList converts a slice of ent Account entities to response DTOs.
func (h *BaseAccountHandler) ToResponseList(entities []*Account) []*AccountResponse {
	responses := make([]*AccountResponse, len(entities))
	for i, e := range entities {
		responses[i] = AccountEntToResponse(e)
	}
	return responses
}

// accountUpdater is the interface required by PartialUpdate.
type accountUpdater interface {
	Update(context.Context, uuid.UUID, *AccountUpdateRequest) (*Account, error)
}

// PartialUpdate applies the partial update request, saves the result, and returns the response DTO.
func (h *BaseAccountHandler) PartialUpdate(
	ctx context.Context, svc accountUpdater,
	id uuid.UUID, req *AccountUpdateRequest,
) (*AccountResponse, error) {
	entity, err := svc.Update(ctx, id, req)
	if err != nil {
		return nil, err
	}
	return AccountEntToResponse(entity), nil
}
