// Code generated by ent, DO NOT EDIT.

package jsonwidget

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the jsonwidget type in the database.
	Label = "json_widget"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldMeta holds the string denoting the meta field in the database.
	FieldMeta = "meta"
	// FieldRequiredTags holds the string denoting the required_tags field in the database.
	FieldRequiredTags = "required_tags"
	// FieldRequiredMeta holds the string denoting the required_meta field in the database.
	FieldRequiredMeta = "required_meta"
	// Table holds the table name of the jsonwidget in the database.
	Table = "json_widgets"
)

// Columns holds all SQL columns for jsonwidget fields.
var Columns = []string{
	FieldID,
	FieldTags,
	FieldMeta,
	FieldRequiredTags,
	FieldRequiredMeta,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the JSONWidget queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}
