// Code generated by entapi extension from schema "Counter". DO NOT EDIT.
// Source template: templates/handler.tmpl
// Regenerate with: make generate

package intident

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime"
	"net/http"
	"strconv"

	// Runtime helpers are kept distinct from identifier-type dependencies.
	entapi "github.com/githonllc/entapi/runtime"
)

// ListCountersFn is byte-identical to ListCounters.
type ListCountersFn func(context.Context, *Client, *CounterFilter, entapi.ListRequest) (*entapi.Page[CounterResponse], error)

func (h *APIHandler) handleListCounters(w http.ResponseWriter, r *http.Request) {
	filter, request, err := ParseCounterQuery(r.URL.Query())
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}

	response, err := h.listCounters(r.Context(), h.client, filter, request)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(err):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(err):
			status = http.StatusConflict
		case entapi.IsValidation(err):
			status = http.StatusBadRequest
		}
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	body, err := json.Marshal(response)
	if err != nil {
		entapi.WriteProblem(w, http.StatusInternalServerError, http.StatusText(http.StatusInternalServerError), err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(append(body, '\n'))
}

// CreateCounterFn is byte-identical to CreateCounter.
type CreateCounterFn func(context.Context, *Client, *ValidCounterCreateRequest) (*CounterResponse, error)

func (h *APIHandler) handleCreateCounter(w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
	mediaType, _, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
	if err != nil || mediaType != "application/json" {
		entapi.WriteProblem(w, http.StatusUnsupportedMediaType, http.StatusText(http.StatusUnsupportedMediaType),
			errors.New("content type must be application/json"))
		return
	}
	body, err := io.ReadAll(r.Body)
	if err != nil {
		var maxBytesErr *http.MaxBytesError
		if errors.As(err, &maxBytesErr) {
			entapi.WriteProblem(w, http.StatusRequestEntityTooLarge, http.StatusText(http.StatusRequestEntityTooLarge), err)
			return
		}
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(body, &raw); err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	unknownField := ""
	for key := range raw {
		known := false
		for _, tag := range counterCreateRequestTags {
			if key == tag {
				known = true
				break
			}
		}
		if !known && (unknownField == "" || key < unknownField) {
			unknownField = key
		}
	}
	if unknownField != "" {
		err := &entapi.FieldError{
			Field: unknownField,
			Err:   fmt.Errorf("%w: unknown field %q", entapi.ErrValidation, unknownField),
		}
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	var request CounterCreateRequest
	if err := json.Unmarshal(body, &request); err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	validated, err := request.Validate()
	if err != nil {
		entapi.WriteProblem(w, http.StatusUnprocessableEntity, http.StatusText(http.StatusUnprocessableEntity), err)
		return
	}

	response, err := h.createCounter(r.Context(), h.client, validated)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(err):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(err):
			status = http.StatusConflict
		case entapi.IsValidation(err):
			status = http.StatusBadRequest
		}
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	body, err = json.Marshal(response)
	if err != nil {
		entapi.WriteProblem(w, http.StatusInternalServerError, http.StatusText(http.StatusInternalServerError), err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(append(body, '\n'))
}

// GetCounterFn is byte-identical to GetCounter.
type GetCounterFn func(context.Context, *Client, int) (*CounterResponse, error)

func (h *APIHandler) handleGetCounter(w http.ResponseWriter, r *http.Request) {
	parsedID, err := strconv.ParseInt(r.PathValue("id"), 10, 0)
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}
	id := int(parsedID)

	response, err := h.getCounter(r.Context(), h.client, id)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(err):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(err):
			status = http.StatusConflict
		case entapi.IsValidation(err):
			status = http.StatusBadRequest
		}
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	body, err := json.Marshal(response)
	if err != nil {
		entapi.WriteProblem(w, http.StatusInternalServerError, http.StatusText(http.StatusInternalServerError), err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(append(body, '\n'))
}

// PatchCounterFn is byte-identical to PatchCounter.
type PatchCounterFn func(context.Context, *Client, int, *ValidCounterPatchRequest) (*CounterResponse, error)

func (h *APIHandler) handlePatchCounter(w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
	mediaType, _, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
	if err != nil || mediaType != "application/json" {
		entapi.WriteProblem(w, http.StatusUnsupportedMediaType, http.StatusText(http.StatusUnsupportedMediaType),
			errors.New("content type must be application/json"))
		return
	}
	body, err := io.ReadAll(r.Body)
	if err != nil {
		var maxBytesErr *http.MaxBytesError
		if errors.As(err, &maxBytesErr) {
			entapi.WriteProblem(w, http.StatusRequestEntityTooLarge, http.StatusText(http.StatusRequestEntityTooLarge), err)
			return
		}
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(body, &raw); err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	unknownField := ""
	for key := range raw {
		known := false
		for _, tag := range counterPatchRequestTags {
			if key == tag {
				known = true
				break
			}
		}
		if !known && (unknownField == "" || key < unknownField) {
			unknownField = key
		}
	}
	if unknownField != "" {
		err := &entapi.FieldError{
			Field: unknownField,
			Err:   fmt.Errorf("%w: unknown field %q", entapi.ErrValidation, unknownField),
		}
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	var request CounterPatchRequest
	if err := json.Unmarshal(body, &request); err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	validated, err := request.Validate()
	if err != nil {
		entapi.WriteProblem(w, http.StatusUnprocessableEntity, http.StatusText(http.StatusUnprocessableEntity), err)
		return
	}
	parsedID, err := strconv.ParseInt(r.PathValue("id"), 10, 0)
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}
	id := int(parsedID)

	response, err := h.patchCounter(r.Context(), h.client, id, validated)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(err):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(err):
			status = http.StatusConflict
		case entapi.IsValidation(err):
			status = http.StatusBadRequest
		}
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	body, err = json.Marshal(response)
	if err != nil {
		entapi.WriteProblem(w, http.StatusInternalServerError, http.StatusText(http.StatusInternalServerError), err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(append(body, '\n'))
}

// DeleteCounterFn is byte-identical to DeleteCounter.
type DeleteCounterFn func(context.Context, *Client, int) error

func (h *APIHandler) handleDeleteCounter(w http.ResponseWriter, r *http.Request) {
	parsedID, err := strconv.ParseInt(r.PathValue("id"), 10, 0)
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}
	id := int(parsedID)

	deleteErr := h.deleteCounter(r.Context(), h.client, id)
	if deleteErr != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(deleteErr):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(deleteErr):
			status = http.StatusConflict
		case entapi.IsValidation(deleteErr):
			status = http.StatusBadRequest
		}
		entapi.WriteProblem(w, status, http.StatusText(status), deleteErr)
		return
	}

	w.WriteHeader(http.StatusNoContent)
}
