// Code generated by entapi extension for this schema as a whole. DO NOT EDIT.
// Source template: templates/http.tmpl
// Regenerate with: make generate

package intident

import (
	"fmt"
	"net/http"

	entapi "github.com/githonllc/entapi/runtime"
)

// APIOption replaces one generated operation implementation.
type APIOption interface{ applyOption(*APIHandler) }

// APIHandler is the generated CRUD HTTP surface.
type APIHandler struct {
	client        *Client
	mux           *http.ServeMux
	routes        []entapi.Route
	listCounters  ListCountersFn
	createCounter CreateCounterFn
	getCounter    GetCounterFn
	patchCounter  PatchCounterFn
	deleteCounter DeleteCounterFn
}

// API builds the generated CRUD HTTP surface for client.
func API(client *Client) *APIHandler {
	if !ErrorMap.HasUniqueViolation() {
		if f, ok := entapi.UniqueViolation(client.driver.Dialect()); ok {
			ErrorMap = ErrorMap.WithUniqueViolation(f)
		}
	}
	h := &APIHandler{
		client:        client,
		mux:           http.NewServeMux(),
		listCounters:  ListCounters,
		createCounter: CreateCounter,
		getCounter:    GetCounter,
		patchCounter:  PatchCounter,
		deleteCounter: DeleteCounter,
	}
	h.routes = []entapi.Route{
		{
			Method:  "GET",
			Path:    "/counters",
			Handler: http.HandlerFunc(h.handleListCounters),
			Entity:  "Counter",
			Op:      "list",
		},
		{
			Method:  "POST",
			Path:    "/counters",
			Handler: http.HandlerFunc(h.handleCreateCounter),
			Entity:  "Counter",
			Op:      "create",
		},
		{
			Method:  "GET",
			Path:    "/counters/{id}",
			Handler: http.HandlerFunc(h.handleGetCounter),
			Entity:  "Counter",
			Op:      "get",
		},
		{
			Method:  "PATCH",
			Path:    "/counters/{id}",
			Handler: http.HandlerFunc(h.handlePatchCounter),
			Entity:  "Counter",
			Op:      "patch",
		},
		{
			Method:  "DELETE",
			Path:    "/counters/{id}",
			Handler: http.HandlerFunc(h.handleDeleteCounter),
			Entity:  "Counter",
			Op:      "delete",
		},
		// The document describing everything above. It is in the manifest, not
		// beside it, so Routes() sees it and a consumer can wrap or drop it with
		// the same loop they use for the CRUD routes. It is the one route the
		// document does not describe: it is not part of the resource surface.
		{
			Method:  "GET",
			Path:    "/openapi.yaml",
			Handler: http.HandlerFunc(serveOpenAPI),
		},
	}
	for _, rt := range h.routes {
		h.mux.Handle(rt.Method+" "+rt.Path, rt.Handler)
	}
	return h
}

// With replaces generated operation implementations before serving begins.
func (h *APIHandler) With(opts ...APIOption) *APIHandler {
	for i, opt := range opts {
		if opt == nil {
			panic(fmt.Sprintf("entapi: APIOption at index %d is nil", i))
		}
		opt.applyOption(h)
	}
	return h
}

// Routes returns generated routes in deterministic registration order.
func (h *APIHandler) Routes() []entapi.Route {
	return append([]entapi.Route(nil), h.routes...)
}

// ServeHTTP serves the generated route tree.
func (h *APIHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h.mux.ServeHTTP(w, r)
}

// Mount registers every generated route on mux.
func (h *APIHandler) Mount(mux *http.ServeMux) {
	for _, rt := range h.routes {
		mux.Handle(rt.Method+" "+rt.Path, rt.Handler)
	}
}
