// Code generated by entapi extension for this schema as a whole. DO NOT EDIT.
// Source template: templates/http.tmpl
// Regenerate with: make generate

package immutableent

import (
	"net/http"

	entapi "github.com/githonllc/entapi/runtime"
)

// APIHandler is the generated CRUD HTTP surface.
type APIHandler struct {
	client    *Client
	mux       *http.ServeMux
	routes    []entapi.Route
	listDocs  ListDocsFn
	createDoc CreateDocFn
	getDoc    GetDocFn
	patchDoc  PatchDocFn
	deleteDoc DeleteDocFn
}

// API builds the generated CRUD HTTP surface for client.
func API(client *Client) *APIHandler {
	if !ErrorMap.HasUniqueViolation() {
		if f, ok := entapi.UniqueViolation(client.driver.Dialect()); ok {
			ErrorMap = ErrorMap.WithUniqueViolation(f)
		}
	}
	h := &APIHandler{
		client:    client,
		mux:       http.NewServeMux(),
		listDocs:  ListDocs,
		createDoc: CreateDoc,
		getDoc:    GetDoc,
		patchDoc:  PatchDoc,
		deleteDoc: DeleteDoc,
	}
	h.routes = []entapi.Route{
		{
			Method:  "GET",
			Path:    "/docs",
			Handler: http.HandlerFunc(h.handleListDocs),
		},
		{
			Method:  "POST",
			Path:    "/docs",
			Handler: http.HandlerFunc(h.handleCreateDoc),
		},
		{
			Method:  "GET",
			Path:    "/docs/{id}",
			Handler: http.HandlerFunc(h.handleGetDoc),
		},
		{
			Method:  "PATCH",
			Path:    "/docs/{id}",
			Handler: http.HandlerFunc(h.handlePatchDoc),
		},
		{
			Method:  "DELETE",
			Path:    "/docs/{id}",
			Handler: http.HandlerFunc(h.handleDeleteDoc),
		},
	}
	for _, rt := range h.routes {
		h.mux.Handle(rt.Method+" "+rt.Path, rt.Handler)
	}
	return h
}

// ServeHTTP serves the generated route tree.
func (h *APIHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h.mux.ServeHTTP(w, r)
}

// Mount registers every generated route on mux.
func (h *APIHandler) Mount(mux *http.ServeMux) {
	for _, rt := range h.routes {
		mux.Handle(rt.Method+" "+rt.Path, rt.Handler)
	}
}
