// Code generated by ent, DO NOT EDIT.

package fieldshapesent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/githonllc/entapi/internal/fixtures/fieldshapes/fieldshapesent/enumwidget"
	"github.com/google/uuid"
)

// EnumWidgetCreate is the builder for creating a EnumWidget entity.
type EnumWidgetCreate struct {
	config
	mutation *EnumWidgetMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (ewc *EnumWidgetCreate) SetStatus(e enumwidget.Status) *EnumWidgetCreate {
	ewc.mutation.SetStatus(e)
	return ewc
}

// SetTier sets the "tier" field.
func (ewc *EnumWidgetCreate) SetTier(e enumwidget.Tier) *EnumWidgetCreate {
	ewc.mutation.SetTier(e)
	return ewc
}

// SetNillableTier sets the "tier" field if the given value is not nil.
func (ewc *EnumWidgetCreate) SetNillableTier(e *enumwidget.Tier) *EnumWidgetCreate {
	if e != nil {
		ewc.SetTier(*e)
	}
	return ewc
}

// SetID sets the "id" field.
func (ewc *EnumWidgetCreate) SetID(u uuid.UUID) *EnumWidgetCreate {
	ewc.mutation.SetID(u)
	return ewc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ewc *EnumWidgetCreate) SetNillableID(u *uuid.UUID) *EnumWidgetCreate {
	if u != nil {
		ewc.SetID(*u)
	}
	return ewc
}

// Mutation returns the EnumWidgetMutation object of the builder.
func (ewc *EnumWidgetCreate) Mutation() *EnumWidgetMutation {
	return ewc.mutation
}

// Save creates the EnumWidget in the database.
func (ewc *EnumWidgetCreate) Save(ctx context.Context) (*EnumWidget, error) {
	ewc.defaults()
	return withHooks(ctx, ewc.sqlSave, ewc.mutation, ewc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ewc *EnumWidgetCreate) SaveX(ctx context.Context) *EnumWidget {
	v, err := ewc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ewc *EnumWidgetCreate) Exec(ctx context.Context) error {
	_, err := ewc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ewc *EnumWidgetCreate) ExecX(ctx context.Context) {
	if err := ewc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ewc *EnumWidgetCreate) defaults() {
	if _, ok := ewc.mutation.ID(); !ok {
		v := enumwidget.DefaultID()
		ewc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ewc *EnumWidgetCreate) check() error {
	if _, ok := ewc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`fieldshapesent: missing required field "EnumWidget.status"`)}
	}
	if v, ok := ewc.mutation.Status(); ok {
		if err := enumwidget.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`fieldshapesent: validator failed for field "EnumWidget.status": %w`, err)}
		}
	}
	if v, ok := ewc.mutation.Tier(); ok {
		if err := enumwidget.TierValidator(v); err != nil {
			return &ValidationError{Name: "tier", err: fmt.Errorf(`fieldshapesent: validator failed for field "EnumWidget.tier": %w`, err)}
		}
	}
	return nil
}

func (ewc *EnumWidgetCreate) sqlSave(ctx context.Context) (*EnumWidget, error) {
	if err := ewc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ewc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ewc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ewc.mutation.id = &_node.ID
	ewc.mutation.done = true
	return _node, nil
}

func (ewc *EnumWidgetCreate) createSpec() (*EnumWidget, *sqlgraph.CreateSpec) {
	var (
		_node = &EnumWidget{config: ewc.config}
		_spec = sqlgraph.NewCreateSpec(enumwidget.Table, sqlgraph.NewFieldSpec(enumwidget.FieldID, field.TypeUUID))
	)
	if id, ok := ewc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ewc.mutation.Status(); ok {
		_spec.SetField(enumwidget.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := ewc.mutation.Tier(); ok {
		_spec.SetField(enumwidget.FieldTier, field.TypeEnum, value)
		_node.Tier = value
	}
	return _node, _spec
}

// EnumWidgetCreateBulk is the builder for creating many EnumWidget entities in bulk.
type EnumWidgetCreateBulk struct {
	config
	err      error
	builders []*EnumWidgetCreate
}

// Save creates the EnumWidget entities in the database.
func (ewcb *EnumWidgetCreateBulk) Save(ctx context.Context) ([]*EnumWidget, error) {
	if ewcb.err != nil {
		return nil, ewcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ewcb.builders))
	nodes := make([]*EnumWidget, len(ewcb.builders))
	mutators := make([]Mutator, len(ewcb.builders))
	for i := range ewcb.builders {
		func(i int, root context.Context) {
			builder := ewcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnumWidgetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ewcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ewcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ewcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ewcb *EnumWidgetCreateBulk) SaveX(ctx context.Context) []*EnumWidget {
	v, err := ewcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ewcb *EnumWidgetCreateBulk) Exec(ctx context.Context) error {
	_, err := ewcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ewcb *EnumWidgetCreateBulk) ExecX(ctx context.Context) {
	if err := ewcb.Exec(ctx); err != nil {
		panic(err)
	}
}
