// Code generated by ent, DO NOT EDIT.

package fieldshapesent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/githonllc/entdomain/internal/fixtures/fieldshapes/fieldshapesent/jsonwidget"
	"github.com/githonllc/entdomain/internal/fixtures/fieldshapes/fieldshapesent/predicate"
)

// JSONWidgetUpdate is the builder for updating JSONWidget entities.
type JSONWidgetUpdate struct {
	config
	hooks    []Hook
	mutation *JSONWidgetMutation
}

// Where appends a list predicates to the JSONWidgetUpdate builder.
func (jwu *JSONWidgetUpdate) Where(ps ...predicate.JSONWidget) *JSONWidgetUpdate {
	jwu.mutation.Where(ps...)
	return jwu
}

// SetTags sets the "tags" field.
func (jwu *JSONWidgetUpdate) SetTags(s []string) *JSONWidgetUpdate {
	jwu.mutation.SetTags(s)
	return jwu
}

// AppendTags appends s to the "tags" field.
func (jwu *JSONWidgetUpdate) AppendTags(s []string) *JSONWidgetUpdate {
	jwu.mutation.AppendTags(s)
	return jwu
}

// ClearTags clears the value of the "tags" field.
func (jwu *JSONWidgetUpdate) ClearTags() *JSONWidgetUpdate {
	jwu.mutation.ClearTags()
	return jwu
}

// SetMeta sets the "meta" field.
func (jwu *JSONWidgetUpdate) SetMeta(m map[string]string) *JSONWidgetUpdate {
	jwu.mutation.SetMeta(m)
	return jwu
}

// ClearMeta clears the value of the "meta" field.
func (jwu *JSONWidgetUpdate) ClearMeta() *JSONWidgetUpdate {
	jwu.mutation.ClearMeta()
	return jwu
}

// SetRequiredTags sets the "required_tags" field.
func (jwu *JSONWidgetUpdate) SetRequiredTags(s []string) *JSONWidgetUpdate {
	jwu.mutation.SetRequiredTags(s)
	return jwu
}

// AppendRequiredTags appends s to the "required_tags" field.
func (jwu *JSONWidgetUpdate) AppendRequiredTags(s []string) *JSONWidgetUpdate {
	jwu.mutation.AppendRequiredTags(s)
	return jwu
}

// SetRequiredMeta sets the "required_meta" field.
func (jwu *JSONWidgetUpdate) SetRequiredMeta(m map[string]string) *JSONWidgetUpdate {
	jwu.mutation.SetRequiredMeta(m)
	return jwu
}

// Mutation returns the JSONWidgetMutation object of the builder.
func (jwu *JSONWidgetUpdate) Mutation() *JSONWidgetMutation {
	return jwu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (jwu *JSONWidgetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, jwu.sqlSave, jwu.mutation, jwu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (jwu *JSONWidgetUpdate) SaveX(ctx context.Context) int {
	affected, err := jwu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (jwu *JSONWidgetUpdate) Exec(ctx context.Context) error {
	_, err := jwu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jwu *JSONWidgetUpdate) ExecX(ctx context.Context) {
	if err := jwu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (jwu *JSONWidgetUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(jsonwidget.Table, jsonwidget.Columns, sqlgraph.NewFieldSpec(jsonwidget.FieldID, field.TypeUUID))
	if ps := jwu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := jwu.mutation.Tags(); ok {
		_spec.SetField(jsonwidget.FieldTags, field.TypeJSON, value)
	}
	if value, ok := jwu.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, jsonwidget.FieldTags, value)
		})
	}
	if jwu.mutation.TagsCleared() {
		_spec.ClearField(jsonwidget.FieldTags, field.TypeJSON)
	}
	if value, ok := jwu.mutation.Meta(); ok {
		_spec.SetField(jsonwidget.FieldMeta, field.TypeJSON, value)
	}
	if jwu.mutation.MetaCleared() {
		_spec.ClearField(jsonwidget.FieldMeta, field.TypeJSON)
	}
	if value, ok := jwu.mutation.RequiredTags(); ok {
		_spec.SetField(jsonwidget.FieldRequiredTags, field.TypeJSON, value)
	}
	if value, ok := jwu.mutation.AppendedRequiredTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, jsonwidget.FieldRequiredTags, value)
		})
	}
	if value, ok := jwu.mutation.RequiredMeta(); ok {
		_spec.SetField(jsonwidget.FieldRequiredMeta, field.TypeJSON, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, jwu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{jsonwidget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	jwu.mutation.done = true
	return n, nil
}

// JSONWidgetUpdateOne is the builder for updating a single JSONWidget entity.
type JSONWidgetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JSONWidgetMutation
}

// SetTags sets the "tags" field.
func (jwuo *JSONWidgetUpdateOne) SetTags(s []string) *JSONWidgetUpdateOne {
	jwuo.mutation.SetTags(s)
	return jwuo
}

// AppendTags appends s to the "tags" field.
func (jwuo *JSONWidgetUpdateOne) AppendTags(s []string) *JSONWidgetUpdateOne {
	jwuo.mutation.AppendTags(s)
	return jwuo
}

// ClearTags clears the value of the "tags" field.
func (jwuo *JSONWidgetUpdateOne) ClearTags() *JSONWidgetUpdateOne {
	jwuo.mutation.ClearTags()
	return jwuo
}

// SetMeta sets the "meta" field.
func (jwuo *JSONWidgetUpdateOne) SetMeta(m map[string]string) *JSONWidgetUpdateOne {
	jwuo.mutation.SetMeta(m)
	return jwuo
}

// ClearMeta clears the value of the "meta" field.
func (jwuo *JSONWidgetUpdateOne) ClearMeta() *JSONWidgetUpdateOne {
	jwuo.mutation.ClearMeta()
	return jwuo
}

// SetRequiredTags sets the "required_tags" field.
func (jwuo *JSONWidgetUpdateOne) SetRequiredTags(s []string) *JSONWidgetUpdateOne {
	jwuo.mutation.SetRequiredTags(s)
	return jwuo
}

// AppendRequiredTags appends s to the "required_tags" field.
func (jwuo *JSONWidgetUpdateOne) AppendRequiredTags(s []string) *JSONWidgetUpdateOne {
	jwuo.mutation.AppendRequiredTags(s)
	return jwuo
}

// SetRequiredMeta sets the "required_meta" field.
func (jwuo *JSONWidgetUpdateOne) SetRequiredMeta(m map[string]string) *JSONWidgetUpdateOne {
	jwuo.mutation.SetRequiredMeta(m)
	return jwuo
}

// Mutation returns the JSONWidgetMutation object of the builder.
func (jwuo *JSONWidgetUpdateOne) Mutation() *JSONWidgetMutation {
	return jwuo.mutation
}

// Where appends a list predicates to the JSONWidgetUpdate builder.
func (jwuo *JSONWidgetUpdateOne) Where(ps ...predicate.JSONWidget) *JSONWidgetUpdateOne {
	jwuo.mutation.Where(ps...)
	return jwuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (jwuo *JSONWidgetUpdateOne) Select(field string, fields ...string) *JSONWidgetUpdateOne {
	jwuo.fields = append([]string{field}, fields...)
	return jwuo
}

// Save executes the query and returns the updated JSONWidget entity.
func (jwuo *JSONWidgetUpdateOne) Save(ctx context.Context) (*JSONWidget, error) {
	return withHooks(ctx, jwuo.sqlSave, jwuo.mutation, jwuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (jwuo *JSONWidgetUpdateOne) SaveX(ctx context.Context) *JSONWidget {
	node, err := jwuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (jwuo *JSONWidgetUpdateOne) Exec(ctx context.Context) error {
	_, err := jwuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jwuo *JSONWidgetUpdateOne) ExecX(ctx context.Context) {
	if err := jwuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (jwuo *JSONWidgetUpdateOne) sqlSave(ctx context.Context) (_node *JSONWidget, err error) {
	_spec := sqlgraph.NewUpdateSpec(jsonwidget.Table, jsonwidget.Columns, sqlgraph.NewFieldSpec(jsonwidget.FieldID, field.TypeUUID))
	id, ok := jwuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`fieldshapesent: missing "JSONWidget.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := jwuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, jsonwidget.FieldID)
		for _, f := range fields {
			if !jsonwidget.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("fieldshapesent: invalid field %q for query", f)}
			}
			if f != jsonwidget.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := jwuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := jwuo.mutation.Tags(); ok {
		_spec.SetField(jsonwidget.FieldTags, field.TypeJSON, value)
	}
	if value, ok := jwuo.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, jsonwidget.FieldTags, value)
		})
	}
	if jwuo.mutation.TagsCleared() {
		_spec.ClearField(jsonwidget.FieldTags, field.TypeJSON)
	}
	if value, ok := jwuo.mutation.Meta(); ok {
		_spec.SetField(jsonwidget.FieldMeta, field.TypeJSON, value)
	}
	if jwuo.mutation.MetaCleared() {
		_spec.ClearField(jsonwidget.FieldMeta, field.TypeJSON)
	}
	if value, ok := jwuo.mutation.RequiredTags(); ok {
		_spec.SetField(jsonwidget.FieldRequiredTags, field.TypeJSON, value)
	}
	if value, ok := jwuo.mutation.AppendedRequiredTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, jsonwidget.FieldRequiredTags, value)
		})
	}
	if value, ok := jwuo.mutation.RequiredMeta(); ok {
		_spec.SetField(jsonwidget.FieldRequiredMeta, field.TypeJSON, value)
	}
	_node = &JSONWidget{config: jwuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, jwuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{jsonwidget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	jwuo.mutation.done = true
	return _node, nil
}
