// Code generated by entapi extension from schema "NamedTypeWidget". DO NOT EDIT.
// Source template: templates/handler.tmpl
// Regenerate with: make generate

package fieldshapesent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime"
	"net/http"

	"github.com/google/uuid"

	// Runtime helpers are kept distinct from identifier-type dependencies.
	entapi "github.com/githonllc/entapi/runtime"
)

// ListNamedTypeWidgetsFn is byte-identical to ListNamedTypeWidgets.
type ListNamedTypeWidgetsFn func(context.Context, *Client, *NamedTypeWidgetFilter, entapi.ListRequest) (*entapi.Page[NamedTypeWidgetResponse], error)

func (h *APIHandler) handleListNamedTypeWidgets(w http.ResponseWriter, r *http.Request) {
	filter, request, err := ParseNamedTypeWidgetQuery(r.URL.Query())
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}

	response, err := h.listNamedTypeWidgets(r.Context(), h.client, filter, request)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(err):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(err):
			status = http.StatusConflict
		case entapi.IsValidation(err):
			status = http.StatusBadRequest
		}
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	body, err := json.Marshal(response)
	if err != nil {
		entapi.WriteProblem(w, http.StatusInternalServerError, http.StatusText(http.StatusInternalServerError), err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(append(body, '\n'))
}

// CreateNamedTypeWidgetFn is byte-identical to CreateNamedTypeWidget.
type CreateNamedTypeWidgetFn func(context.Context, *Client, *ValidNamedTypeWidgetCreateRequest) (*NamedTypeWidgetResponse, error)

func (h *APIHandler) handleCreateNamedTypeWidget(w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
	mediaType, _, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
	if err != nil || mediaType != "application/json" {
		entapi.WriteProblem(w, http.StatusUnsupportedMediaType, http.StatusText(http.StatusUnsupportedMediaType),
			errors.New("content type must be application/json"))
		return
	}
	body, err := io.ReadAll(r.Body)
	if err != nil {
		var maxBytesErr *http.MaxBytesError
		if errors.As(err, &maxBytesErr) {
			entapi.WriteProblem(w, http.StatusRequestEntityTooLarge, http.StatusText(http.StatusRequestEntityTooLarge), err)
			return
		}
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(body, &raw); err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	unknownField := ""
	for key := range raw {
		known := false
		for _, tag := range namedTypeWidgetCreateRequestTags {
			if key == tag {
				known = true
				break
			}
		}
		if !known && (unknownField == "" || key < unknownField) {
			unknownField = key
		}
	}
	if unknownField != "" {
		err := &entapi.FieldError{
			Field: unknownField,
			Err:   fmt.Errorf("%w: unknown field %q", entapi.ErrValidation, unknownField),
		}
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	var request NamedTypeWidgetCreateRequest
	if err := json.Unmarshal(body, &request); err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	validated, err := request.Validate()
	if err != nil {
		entapi.WriteProblem(w, http.StatusUnprocessableEntity, http.StatusText(http.StatusUnprocessableEntity), err)
		return
	}

	response, err := h.createNamedTypeWidget(r.Context(), h.client, validated)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(err):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(err):
			status = http.StatusConflict
		case entapi.IsValidation(err):
			status = http.StatusBadRequest
		}
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	body, err = json.Marshal(response)
	if err != nil {
		entapi.WriteProblem(w, http.StatusInternalServerError, http.StatusText(http.StatusInternalServerError), err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(append(body, '\n'))
}

// GetNamedTypeWidgetFn is byte-identical to GetNamedTypeWidget.
type GetNamedTypeWidgetFn func(context.Context, *Client, uuid.UUID) (*NamedTypeWidgetResponse, error)

func (h *APIHandler) handleGetNamedTypeWidget(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(r.PathValue("id"))
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}

	response, err := h.getNamedTypeWidget(r.Context(), h.client, id)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(err):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(err):
			status = http.StatusConflict
		case entapi.IsValidation(err):
			status = http.StatusBadRequest
		}
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	body, err := json.Marshal(response)
	if err != nil {
		entapi.WriteProblem(w, http.StatusInternalServerError, http.StatusText(http.StatusInternalServerError), err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(append(body, '\n'))
}

// PatchNamedTypeWidgetFn is byte-identical to PatchNamedTypeWidget.
type PatchNamedTypeWidgetFn func(context.Context, *Client, uuid.UUID, *ValidNamedTypeWidgetPatchRequest) (*NamedTypeWidgetResponse, error)

func (h *APIHandler) handlePatchNamedTypeWidget(w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
	mediaType, _, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
	if err != nil || mediaType != "application/json" {
		entapi.WriteProblem(w, http.StatusUnsupportedMediaType, http.StatusText(http.StatusUnsupportedMediaType),
			errors.New("content type must be application/json"))
		return
	}
	body, err := io.ReadAll(r.Body)
	if err != nil {
		var maxBytesErr *http.MaxBytesError
		if errors.As(err, &maxBytesErr) {
			entapi.WriteProblem(w, http.StatusRequestEntityTooLarge, http.StatusText(http.StatusRequestEntityTooLarge), err)
			return
		}
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(body, &raw); err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	unknownField := ""
	for key := range raw {
		known := false
		for _, tag := range namedTypeWidgetPatchRequestTags {
			if key == tag {
				known = true
				break
			}
		}
		if !known && (unknownField == "" || key < unknownField) {
			unknownField = key
		}
	}
	if unknownField != "" {
		err := &entapi.FieldError{
			Field: unknownField,
			Err:   fmt.Errorf("%w: unknown field %q", entapi.ErrValidation, unknownField),
		}
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	var request NamedTypeWidgetPatchRequest
	if err := json.Unmarshal(body, &request); err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	validated, err := request.Validate()
	if err != nil {
		entapi.WriteProblem(w, http.StatusUnprocessableEntity, http.StatusText(http.StatusUnprocessableEntity), err)
		return
	}
	id, err := uuid.Parse(r.PathValue("id"))
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}

	response, err := h.patchNamedTypeWidget(r.Context(), h.client, id, validated)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(err):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(err):
			status = http.StatusConflict
		case entapi.IsValidation(err):
			status = http.StatusBadRequest
		}
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	body, err = json.Marshal(response)
	if err != nil {
		entapi.WriteProblem(w, http.StatusInternalServerError, http.StatusText(http.StatusInternalServerError), err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(append(body, '\n'))
}

// DeleteNamedTypeWidgetFn is byte-identical to DeleteNamedTypeWidget.
type DeleteNamedTypeWidgetFn func(context.Context, *Client, uuid.UUID) error

func (h *APIHandler) handleDeleteNamedTypeWidget(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(r.PathValue("id"))
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}

	deleteErr := h.deleteNamedTypeWidget(r.Context(), h.client, id)
	if deleteErr != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(deleteErr):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(deleteErr):
			status = http.StatusConflict
		case entapi.IsValidation(deleteErr):
			status = http.StatusBadRequest
		}
		entapi.WriteProblem(w, status, http.StatusText(status), deleteErr)
		return
	}

	w.WriteHeader(http.StatusNoContent)
}
