// Code generated by ent, DO NOT EDIT.

package fieldshapesent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/githonllc/entapi/internal/fixtures/fieldshapes/fieldshapesent/namedtypewidget"
	"github.com/githonllc/entapi/internal/fixtures/fieldshapes/fieldshapesent/predicate"
	"github.com/githonllc/entapi/internal/fixtures/fieldshapes/fieldshapesent/schema"
)

// NamedTypeWidgetUpdate is the builder for updating NamedTypeWidget entities.
type NamedTypeWidgetUpdate struct {
	config
	hooks    []Hook
	mutation *NamedTypeWidgetMutation
}

// Where appends a list predicates to the NamedTypeWidgetUpdate builder.
func (ntwu *NamedTypeWidgetUpdate) Where(ps ...predicate.NamedTypeWidget) *NamedTypeWidgetUpdate {
	ntwu.mutation.Where(ps...)
	return ntwu
}

// SetLabels sets the "labels" field.
func (ntwu *NamedTypeWidgetUpdate) SetLabels(s schema.Tags) *NamedTypeWidgetUpdate {
	ntwu.mutation.SetLabels(s)
	return ntwu
}

// AppendLabels appends s to the "labels" field.
func (ntwu *NamedTypeWidgetUpdate) AppendLabels(s schema.Tags) *NamedTypeWidgetUpdate {
	ntwu.mutation.AppendLabels(s)
	return ntwu
}

// ClearLabels clears the value of the "labels" field.
func (ntwu *NamedTypeWidgetUpdate) ClearLabels() *NamedTypeWidgetUpdate {
	ntwu.mutation.ClearLabels()
	return ntwu
}

// SetAttrs sets the "attrs" field.
func (ntwu *NamedTypeWidgetUpdate) SetAttrs(s schema.Attrs) *NamedTypeWidgetUpdate {
	ntwu.mutation.SetAttrs(s)
	return ntwu
}

// ClearAttrs clears the value of the "attrs" field.
func (ntwu *NamedTypeWidgetUpdate) ClearAttrs() *NamedTypeWidgetUpdate {
	ntwu.mutation.ClearAttrs()
	return ntwu
}

// SetRequiredLabels sets the "required_labels" field.
func (ntwu *NamedTypeWidgetUpdate) SetRequiredLabels(s schema.Tags) *NamedTypeWidgetUpdate {
	ntwu.mutation.SetRequiredLabels(s)
	return ntwu
}

// AppendRequiredLabels appends s to the "required_labels" field.
func (ntwu *NamedTypeWidgetUpdate) AppendRequiredLabels(s schema.Tags) *NamedTypeWidgetUpdate {
	ntwu.mutation.AppendRequiredLabels(s)
	return ntwu
}

// SetRequiredAttrs sets the "required_attrs" field.
func (ntwu *NamedTypeWidgetUpdate) SetRequiredAttrs(s schema.Attrs) *NamedTypeWidgetUpdate {
	ntwu.mutation.SetRequiredAttrs(s)
	return ntwu
}

// Mutation returns the NamedTypeWidgetMutation object of the builder.
func (ntwu *NamedTypeWidgetUpdate) Mutation() *NamedTypeWidgetMutation {
	return ntwu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ntwu *NamedTypeWidgetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ntwu.sqlSave, ntwu.mutation, ntwu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ntwu *NamedTypeWidgetUpdate) SaveX(ctx context.Context) int {
	affected, err := ntwu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ntwu *NamedTypeWidgetUpdate) Exec(ctx context.Context) error {
	_, err := ntwu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ntwu *NamedTypeWidgetUpdate) ExecX(ctx context.Context) {
	if err := ntwu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ntwu *NamedTypeWidgetUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(namedtypewidget.Table, namedtypewidget.Columns, sqlgraph.NewFieldSpec(namedtypewidget.FieldID, field.TypeUUID))
	if ps := ntwu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ntwu.mutation.Labels(); ok {
		_spec.SetField(namedtypewidget.FieldLabels, field.TypeJSON, value)
	}
	if value, ok := ntwu.mutation.AppendedLabels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, namedtypewidget.FieldLabels, value)
		})
	}
	if ntwu.mutation.LabelsCleared() {
		_spec.ClearField(namedtypewidget.FieldLabels, field.TypeJSON)
	}
	if value, ok := ntwu.mutation.Attrs(); ok {
		_spec.SetField(namedtypewidget.FieldAttrs, field.TypeJSON, value)
	}
	if ntwu.mutation.AttrsCleared() {
		_spec.ClearField(namedtypewidget.FieldAttrs, field.TypeJSON)
	}
	if value, ok := ntwu.mutation.RequiredLabels(); ok {
		_spec.SetField(namedtypewidget.FieldRequiredLabels, field.TypeJSON, value)
	}
	if value, ok := ntwu.mutation.AppendedRequiredLabels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, namedtypewidget.FieldRequiredLabels, value)
		})
	}
	if value, ok := ntwu.mutation.RequiredAttrs(); ok {
		_spec.SetField(namedtypewidget.FieldRequiredAttrs, field.TypeJSON, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ntwu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{namedtypewidget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ntwu.mutation.done = true
	return n, nil
}

// NamedTypeWidgetUpdateOne is the builder for updating a single NamedTypeWidget entity.
type NamedTypeWidgetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NamedTypeWidgetMutation
}

// SetLabels sets the "labels" field.
func (ntwuo *NamedTypeWidgetUpdateOne) SetLabels(s schema.Tags) *NamedTypeWidgetUpdateOne {
	ntwuo.mutation.SetLabels(s)
	return ntwuo
}

// AppendLabels appends s to the "labels" field.
func (ntwuo *NamedTypeWidgetUpdateOne) AppendLabels(s schema.Tags) *NamedTypeWidgetUpdateOne {
	ntwuo.mutation.AppendLabels(s)
	return ntwuo
}

// ClearLabels clears the value of the "labels" field.
func (ntwuo *NamedTypeWidgetUpdateOne) ClearLabels() *NamedTypeWidgetUpdateOne {
	ntwuo.mutation.ClearLabels()
	return ntwuo
}

// SetAttrs sets the "attrs" field.
func (ntwuo *NamedTypeWidgetUpdateOne) SetAttrs(s schema.Attrs) *NamedTypeWidgetUpdateOne {
	ntwuo.mutation.SetAttrs(s)
	return ntwuo
}

// ClearAttrs clears the value of the "attrs" field.
func (ntwuo *NamedTypeWidgetUpdateOne) ClearAttrs() *NamedTypeWidgetUpdateOne {
	ntwuo.mutation.ClearAttrs()
	return ntwuo
}

// SetRequiredLabels sets the "required_labels" field.
func (ntwuo *NamedTypeWidgetUpdateOne) SetRequiredLabels(s schema.Tags) *NamedTypeWidgetUpdateOne {
	ntwuo.mutation.SetRequiredLabels(s)
	return ntwuo
}

// AppendRequiredLabels appends s to the "required_labels" field.
func (ntwuo *NamedTypeWidgetUpdateOne) AppendRequiredLabels(s schema.Tags) *NamedTypeWidgetUpdateOne {
	ntwuo.mutation.AppendRequiredLabels(s)
	return ntwuo
}

// SetRequiredAttrs sets the "required_attrs" field.
func (ntwuo *NamedTypeWidgetUpdateOne) SetRequiredAttrs(s schema.Attrs) *NamedTypeWidgetUpdateOne {
	ntwuo.mutation.SetRequiredAttrs(s)
	return ntwuo
}

// Mutation returns the NamedTypeWidgetMutation object of the builder.
func (ntwuo *NamedTypeWidgetUpdateOne) Mutation() *NamedTypeWidgetMutation {
	return ntwuo.mutation
}

// Where appends a list predicates to the NamedTypeWidgetUpdate builder.
func (ntwuo *NamedTypeWidgetUpdateOne) Where(ps ...predicate.NamedTypeWidget) *NamedTypeWidgetUpdateOne {
	ntwuo.mutation.Where(ps...)
	return ntwuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ntwuo *NamedTypeWidgetUpdateOne) Select(field string, fields ...string) *NamedTypeWidgetUpdateOne {
	ntwuo.fields = append([]string{field}, fields...)
	return ntwuo
}

// Save executes the query and returns the updated NamedTypeWidget entity.
func (ntwuo *NamedTypeWidgetUpdateOne) Save(ctx context.Context) (*NamedTypeWidget, error) {
	return withHooks(ctx, ntwuo.sqlSave, ntwuo.mutation, ntwuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ntwuo *NamedTypeWidgetUpdateOne) SaveX(ctx context.Context) *NamedTypeWidget {
	node, err := ntwuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ntwuo *NamedTypeWidgetUpdateOne) Exec(ctx context.Context) error {
	_, err := ntwuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ntwuo *NamedTypeWidgetUpdateOne) ExecX(ctx context.Context) {
	if err := ntwuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ntwuo *NamedTypeWidgetUpdateOne) sqlSave(ctx context.Context) (_node *NamedTypeWidget, err error) {
	_spec := sqlgraph.NewUpdateSpec(namedtypewidget.Table, namedtypewidget.Columns, sqlgraph.NewFieldSpec(namedtypewidget.FieldID, field.TypeUUID))
	id, ok := ntwuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`fieldshapesent: missing "NamedTypeWidget.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ntwuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, namedtypewidget.FieldID)
		for _, f := range fields {
			if !namedtypewidget.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("fieldshapesent: invalid field %q for query", f)}
			}
			if f != namedtypewidget.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ntwuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ntwuo.mutation.Labels(); ok {
		_spec.SetField(namedtypewidget.FieldLabels, field.TypeJSON, value)
	}
	if value, ok := ntwuo.mutation.AppendedLabels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, namedtypewidget.FieldLabels, value)
		})
	}
	if ntwuo.mutation.LabelsCleared() {
		_spec.ClearField(namedtypewidget.FieldLabels, field.TypeJSON)
	}
	if value, ok := ntwuo.mutation.Attrs(); ok {
		_spec.SetField(namedtypewidget.FieldAttrs, field.TypeJSON, value)
	}
	if ntwuo.mutation.AttrsCleared() {
		_spec.ClearField(namedtypewidget.FieldAttrs, field.TypeJSON)
	}
	if value, ok := ntwuo.mutation.RequiredLabels(); ok {
		_spec.SetField(namedtypewidget.FieldRequiredLabels, field.TypeJSON, value)
	}
	if value, ok := ntwuo.mutation.AppendedRequiredLabels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, namedtypewidget.FieldRequiredLabels, value)
		})
	}
	if value, ok := ntwuo.mutation.RequiredAttrs(); ok {
		_spec.SetField(namedtypewidget.FieldRequiredAttrs, field.TypeJSON, value)
	}
	_node = &NamedTypeWidget{config: ntwuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ntwuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{namedtypewidget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ntwuo.mutation.done = true
	return _node, nil
}
