// Code generated by entapi extension from schema "NillableWidget". DO NOT EDIT.
// Source template: templates/dto.tmpl
// Regenerate with: make generate

package fieldshapesent

import (
	"encoding/json"
	"fmt"
	"strings"

	entapi "github.com/githonllc/entapi/runtime"
	"github.com/google/uuid"
)

// ============================================================================================
// Layered Architecture Overview:
//
// 1. CreateRequest/PatchRequest - HTTP-layer request models derived from Ent.
//    - Hidden and ReadOnly are the only annotation-side request exclusions.
//    - Optional, Default, Nillable and Immutable determine the remaining shape.
//    - Used by the Handler layer to receive HTTP requests.
//    - Certain fields (e.g., ID, audit fields) cannot be set via the HTTP API.
//    - Presence is recorded per request, so an omitted key, an explicit null and
//      a value are three different things rather than two.
//    - Apply is defined on the VALIDATED request only, so a builder cannot be
//      written without validating first.
//
// 2. Response/Summary - HTTP-layer response models derived from Ent.
//    - Hidden and Ent Sensitive fields are excluded; ReadOnly fields remain.
//    - Includes a nested edge when the edge carries api.Expand().
//      Exposing the foreign-key scalar and exposing the nested object are
//      independent decisions; neither is derived from the other.
//    - A nested edge is rendered as the target's Summary, which carries no
//      edges of its own, so expansion terminates one level down.
//    - Used by the Handler layer to return HTTP responses.
//
// Key Design Principles:
// - transport → nillablewidget_wiring.go → entapi runtime → ent.Client
// - Deviation words affect HTTP generation only; they restrict nothing at the Ent layer.
// - The consumer's own code operates directly on ent entities with full ORM capabilities.
// ============================================================================================

// NillableWidgetCreateRequest is the create request for NillableWidget.
//
// Field shape follows ent's schema rather than a parallel set of booleans. A
// field ent can fill by itself — Optional, or carrying a Default() — is a
// pointer here and is written to the builder only when the caller supplied a
// value, so an omitted key leaves the schema's default in effect. A field ent
// requires and cannot default is a value type and is always written.
type NillableWidgetCreateRequest struct {
	Nickname *string `json:"nickname,omitempty"`
	Handle   *string `json:"handle,omitempty"`
	Quota    *int    `json:"quota,omitempty"`

	// present records which keys the payload actually carried. It is what makes
	// "omitted" distinguishable from "sent as the zero value" for a field whose
	// Go type has no nil — a required int or bool got no check at all while
	// requiredness was inferred from the zero value.
	//
	// A create request cannot express "clear", so an explicit null counts as
	// absent: it leaves the field unwritten, exactly like omitting the key.
	present map[string]bool
}

// nillableWidgetCreateRequestTags is the canonical JSON key of every field on
// NillableWidgetCreateRequest, in declaration order. UnmarshalJSON needs the tags as
// data, not as struct tags, to tell a case variant from an unrelated key.
var nillableWidgetCreateRequestTags = []string{"nickname", "handle", "quota"}

// NillableWidgetCreateRequestTags returns the canonical JSON key of every field on
// NillableWidgetCreateRequest, in declaration order. Generated handlers compare raw
// request keys against this data to reject unknown keys.
//
// Like Endpoints(), it returns a fresh copy on every call: slices are mutable, so
// exporting the variable would let any consumer mutate validation data that
// every generated handler in the process reads. The unexported variable remains
// the source of truth; this accessor is for consumers that decline the generated
// handler and write their own bind step.
func NillableWidgetCreateRequestTags() []string {
	return append([]string(nil), nillableWidgetCreateRequestTags...)
}

// UnmarshalJSON records presence, then decodes normally.
//
// The wire format is unchanged: every exported field keeps its ordinary type
// and tag, so marshalling, form binders, validators and spec generators all see
// the struct they saw before. That is the property a generic Optional[T]
// wrapper could not keep.
//
// A key that case-folds to a canonical tag without matching it exactly is
// rejected (#58, ADR-0001): encoding/json would fill the field from it while
// presence — recorded by raw key — would not, so the value decoded and then
// went unwritten. The check runs after raw decodes and BEFORE the alias decode,
// so a rejected request leaves the receiver untouched. A key that folds to no
// tag keeps its old behaviour and is ignored; refusing those is
// DisallowUnknownFields, which stays the consumer handler's decision.
func (r *NillableWidgetCreateRequest) UnmarshalJSON(b []byte) error {
	type alias NillableWidgetCreateRequest // breaks the UnmarshalJSON recursion
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	for k := range raw {
		for _, t := range nillableWidgetCreateRequestTags {
			if k != t && strings.EqualFold(k, t) {
				return fmt.Errorf("%w: unknown key %q (did you mean %q?)", entapi.ErrValidation, k, t)
			}
		}
	}
	if err := json.Unmarshal(b, (*alias)(r)); err != nil {
		return err
	}
	r.present = make(map[string]bool, len(raw))
	for k, v := range raw {
		if string(v) != "null" {
			r.present[k] = true
		}
	}
	return nil
}

// has reports whether the decoded payload carried a value for a key.
//
// A request built in Go rather than decoded from JSON recorded no presence at
// all, and there the struct is the only source of truth: every field reads as
// supplied, which is what the caller assigning to it meant. UnmarshalJSON always
// allocates the map, even for {}, so this fallback cannot fire on a decoded
// request. Reporting such a request as entirely absent instead would reject
// "seats is required" for a request that plainly sets Seats.
//
// The patch request deliberately does NOT do this: there, "unknown" has to mean
// absent, or a hand-built request would read as an instruction to clear
// everything.
func (r *NillableWidgetCreateRequest) has(field string) bool {
	if r.present == nil {
		return true
	}
	return r.present[field]
}

// HasNickname reports whether the payload carried "nickname".
func (r *NillableWidgetCreateRequest) HasNickname() bool { return r.has("nickname") }

// HasHandle reports whether the payload carried "handle".
func (r *NillableWidgetCreateRequest) HasHandle() bool { return r.has("handle") }

// HasQuota reports whether the payload carried "quota".
func (r *NillableWidgetCreateRequest) HasQuota() bool { return r.has("quota") }

// ValidNillableWidgetCreateRequest wraps a NillableWidgetCreateRequest that has
// passed Validate. Apply is defined on this type and nowhere else, so a caller
// who skips validation has no method to call — a compile error rather than a
// validator that runs only when someone remembers it.
type ValidNillableWidgetCreateRequest struct{ r *NillableWidgetCreateRequest }

// HasNickname reports whether the payload carried "nickname".
func (v *ValidNillableWidgetCreateRequest) HasNickname() bool { return v.r.HasNickname() }

// HasHandle reports whether the payload carried "handle".
func (v *ValidNillableWidgetCreateRequest) HasHandle() bool { return v.r.HasHandle() }

// HasQuota reports whether the payload carried "quota".
func (v *ValidNillableWidgetCreateRequest) HasQuota() bool { return v.r.HasQuota() }

// Validate checks the request and returns the only type Apply accepts.
func (r *NillableWidgetCreateRequest) Validate() (*ValidNillableWidgetCreateRequest, error) {
	if r == nil {
		return nil, fmt.Errorf("%w: create request is nil", entapi.ErrValidation)
	}
	return &ValidNillableWidgetCreateRequest{r: r}, nil
}

// Apply writes the request onto a create builder.
//
// A field the caller omitted is not written at all, so the schema's Default()
// still applies. Writing the zero value unconditionally is what silently
// defeated every schema default.
func (v *ValidNillableWidgetCreateRequest) Apply(b *NillableWidgetCreate) *NillableWidgetCreate {
	r := v.r
	if r.Nickname != nil {
		b.SetNickname(*r.Nickname)
	}
	if r.Handle != nil {
		b.SetHandle(*r.Handle)
	}
	if r.Quota != nil {
		b.SetQuota(*r.Quota)
	}
	return b
}

// NillableWidgetPatchRequest is the partial-update request for NillableWidget.
//
// Every field is a pointer and presence is recorded separately, which is what
// separates the three states a PATCH has to express: absent means "leave it
// alone", an explicit null means "clear it", and a value means "set it". With
// bare pointers the first two are the same value, and clearing a field cannot
// be expressed at all.
//
// A field the ent schema marks Immutable() is absent from this struct, because
// ent's update builders iterate MutableFields and generate no setter for one.
// encoding/json discards the key before any validator can see it, so a caller
// who sends it gets silence — rejecting that needs DisallowUnknownFields, which
// belongs to the consumer's handler.
type NillableWidgetPatchRequest struct {
	Nickname *string `json:"nickname,omitempty"`
	Handle   *string `json:"handle,omitempty"`
	Quota    *int    `json:"quota,omitempty"`

	present map[string]bool
}

// nillableWidgetPatchRequestTags is the canonical JSON key of every field on
// NillableWidgetPatchRequest, in declaration order.
var nillableWidgetPatchRequestTags = []string{"nickname", "handle", "quota"}

// NillableWidgetPatchRequestTags returns the canonical JSON key of every field on
// NillableWidgetPatchRequest, in declaration order. Generated handlers compare raw
// request keys against this data to reject unknown keys.
//
// Like Endpoints(), it returns a fresh copy on every call: slices are mutable, so
// exporting the variable would let any consumer mutate validation data that
// every generated handler in the process reads. The unexported variable remains
// the source of truth; this accessor is for consumers that decline the generated
// handler and write their own bind step.
func NillableWidgetPatchRequestTags() []string {
	return append([]string(nil), nillableWidgetPatchRequestTags...)
}

// UnmarshalJSON records which keys the payload carried, including the ones
// whose value was null — that is the whole point here, and the difference from
// the create request, where a null has nothing to clear.
//
// A key that case-folds to a canonical tag without matching it exactly is
// rejected (#58, ADR-0001). The patch side is where that mattered most: a
// case-variant key decoded into the field while Has<Field>() stayed false, so
// Apply wrote nothing and the update reported success having changed no row —
// and a payload carrying BOTH spellings could clear a field the exact key had
// just set. The check runs after raw decodes and BEFORE the alias decode, so a
// rejected request leaves the receiver untouched.
func (r *NillableWidgetPatchRequest) UnmarshalJSON(b []byte) error {
	type alias NillableWidgetPatchRequest // breaks the UnmarshalJSON recursion
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	for k := range raw {
		for _, t := range nillableWidgetPatchRequestTags {
			if k != t && strings.EqualFold(k, t) {
				return fmt.Errorf("%w: unknown key %q (did you mean %q?)", entapi.ErrValidation, k, t)
			}
		}
	}
	if err := json.Unmarshal(b, (*alias)(r)); err != nil {
		return err
	}
	r.present = make(map[string]bool, len(raw))
	for k := range raw {
		r.present[k] = true
	}
	return nil
}

// has reports whether the decoded payload carried the key at all. A request
// built in Go rather than decoded from JSON has no presence, and Apply writes
// nothing for it.
func (r *NillableWidgetPatchRequest) has(field string) bool { return r.present[field] }

// HasNickname reports whether the payload carried "nickname".
func (r *NillableWidgetPatchRequest) HasNickname() bool { return r.has("nickname") }

// HasHandle reports whether the payload carried "handle".
func (r *NillableWidgetPatchRequest) HasHandle() bool { return r.has("handle") }

// HasQuota reports whether the payload carried "quota".
func (r *NillableWidgetPatchRequest) HasQuota() bool { return r.has("quota") }

// ValidNillableWidgetPatchRequest wraps a NillableWidgetPatchRequest that has passed
// Validate. It is the only type Apply is defined on.
type ValidNillableWidgetPatchRequest struct{ r *NillableWidgetPatchRequest }

// HasNickname reports whether the payload carried "nickname".
//
// A custom implementation receives only the validated type, so without this
// forwarder the patch's presence — the one thing that distinguishes "clear it"
// from "leave it alone" — is unreachable from the customization point that is
// supposed to act on it.
func (v *ValidNillableWidgetPatchRequest) HasNickname() bool { return v.r.HasNickname() }

// Nickname reports the value the payload carried for
// "nickname", and whether Apply will Set it.
//
// Presence is two of the three states a PATCH field has; this reads the third.
// Paired with HasNickname(), which is "present" below:
//
//	ok                    the payload carried a value; Apply will Set it
//	!ok, present          the payload carried an explicit null; Apply will
//	                      Clear it. Reachable only for a clearable field —
//	                      Validate refuses a null on anything else
//	!ok, absent           the key was not in the payload; Apply writes nothing
//
// Without it a cross-field rule cannot tell "clear this" from "set this", and
// the customization point is forced to allocate an update builder it never
// executes, Apply the request to it and read back Mutation() (#113).
func (v *ValidNillableWidgetPatchRequest) Nickname() (string, bool) {
	if !v.r.HasNickname() || v.r.Nickname == nil {
		var zero string
		return zero, false
	}
	return *v.r.Nickname, true
}

// HasHandle reports whether the payload carried "handle".
//
// A custom implementation receives only the validated type, so without this
// forwarder the patch's presence — the one thing that distinguishes "clear it"
// from "leave it alone" — is unreachable from the customization point that is
// supposed to act on it.
func (v *ValidNillableWidgetPatchRequest) HasHandle() bool { return v.r.HasHandle() }

// Handle reports the value the payload carried for
// "handle", and whether Apply will Set it.
//
// Presence is two of the three states a PATCH field has; this reads the third.
// Paired with HasHandle(), which is "present" below:
//
//	ok                    the payload carried a value; Apply will Set it
//	!ok, present          the payload carried an explicit null; Apply will
//	                      Clear it. Reachable only for a clearable field —
//	                      Validate refuses a null on anything else
//	!ok, absent           the key was not in the payload; Apply writes nothing
//
// Without it a cross-field rule cannot tell "clear this" from "set this", and
// the customization point is forced to allocate an update builder it never
// executes, Apply the request to it and read back Mutation() (#113).
func (v *ValidNillableWidgetPatchRequest) Handle() (string, bool) {
	if !v.r.HasHandle() || v.r.Handle == nil {
		var zero string
		return zero, false
	}
	return *v.r.Handle, true
}

// HasQuota reports whether the payload carried "quota".
//
// A custom implementation receives only the validated type, so without this
// forwarder the patch's presence — the one thing that distinguishes "clear it"
// from "leave it alone" — is unreachable from the customization point that is
// supposed to act on it.
func (v *ValidNillableWidgetPatchRequest) HasQuota() bool { return v.r.HasQuota() }

// Quota reports the value the payload carried for
// "quota", and whether Apply will Set it.
//
// Presence is two of the three states a PATCH field has; this reads the third.
// Paired with HasQuota(), which is "present" below:
//
//	ok                    the payload carried a value; Apply will Set it
//	!ok, present          the payload carried an explicit null; Apply will
//	                      Clear it. Reachable only for a clearable field —
//	                      Validate refuses a null on anything else
//	!ok, absent           the key was not in the payload; Apply writes nothing
//
// Without it a cross-field rule cannot tell "clear this" from "set this", and
// the customization point is forced to allocate an update builder it never
// executes, Apply the request to it and read back Mutation() (#113).
func (v *ValidNillableWidgetPatchRequest) Quota() (int, bool) {
	if !v.r.HasQuota() || v.r.Quota == nil {
		var zero int
		return zero, false
	}
	return *v.r.Quota, true
}

// Validate rejects an explicit null on a field that cannot be cleared.
//
// ent emits Clear<Field>() for Optional fields and for no others, so a null on
// anything else has no correct translation: the column is NOT NULL and there is
// no method to call. The field is named in the error, because "invalid request"
// tells the caller nothing about which key to fix.
func (r *NillableWidgetPatchRequest) Validate() (*ValidNillableWidgetPatchRequest, error) {
	if r == nil {
		return nil, fmt.Errorf("%w: patch request is nil", entapi.ErrValidation)
	}
	return &ValidNillableWidgetPatchRequest{r: r}, nil
}

// Apply writes the request onto an update builder. Absent fields are not
// touched; the rest are set, or cleared when the caller sent an explicit null.
func (v *ValidNillableWidgetPatchRequest) Apply(b *NillableWidgetUpdateOne) *NillableWidgetUpdateOne {
	r := v.r
	if r.HasNickname() {
		if r.Nickname == nil {
			b.ClearNickname()
		} else {
			b.SetNickname(*r.Nickname)
		}
	}
	if r.HasHandle() {
		if r.Handle == nil {
			b.ClearHandle()
		} else {
			b.SetHandle(*r.Handle)
		}
	}
	if r.HasQuota() {
		if r.Quota == nil {
			b.ClearQuota()
		} else {
			b.SetQuota(*r.Quota)
		}
	}
	return b
}

// NillableWidgetSummary is the shape NillableWidget takes on another entity's response.
//
// It carries the same scalar fields as NillableWidgetResponse and no edges at all.
// That is what bounds expansion: NewNillableWidgetResponse calls summary
// constructors, and a summary constructor calls nothing, so there is no second
// level for a cycle to close through and no runtime depth counter is needed.
//
// The cost is real rather than hidden: a three-level tree comes back one level
// deep, and a deeper one needs another round trip per level.
type NillableWidgetSummary struct {
	// ID field is always included in summaries
	ID       uuid.UUID `json:"id"`
	Nickname *string   `json:"nickname,omitempty"`
	Handle   *string   `json:"handle,omitempty"`
	Quota    *int      `json:"quota,omitempty"`
}

// NewNillableWidgetSummary converts an entity to its summary DTO. It cannot fail:
// a summary reads no edges.
func NewNillableWidgetSummary(e *NillableWidget) *NillableWidgetSummary {
	if e == nil {
		return nil
	}
	return &NillableWidgetSummary{
		ID:       e.ID,
		Nickname: e.Nickname,
		Handle:   e.Handle,
		Quota:    e.Quota,
	}
}

// NillableWidgetResponse represents the response for NillableWidget.
//
// It is emitted unconditionally: an entity whose every scalar field is
// Sensitive still has a meaningful response carrying its ID, and
// NillableWidgetListResponse below refers to this type either way.
type NillableWidgetResponse struct {
	// ID field is always included in responses
	ID       uuid.UUID `json:"id"`
	Nickname *string   `json:"nickname,omitempty"`
	Handle   *string   `json:"handle,omitempty"`
	Quota    *int      `json:"quota,omitempty"`
}

// NewNillableWidgetResponse converts an entity to its response DTO.
//
// This entity declares no response edges, so the error is always nil. The
// signature is kept uniform so callers do not need two shapes.
func NewNillableWidgetResponse(e *NillableWidget) (*NillableWidgetResponse, error) {
	if e == nil {
		return nil, nil
	}
	r := &NillableWidgetResponse{
		ID:       e.ID,
		Nickname: e.Nickname,
		Handle:   e.Handle,
		Quota:    e.Quota,
	}
	return r, nil
}

// NillableWidgetQueryWithResponseEdges applies the eager-load plan for NillableWidgetResponse.
//
// The plan is generated from the response type's own edge set, so no individual
// edge can be omitted from it. Generated wiring always routes through this
// function.
//
// For a hand-written query, using this function is a convention the type
// system does not enforce. An entity loaded without this plan makes
// NewNillableWidgetResponse return a not-loaded-edge error at run time. It fails
// loudly; it never silently narrows the response.
//
// With no expanded edges, this function is the identity function. It exists so
// every entity has the same call shape.
func NillableWidgetQueryWithResponseEdges(q *NillableWidgetQuery) *NillableWidgetQuery {
	return q
}

// NillableWidgetListResponse is the NAMED, non-generic shape of one list page —
// for OpenAPI/swaggo-class annotation tooling, which cannot express the
// generic entapi.Page[NillableWidgetResponse] that ListNillableWidgets returns.
// Convert at the handler boundary with NewNillableWidgetListResponse.
// (A fifth field, PageInfo, carried cursor metadata until #6 removed it.)
type NillableWidgetListResponse struct {
	Data  []*NillableWidgetResponse `json:"data"`
	Total int                       `json:"total"`
	Page  int                       `json:"page"`
	Size  int                       `json:"size"`
}

// NewNillableWidgetListResponse converts the page ListNillableWidgets returns into
// the named list shape. The conversion expression is the shape contract:
// if NillableWidgetListResponse and entapi.Page ever diverge in field set,
// type or order, this line stops compiling in every generated package.
// JSON tags are outside what a conversion checks; the wire-format golden
// test in the basic fixture guards those.
func NewNillableWidgetListResponse(p *entapi.Page[NillableWidgetResponse]) *NillableWidgetListResponse {
	if p == nil {
		return nil
	}
	r := NillableWidgetListResponse(*p)
	return &r
}
