// Code generated by entapi extension from schema "Todo". DO NOT EDIT.
// Source template: templates/filter.tmpl
// Regenerate with: make generate

package todoent

import (
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"entgo.io/ent/dialect/sql"

	"github.com/githonllc/entapi/examples/todo/todoent/predicate"
	"github.com/githonllc/entapi/examples/todo/todoent/todo"
	entapi "github.com/githonllc/entapi/runtime"
)

// TodoFilter is the typed query representation for Todo.
// Repeated URL parameters occupy repeated slots and Predicates ANDs them.
type TodoFilter struct {
	// id: int
	ID      []int   `json:"id,omitempty"`
	IDNEQ   []int   `json:"id_neq,omitempty"`
	IDIn    [][]int `json:"id_in,omitempty"`
	IDNotIn [][]int `json:"id_not_in,omitempty"`
	IDGT    []int   `json:"id_gt,omitempty"`
	IDGTE   []int   `json:"id_gte,omitempty"`
	IDLT    []int   `json:"id_lt,omitempty"`
	IDLTE   []int   `json:"id_lte,omitempty"`
	// title: string
	Title             []string   `json:"title,omitempty"`
	TitleNEQ          []string   `json:"title_neq,omitempty"`
	TitleIn           [][]string `json:"title_in,omitempty"`
	TitleNotIn        [][]string `json:"title_not_in,omitempty"`
	TitleGT           []string   `json:"title_gt,omitempty"`
	TitleGTE          []string   `json:"title_gte,omitempty"`
	TitleLT           []string   `json:"title_lt,omitempty"`
	TitleLTE          []string   `json:"title_lte,omitempty"`
	TitleContains     []string   `json:"title_contains,omitempty"`
	TitleHasPrefix    []string   `json:"title_prefix,omitempty"`
	TitleHasSuffix    []string   `json:"title_suffix,omitempty"`
	TitleContainsFold []string   `json:"title_icontains,omitempty"`
	// done: bool, optional
	Done       []bool `json:"done,omitempty"`
	DoneNEQ    []bool `json:"done_neq,omitempty"`
	DoneIsNull []bool `json:"done_is_null,omitempty"`
	// priority: int, optional
	Priority       []int   `json:"priority,omitempty"`
	PriorityNEQ    []int   `json:"priority_neq,omitempty"`
	PriorityIn     [][]int `json:"priority_in,omitempty"`
	PriorityNotIn  [][]int `json:"priority_not_in,omitempty"`
	PriorityGT     []int   `json:"priority_gt,omitempty"`
	PriorityGTE    []int   `json:"priority_gte,omitempty"`
	PriorityLT     []int   `json:"priority_lt,omitempty"`
	PriorityLTE    []int   `json:"priority_lte,omitempty"`
	PriorityIsNull []bool  `json:"priority_is_null,omitempty"`
	// Q is the single free-text term matched across Searchable fields.
	Q *string `json:"_q,omitempty"`
}

// Predicates converts the typed filter into conjunctive ent predicates.
func (f *TodoFilter) Predicates() []predicate.Todo {
	if f == nil {
		return nil
	}
	var ps []predicate.Todo
	entapi.AppendEach(&ps, f.ID, todo.IDEQ)
	entapi.AppendEach(&ps, f.IDNEQ, todo.IDNEQ)
	entapi.AppendEachSlice(&ps, f.IDIn, todo.IDIn)
	entapi.AppendEachSlice(&ps, f.IDNotIn, todo.IDNotIn)
	entapi.AppendEach(&ps, f.IDGT, todo.IDGT)
	entapi.AppendEach(&ps, f.IDGTE, todo.IDGTE)
	entapi.AppendEach(&ps, f.IDLT, todo.IDLT)
	entapi.AppendEach(&ps, f.IDLTE, todo.IDLTE)
	entapi.AppendEach(&ps, f.Title, todo.TitleEQ)
	entapi.AppendEach(&ps, f.TitleNEQ, todo.TitleNEQ)
	entapi.AppendEachSlice(&ps, f.TitleIn, todo.TitleIn)
	entapi.AppendEachSlice(&ps, f.TitleNotIn, todo.TitleNotIn)
	entapi.AppendEach(&ps, f.TitleGT, todo.TitleGT)
	entapi.AppendEach(&ps, f.TitleGTE, todo.TitleGTE)
	entapi.AppendEach(&ps, f.TitleLT, todo.TitleLT)
	entapi.AppendEach(&ps, f.TitleLTE, todo.TitleLTE)
	entapi.AppendEach(&ps, f.TitleContains, todo.TitleContains)
	entapi.AppendEach(&ps, f.TitleHasPrefix, todo.TitleHasPrefix)
	entapi.AppendEach(&ps, f.TitleHasSuffix, todo.TitleHasSuffix)
	entapi.AppendEach(&ps, f.TitleContainsFold, todo.TitleContainsFold)
	entapi.AppendEach(&ps, f.Done, todo.DoneEQ)
	entapi.AppendEach(&ps, f.DoneNEQ, todo.DoneNEQ)
	for _, isNull := range f.DoneIsNull {
		if isNull {
			ps = append(ps, todo.DoneIsNil())
		} else {
			ps = append(ps, todo.DoneNotNil())
		}
	}
	entapi.AppendEach(&ps, f.Priority, todo.PriorityEQ)
	entapi.AppendEach(&ps, f.PriorityNEQ, todo.PriorityNEQ)
	entapi.AppendEachSlice(&ps, f.PriorityIn, todo.PriorityIn)
	entapi.AppendEachSlice(&ps, f.PriorityNotIn, todo.PriorityNotIn)
	entapi.AppendEach(&ps, f.PriorityGT, todo.PriorityGT)
	entapi.AppendEach(&ps, f.PriorityGTE, todo.PriorityGTE)
	entapi.AppendEach(&ps, f.PriorityLT, todo.PriorityLT)
	entapi.AppendEach(&ps, f.PriorityLTE, todo.PriorityLTE)
	for _, isNull := range f.PriorityIsNull {
		if isNull {
			ps = append(ps, todo.PriorityIsNil())
		} else {
			ps = append(ps, todo.PriorityNotNil())
		}
	}
	if f.Q != nil && *f.Q != "" {
		ps = append(ps, todo.Or(
			todo.TitleContains(*f.Q),
		))
	}
	return ps
}

func parseTodoIDQueryValue(raw, whole string) (int, error) {
	parsed, err := strconv.ParseInt(raw, 10, 0)
	if err != nil {
		var zero int
		return zero, fmt.Errorf("%w: field %q value %q is not a valid int: %v", entapi.ErrValidation, "id", whole, err)
	}
	return int(parsed), nil
}

func parseTodoTitleQueryValue(raw, whole string) (string, error) {
	return string(raw), nil
}

func parseTodoDoneQueryValue(raw, whole string) (bool, error) {
	parsed, err := strconv.ParseBool(raw)
	if err != nil {
		var zero bool
		return zero, fmt.Errorf("%w: field %q value %q is not a bool: %v", entapi.ErrValidation, "done", whole, err)
	}
	return bool(parsed), nil
}

func parseTodoPriorityQueryValue(raw, whole string) (int, error) {
	parsed, err := strconv.ParseInt(raw, 10, 0)
	if err != nil {
		var zero int
		return zero, fmt.Errorf("%w: field %q value %q is not a valid int: %v", entapi.ErrValidation, "priority", whole, err)
	}
	return int(parsed), nil
}

// ParseTodoQuery parses the complete URL query contract in sorted-key
// order. Runtime code owns lexical grammar; the generated operator tables own
// the field-local operator set, conversion and predicate slots.
func ParseTodoQuery(q url.Values) (*TodoFilter, entapi.ListRequest, error) {
	f := &TodoFilter{}
	var request entapi.ListRequest
	keys := make([]string, 0, len(q))
	for key := range q {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		values := q[key]
		reserved, recognized, err := entapi.ReservedQueryValue(key, values)
		if err != nil {
			return nil, entapi.ListRequest{}, err
		}
		if recognized {
			switch key {
			case "_sort":
				request.Sort, err = entapi.ParseSortSpecs(reserved)
			case "_page":
				request.Page, err = entapi.ParsePageParam(key, reserved)
			case "_size":
				request.Size, err = entapi.ParsePageParam(key, reserved)
			case "_q":
				term := reserved
				f.Q = &term
			}
			if err != nil {
				return nil, entapi.ListRequest{}, err
			}
			continue
		}
		if strings.HasPrefix(key, "_") {
			return nil, entapi.ListRequest{}, fmt.Errorf("%w: unknown reserved query parameter %q", entapi.ErrValidation, key)
		}
		switch key {
		case "id":
			if err := entapi.ParseFieldValues("id", values, false, "eq, ne, in, not_in, gt, ge, lt, le, from, to, between", parseTodoIDQueryValue, []entapi.QueryOp[int]{
				{Prefix: "eq", Kind: entapi.OpKindValue, One: &f.ID},
				{Prefix: "ne", Kind: entapi.OpKindValue, One: &f.IDNEQ},
				{Prefix: "in", Kind: entapi.OpKindList, Many: &f.IDIn},
				{Prefix: "not_in", Kind: entapi.OpKindList, Many: &f.IDNotIn},
				{Prefix: "gt", Kind: entapi.OpKindValue, One: &f.IDGT},
				{Prefix: "ge", Kind: entapi.OpKindValue, One: &f.IDGTE},
				{Prefix: "lt", Kind: entapi.OpKindValue, One: &f.IDLT},
				{Prefix: "le", Kind: entapi.OpKindValue, One: &f.IDLTE},
				{Prefix: "from", Kind: entapi.OpKindValue, One: &f.IDGTE},
				{Prefix: "to", Kind: entapi.OpKindValue, One: &f.IDLTE},
				{Prefix: "between", Kind: entapi.OpKindRange, One: &f.IDGTE, Second: &f.IDLTE},
			}); err != nil {
				return nil, entapi.ListRequest{}, err
			}
		case "title":
			if err := entapi.ParseFieldValues("title", values, false, "eq, ne, in, not_in, gt, ge, lt, le, like, prefix, suffix, ilike, from, to, between", parseTodoTitleQueryValue, []entapi.QueryOp[string]{
				{Prefix: "eq", Kind: entapi.OpKindValue, One: &f.Title},
				{Prefix: "ne", Kind: entapi.OpKindValue, One: &f.TitleNEQ},
				{Prefix: "in", Kind: entapi.OpKindList, Many: &f.TitleIn},
				{Prefix: "not_in", Kind: entapi.OpKindList, Many: &f.TitleNotIn},
				{Prefix: "gt", Kind: entapi.OpKindValue, One: &f.TitleGT},
				{Prefix: "ge", Kind: entapi.OpKindValue, One: &f.TitleGTE},
				{Prefix: "lt", Kind: entapi.OpKindValue, One: &f.TitleLT},
				{Prefix: "le", Kind: entapi.OpKindValue, One: &f.TitleLTE},
				{Prefix: "like", Kind: entapi.OpKindValue, One: &f.TitleContains},
				{Prefix: "prefix", Kind: entapi.OpKindValue, One: &f.TitleHasPrefix},
				{Prefix: "suffix", Kind: entapi.OpKindValue, One: &f.TitleHasSuffix},
				{Prefix: "ilike", Kind: entapi.OpKindValue, One: &f.TitleContainsFold},
				{Prefix: "from", Kind: entapi.OpKindValue, One: &f.TitleGTE},
				{Prefix: "to", Kind: entapi.OpKindValue, One: &f.TitleLTE},
				{Prefix: "between", Kind: entapi.OpKindRange, One: &f.TitleGTE, Second: &f.TitleLTE},
			}); err != nil {
				return nil, entapi.ListRequest{}, err
			}
		case "done":
			if err := entapi.ParseFieldValues("done", values, false, "eq, ne, is_null, not_null", parseTodoDoneQueryValue, []entapi.QueryOp[bool]{
				{Prefix: "eq", Kind: entapi.OpKindValue, One: &f.Done},
				{Prefix: "ne", Kind: entapi.OpKindValue, One: &f.DoneNEQ},
				{Prefix: "is_null", Kind: entapi.OpKindFlag, Null: &f.DoneIsNull, BoolValue: true},
				{Prefix: "not_null", Kind: entapi.OpKindFlag, Null: &f.DoneIsNull, BoolValue: false},
			}); err != nil {
				return nil, entapi.ListRequest{}, err
			}
		case "priority":
			if err := entapi.ParseFieldValues("priority", values, false, "eq, ne, in, not_in, gt, ge, lt, le, is_null, not_null, from, to, between", parseTodoPriorityQueryValue, []entapi.QueryOp[int]{
				{Prefix: "eq", Kind: entapi.OpKindValue, One: &f.Priority},
				{Prefix: "ne", Kind: entapi.OpKindValue, One: &f.PriorityNEQ},
				{Prefix: "in", Kind: entapi.OpKindList, Many: &f.PriorityIn},
				{Prefix: "not_in", Kind: entapi.OpKindList, Many: &f.PriorityNotIn},
				{Prefix: "gt", Kind: entapi.OpKindValue, One: &f.PriorityGT},
				{Prefix: "ge", Kind: entapi.OpKindValue, One: &f.PriorityGTE},
				{Prefix: "lt", Kind: entapi.OpKindValue, One: &f.PriorityLT},
				{Prefix: "le", Kind: entapi.OpKindValue, One: &f.PriorityLTE},
				{Prefix: "is_null", Kind: entapi.OpKindFlag, Null: &f.PriorityIsNull, BoolValue: true},
				{Prefix: "not_null", Kind: entapi.OpKindFlag, Null: &f.PriorityIsNull, BoolValue: false},
				{Prefix: "from", Kind: entapi.OpKindValue, One: &f.PriorityGTE},
				{Prefix: "to", Kind: entapi.OpKindValue, One: &f.PriorityLTE},
				{Prefix: "between", Kind: entapi.OpKindRange, One: &f.PriorityGTE, Second: &f.PriorityLTE},
			}); err != nil {
				return nil, entapi.ListRequest{}, err
			}
		default:
			switch key {
			case "created_at":
				return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q with value %q is not Filterable", entapi.ErrValidation, key, values)
			default:
				return nil, entapi.ListRequest{}, fmt.Errorf("%w: unknown query field %q with value %q", entapi.ErrValidation, key, values)
			}
		}
	}
	return f, request, nil
}

var todoSortOptions = map[string]func(...sql.OrderTermOption) todo.OrderOption{
	"id":         todo.ByID,
	"title":      todo.ByTitle,
	"priority":   todo.ByPriority,
	"created_at": todo.ByCreatedAt,
}

// TodoSortKeys is the complete sort allow-list. The primary key is
// naturally Sortable; every other key requires api.Sortable().
var TodoSortKeys = []string{
	"id", "title", "priority", "created_at",
}

// TodoOrder is the single sort allow-list seam.
func TodoOrder(r entapi.ListRequest) ([]todo.OrderOption, error) {
	if len(r.Sort) == 0 {
		return []todo.OrderOption{todo.ByID(sql.OrderAsc())}, nil
	}
	orderBy := make([]todo.OrderOption, 0, len(r.Sort)+1)
	idPresent := false
	lastDir := sql.OrderAsc()
	for _, spec := range r.Sort {
		by, ok := todoSortOptions[spec.Key]
		if !ok {
			return nil, fmt.Errorf("%w: cannot sort by %q; legal keys: %s", entapi.ErrValidation, spec.Key, strings.Join(TodoSortKeys, ", "))
		}
		dir := sql.OrderAsc()
		if spec.Desc {
			dir = sql.OrderDesc()
		}
		orderBy = append(orderBy, by(dir))
		lastDir = dir
		if spec.Key == "id" {
			idPresent = true
		}
	}
	if !idPresent {
		orderBy = append(orderBy, todo.ByID(lastDir))
	}
	return orderBy, nil
}
