// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/githonllc/entdomain/internal/fixtures/query/ent/plain"
	"github.com/githonllc/entdomain/internal/fixtures/query/ent/record"
	"github.com/githonllc/entdomain/internal/fixtures/query/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	plainFields := schema.Plain{}.Fields()
	_ = plainFields
	// plainDescID is the schema descriptor for id field.
	plainDescID := plainFields[0].Descriptor()
	// plain.DefaultID holds the default value on creation for the id field.
	plain.DefaultID = plainDescID.Default.(func() uuid.UUID)
	recordFields := schema.Record{}.Fields()
	_ = recordFields
	// recordDescCreatedAt is the schema descriptor for created_at field.
	recordDescCreatedAt := recordFields[5].Descriptor()
	// record.DefaultCreatedAt holds the default value on creation for the created_at field.
	record.DefaultCreatedAt = recordDescCreatedAt.Default.(func() time.Time)
	// recordDescID is the schema descriptor for id field.
	recordDescID := recordFields[0].Descriptor()
	// record.DefaultID holds the default value on creation for the id field.
	record.DefaultID = recordDescID.Default.(func() uuid.UUID)
}
