package entdomain

import (
	"os"
	"path/filepath"
	"testing"

	"entgo.io/ent/entc/gen"
)

// entdomainHeader is a realistic generated header — the thing cleanup keys on.
const entdomainHeader = `// Code generated by entdomain extension from schema "Widget" (entschema/schema/widget.go). DO NOT EDIT.

package ent
`

// entHeader is ent's own generated header. Cleanup must not match it: ent's
// files sit in the same directory.
const entHeader = `// Code generated by ent, DO NOT EDIT.

package ent
`

func seed(t *testing.T, dir, name, content string) string {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("seeding %s: %v", path, err)
	}
	return path
}

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func TestRemoveStaleArtifacts_RemovesOwnedFilesNotWrittenThisRun(t *testing.T) {
	dir := t.TempDir()
	dto := seed(t, dir, "widget_dto.go", entdomainHeader)
	svc := seed(t, dir, "widget_base_service.go", entdomainHeader)
	handler := seed(t, dir, "widget_base_handler.go", entdomainHeader)

	nodes := []*gen.Type{newTestType("Widget")}
	if err := removeStaleArtifacts(dir, nodes, map[string]bool{}); err != nil {
		t.Fatalf("removeStaleArtifacts: %v", err)
	}

	for _, path := range []string{dto, svc, handler} {
		if exists(path) {
			t.Errorf("%s survived: it carries the entdomain marker and this run did not write it", path)
		}
	}
}

func TestRemoveStaleArtifacts_KeepsFilesWrittenThisRun(t *testing.T) {
	dir := t.TempDir()
	dto := seed(t, dir, "widget_dto.go", entdomainHeader)

	nodes := []*gen.Type{newTestType("Widget")}
	if err := removeStaleArtifacts(dir, nodes, map[string]bool{dto: true}); err != nil {
		t.Fatalf("removeStaleArtifacts: %v", err)
	}

	if !exists(dto) {
		t.Error("cleanup deleted a file this run had just written")
	}
}

// TestRemoveStaleArtifacts_KeepsUnmarkedFiles is the criterion the whole rule
// exists for: these are files in someone's repository.
func TestRemoveStaleArtifacts_KeepsUnmarkedFiles(t *testing.T) {
	cases := map[string]string{
		"hand-written, no header at all":    "package ent\n\ntype Widget struct{}\n",
		"ent's own generated header":        entHeader,
		"marker edited into something else": "// Code generated by something else. DO NOT EDIT.\n\npackage ent\n",
		"marker below the header":           "package ent\n\n// mentions Code generated by entdomain extension in prose\n",
	}

	for name, content := range cases {
		t.Run(name, func(t *testing.T) {
			dir := t.TempDir()
			path := seed(t, dir, "widget_dto.go", content)

			nodes := []*gen.Type{newTestType("Widget")}
			if err := removeStaleArtifacts(dir, nodes, map[string]bool{}); err != nil {
				t.Fatalf("removeStaleArtifacts: %v", err)
			}

			if !exists(path) {
				t.Fatalf("cleanup deleted %s, which this extension did not write", path)
			}
		})
	}
}

// TestRemoveStaleArtifacts_IgnoresUnrelatedFiles pins the first fence: only
// names this extension can produce, for entities in the current schema.
func TestRemoveStaleArtifacts_IgnoresUnrelatedFiles(t *testing.T) {
	dir := t.TempDir()
	// Same marker, but not a name this extension produces for Widget.
	other := seed(t, dir, "widget_service.go", entdomainHeader)
	// A name it does produce, but for an entity the schema no longer has at
	// all — indistinguishable from a consumer's file, so it is left alone.
	gone := seed(t, dir, "gadget_dto.go", entdomainHeader)

	nodes := []*gen.Type{newTestType("Widget")}
	if err := removeStaleArtifacts(dir, nodes, map[string]bool{}); err != nil {
		t.Fatalf("removeStaleArtifacts: %v", err)
	}

	if !exists(other) {
		t.Error("cleanup deleted widget_service.go, which is not a name this extension produces")
	}
	if !exists(gone) {
		t.Error("cleanup deleted gadget_dto.go: the entity is not in the schema this run examined")
	}
}

func TestRemoveStaleArtifacts_MissingFilesAreNotAnError(t *testing.T) {
	dir := t.TempDir()
	nodes := []*gen.Type{newTestType("Widget")}
	if err := removeStaleArtifacts(dir, nodes, map[string]bool{}); err != nil {
		t.Fatalf("removeStaleArtifacts on an empty directory: %v", err)
	}
}

func TestGeneratedFileNames(t *testing.T) {
	got := generatedFileNames(newTestType("UserProfile"))
	want := []string{"userprofile_dto.go", "userprofile_base_service.go", "userprofile_base_handler.go"}

	if len(got) != len(want) {
		t.Fatalf("generatedFileNames() = %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("generatedFileNames()[%d] = %q, want %q", i, got[i], want[i])
		}
	}
}
