// Code generated by ent, DO NOT EDIT.

package basicent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/githonllc/entapi/internal/fixtures/basic/basicent/widget"
	"github.com/google/uuid"
)

// WidgetCreate is the builder for creating a Widget entity.
type WidgetCreate struct {
	config
	mutation *WidgetMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (wc *WidgetCreate) SetName(s string) *WidgetCreate {
	wc.mutation.SetName(s)
	return wc
}

// SetDescription sets the "description" field.
func (wc *WidgetCreate) SetDescription(s string) *WidgetCreate {
	wc.mutation.SetDescription(s)
	return wc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (wc *WidgetCreate) SetNillableDescription(s *string) *WidgetCreate {
	if s != nil {
		wc.SetDescription(*s)
	}
	return wc
}

// SetCreatedAt sets the "created_at" field.
func (wc *WidgetCreate) SetCreatedAt(t time.Time) *WidgetCreate {
	wc.mutation.SetCreatedAt(t)
	return wc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wc *WidgetCreate) SetNillableCreatedAt(t *time.Time) *WidgetCreate {
	if t != nil {
		wc.SetCreatedAt(*t)
	}
	return wc
}

// SetID sets the "id" field.
func (wc *WidgetCreate) SetID(u uuid.UUID) *WidgetCreate {
	wc.mutation.SetID(u)
	return wc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (wc *WidgetCreate) SetNillableID(u *uuid.UUID) *WidgetCreate {
	if u != nil {
		wc.SetID(*u)
	}
	return wc
}

// Mutation returns the WidgetMutation object of the builder.
func (wc *WidgetCreate) Mutation() *WidgetMutation {
	return wc.mutation
}

// Save creates the Widget in the database.
func (wc *WidgetCreate) Save(ctx context.Context) (*Widget, error) {
	wc.defaults()
	return withHooks(ctx, wc.sqlSave, wc.mutation, wc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (wc *WidgetCreate) SaveX(ctx context.Context) *Widget {
	v, err := wc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wc *WidgetCreate) Exec(ctx context.Context) error {
	_, err := wc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wc *WidgetCreate) ExecX(ctx context.Context) {
	if err := wc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wc *WidgetCreate) defaults() {
	if _, ok := wc.mutation.CreatedAt(); !ok {
		v := widget.DefaultCreatedAt()
		wc.mutation.SetCreatedAt(v)
	}
	if _, ok := wc.mutation.ID(); !ok {
		v := widget.DefaultID()
		wc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wc *WidgetCreate) check() error {
	if _, ok := wc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`basicent: missing required field "Widget.name"`)}
	}
	if _, ok := wc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`basicent: missing required field "Widget.created_at"`)}
	}
	return nil
}

func (wc *WidgetCreate) sqlSave(ctx context.Context) (*Widget, error) {
	if err := wc.check(); err != nil {
		return nil, err
	}
	_node, _spec := wc.createSpec()
	if err := sqlgraph.CreateNode(ctx, wc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	wc.mutation.id = &_node.ID
	wc.mutation.done = true
	return _node, nil
}

func (wc *WidgetCreate) createSpec() (*Widget, *sqlgraph.CreateSpec) {
	var (
		_node = &Widget{config: wc.config}
		_spec = sqlgraph.NewCreateSpec(widget.Table, sqlgraph.NewFieldSpec(widget.FieldID, field.TypeUUID))
	)
	if id, ok := wc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := wc.mutation.Name(); ok {
		_spec.SetField(widget.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := wc.mutation.Description(); ok {
		_spec.SetField(widget.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := wc.mutation.CreatedAt(); ok {
		_spec.SetField(widget.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// WidgetCreateBulk is the builder for creating many Widget entities in bulk.
type WidgetCreateBulk struct {
	config
	err      error
	builders []*WidgetCreate
}

// Save creates the Widget entities in the database.
func (wcb *WidgetCreateBulk) Save(ctx context.Context) ([]*Widget, error) {
	if wcb.err != nil {
		return nil, wcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(wcb.builders))
	nodes := make([]*Widget, len(wcb.builders))
	mutators := make([]Mutator, len(wcb.builders))
	for i := range wcb.builders {
		func(i int, root context.Context) {
			builder := wcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WidgetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, wcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, wcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, wcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (wcb *WidgetCreateBulk) SaveX(ctx context.Context) []*Widget {
	v, err := wcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wcb *WidgetCreateBulk) Exec(ctx context.Context) error {
	_, err := wcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wcb *WidgetCreateBulk) ExecX(ctx context.Context) {
	if err := wcb.Exec(ctx); err != nil {
		panic(err)
	}
}
