// Code generated by entdomain extension from schema "Widget". DO NOT EDIT.
// Source template: templates/filter.tmpl
// Regenerate with: make generate

package basicent

import (
	"entgo.io/ent/dialect/sql"
	"github.com/githonllc/entdomain/internal/fixtures/basic/basicent/predicate"
	"github.com/githonllc/entdomain/internal/fixtures/basic/basicent/widget"
	entdomain "github.com/githonllc/entdomain/runtime"
)

// ============================================================================
// Query surface for Widget — filters, free-text search and the sort
// allow-list. They are three dimensions of one list endpoint, not three
// features, so they are one artifact.
//
// Every field below carries ScopeQuery AND the marker for its dimension. A
// field with neither is absent from all three, and there is no runtime switch
// that can bring it back.
// ============================================================================

// WidgetFilter is the structured query surface for Widget.
//
// One parameter per operator per Filterable field, with the operator set taken
// from ent's own per-type table ($field.Ops) rather than from a curated
// selection: emitting an operator costs nothing here, whereas adding one later
// means changing a template, regenerating and possibly breaking a URL contract
// consumers already depend on. Substring-class operators (_contains,
// _icontains, _ieq, _suffix) additionally require AsSearchable on the field —
// see docs/adr/0005.
//
// Every parameter is a pointer or a slice, because "absent" and "the zero
// value" are different requests.
type WidgetFilter struct {
}

// Predicates converts the filter into ent predicates.
//
// The result is applied with Where(...), which combines conjunctively, so every
// parameter the caller set narrows the result further. The free-text term is
// the one disjunction: it ORs across the searchable fields and joins the rest
// as a single conjunct.
//
// A nil receiver yields no predicates, so an endpoint with no filter bound does
// not need a branch of its own.
func (f *WidgetFilter) Predicates() []predicate.Widget {
	if f == nil {
		return nil
	}
	var ps []predicate.Widget
	return ps
}

// widgetSortOptions maps an allowed sort key to ent's own order
// builder for that column. It is unexported: the mapping is reached through
// WidgetOrder, which checks the key first.
var widgetSortOptions = map[string]func(...sql.OrderTermOption) widget.OrderOption{}

// WidgetSortKeys is the sort allow-list: exactly the fields annotated
// Sortable, and nothing else.
//
// This is the load-bearing part of the query surface. An unchecked sort field
// is an injection site, an unindexed-scan trigger and — combined with paging —
// an ordering oracle over columns the caller was never meant to read. An entity
// that marks nothing is orderable by nothing, which is the safe end of the
// default rather than an oversight.
var WidgetSortKeys = []string{}

// WidgetOrder turns a list request into ent order options.
//
// The caller's string is checked against WidgetSortKeys and then thrown
// away: what reaches the query is the order builder ent generated for that
// column, looked up by an already-validated key. No caller-supplied string is
// ever interpolated into SQL.
//
// A key outside the allow-list is a validation error, not a silent fallback —
// a request to sort by a column that is out of bounds has no correct answer,
// and quietly serving a differently-ordered page is worse than refusing.
//
// There is still no default sort COLUMN. Which column to order by when the
// caller names none is a policy the schema does not contain, so generation does
// not invent one; a consumer that wants a default passes SortBy itself.
//
// Every result nevertheless ends with the primary key (ADR-0002). Offset
// pagination is only correct over a TOTAL order: LIMIT/OFFSET over a result set
// that is unordered, or ordered by a column with ties, lets rows repeat or
// vanish between pages with zero concurrent writes. The primary key is unique,
// so appending it turns any prefix order into a total one — that is the whole
// correctness argument.
//
// The primary-key term is a determinism floor, not a default sort: the response
// does not claim an ordering the caller never requested, it merely stops being
// random. The tiebreak follows the requested direction so that a descending
// walk stays descending, and it is skipped when the requested key IS the
// primary key, since ORDER BY id, id says nothing the first term did not.
func WidgetOrder(r entdomain.ListRequest) ([]widget.OrderOption, error) {
	key, desc, err := r.SortKey(WidgetSortKeys, "")
	if err != nil {
		return nil, err
	}
	dir := sql.OrderAsc()
	if desc {
		dir = sql.OrderDesc()
	}
	by, ok := widgetSortOptions[key]
	if !ok {
		return []widget.OrderOption{widget.ByID(sql.OrderAsc())}, nil
	}
	order := []widget.OrderOption{by(dir)}
	if key != "id" {
		order = append(order, widget.ByID(dir))
	}
	return order, nil
}
