// Code generated by entapi extension for this schema as a whole. DO NOT EDIT.
// Source template: templates/http.tmpl
// Regenerate with: make generate

package sensitiveent

import (
	"fmt"
	"net/http"

	entapi "github.com/githonllc/entapi/runtime"
)

// APIOption replaces one generated operation implementation.
type APIOption interface{ applyOption(*APIHandler) }

// APIHandler is the generated CRUD HTTP surface.
type APIHandler struct {
	client        *Client
	mux           *http.ServeMux
	routes        []entapi.Route
	listAccounts  ListAccountsFn
	createAccount CreateAccountFn
	getAccount    GetAccountFn
	patchAccount  PatchAccountFn
	deleteAccount DeleteAccountFn
	listSessions  ListSessionsFn
	createSession CreateSessionFn
	getSession    GetSessionFn
	patchSession  PatchSessionFn
	deleteSession DeleteSessionFn
}

// API builds the generated CRUD HTTP surface for client.
func API(client *Client) *APIHandler {
	if !ErrorMap.HasUniqueViolation() {
		if f, ok := entapi.UniqueViolation(client.driver.Dialect()); ok {
			ErrorMap = ErrorMap.WithUniqueViolation(f)
		}
	}
	h := &APIHandler{
		client:        client,
		mux:           http.NewServeMux(),
		listAccounts:  ListAccounts,
		createAccount: CreateAccount,
		getAccount:    GetAccount,
		patchAccount:  PatchAccount,
		deleteAccount: DeleteAccount,
		listSessions:  ListSessions,
		createSession: CreateSession,
		getSession:    GetSession,
		patchSession:  PatchSession,
		deleteSession: DeleteSession,
	}
	h.routes = []entapi.Route{
		{
			Method:  "GET",
			Path:    "/accounts",
			Handler: http.HandlerFunc(h.handleListAccounts),
			Entity:  "Account",
			Op:      "list",
		},
		{
			Method:  "POST",
			Path:    "/accounts",
			Handler: http.HandlerFunc(h.handleCreateAccount),
			Entity:  "Account",
			Op:      "create",
		},
		{
			Method:  "GET",
			Path:    "/accounts/{id}",
			Handler: http.HandlerFunc(h.handleGetAccount),
			Entity:  "Account",
			Op:      "get",
		},
		{
			Method:  "PATCH",
			Path:    "/accounts/{id}",
			Handler: http.HandlerFunc(h.handlePatchAccount),
			Entity:  "Account",
			Op:      "patch",
		},
		{
			Method:  "DELETE",
			Path:    "/accounts/{id}",
			Handler: http.HandlerFunc(h.handleDeleteAccount),
			Entity:  "Account",
			Op:      "delete",
		},
		{
			Method:  "GET",
			Path:    "/sessions",
			Handler: http.HandlerFunc(h.handleListSessions),
			Entity:  "Session",
			Op:      "list",
		},
		{
			Method:  "POST",
			Path:    "/sessions",
			Handler: http.HandlerFunc(h.handleCreateSession),
			Entity:  "Session",
			Op:      "create",
		},
		{
			Method:  "GET",
			Path:    "/sessions/{id}",
			Handler: http.HandlerFunc(h.handleGetSession),
			Entity:  "Session",
			Op:      "get",
		},
		{
			Method:  "PATCH",
			Path:    "/sessions/{id}",
			Handler: http.HandlerFunc(h.handlePatchSession),
			Entity:  "Session",
			Op:      "patch",
		},
		{
			Method:  "DELETE",
			Path:    "/sessions/{id}",
			Handler: http.HandlerFunc(h.handleDeleteSession),
			Entity:  "Session",
			Op:      "delete",
		},
		// The document describing everything above. It is in the manifest, not
		// beside it, so Routes() sees it and a consumer can wrap or drop it with
		// the same loop they use for the CRUD routes. It is the one route the
		// document does not describe: it is not part of the resource surface.
		{
			Method:  "GET",
			Path:    "/openapi.yaml",
			Handler: http.HandlerFunc(serveOpenAPI),
		},
	}
	for _, rt := range h.routes {
		h.mux.Handle(rt.Method+" "+rt.Path, rt.Handler)
	}
	return h
}

// With replaces generated operation implementations before serving begins.
func (h *APIHandler) With(opts ...APIOption) *APIHandler {
	for i, opt := range opts {
		if opt == nil {
			panic(fmt.Sprintf("entapi: APIOption at index %d is nil", i))
		}
		opt.applyOption(h)
	}
	return h
}

// Routes returns generated routes in deterministic registration order.
func (h *APIHandler) Routes() []entapi.Route {
	return append([]entapi.Route(nil), h.routes...)
}

// ServeHTTP serves the generated route tree.
func (h *APIHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h.mux.ServeHTTP(w, r)
}

// Mount registers every generated route on mux.
func (h *APIHandler) Mount(mux *http.ServeMux) {
	for _, rt := range h.routes {
		mux.Handle(rt.Method+" "+rt.Path, rt.Handler)
	}
}
