// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"

	"github.com/githonllc/entapi/internal/fixtures/softdelete/softdeleteent/doc"
	"github.com/githonllc/entapi/internal/fixtures/softdelete/softdeleteent/draft"
	"github.com/githonllc/entapi/internal/fixtures/softdelete/softdeleteent/ledger"
	"github.com/githonllc/entapi/internal/fixtures/softdelete/softdeleteent/note"
	"github.com/githonllc/entapi/internal/fixtures/softdelete/softdeleteent/schema"
	"github.com/google/uuid"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	doc.Policy = privacy.NewPolicies(schema.Doc{})
	doc.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := doc.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	docFields := schema.Doc{}.Fields()
	_ = docFields
	// docDescID is the schema descriptor for id field.
	docDescID := docFields[0].Descriptor()
	// doc.DefaultID holds the default value on creation for the id field.
	doc.DefaultID = docDescID.Default.(func() uuid.UUID)
	draftFields := schema.Draft{}.Fields()
	_ = draftFields
	// draftDescID is the schema descriptor for id field.
	draftDescID := draftFields[0].Descriptor()
	// draft.DefaultID holds the default value on creation for the id field.
	draft.DefaultID = draftDescID.Default.(func() uuid.UUID)
	ledgerFields := schema.Ledger{}.Fields()
	_ = ledgerFields
	// ledgerDescID is the schema descriptor for id field.
	ledgerDescID := ledgerFields[0].Descriptor()
	// ledger.DefaultID holds the default value on creation for the id field.
	ledger.DefaultID = ledgerDescID.Default.(func() uuid.UUID)
	noteFields := schema.Note{}.Fields()
	_ = noteFields
	// noteDescID is the schema descriptor for id field.
	noteDescID := noteFields[0].Descriptor()
	// note.DefaultID holds the default value on creation for the id field.
	note.DefaultID = noteDescID.Default.(func() uuid.UUID)
}
