// Code generated by entapi extension from schema "Post". DO NOT EDIT.
// Source template: templates/handler.tmpl
// Regenerate with: make generate

package edgesent

import (
	"context"
	"fmt"
	"net/http"

	"github.com/google/uuid"

	// Runtime helpers are kept distinct from identifier-type dependencies.
	entapi "github.com/githonllc/entapi/runtime"
)

// ListPostsFn is byte-identical to ListPosts.
type ListPostsFn func(context.Context, *Client, *PostFilter, entapi.ListRequest) (*entapi.Page[PostResponse], error)

func (f ListPostsFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: ListPostsFn is nil")
	}
	h.listPosts = f
}

func (h *APIHandler) handleListPosts(w http.ResponseWriter, r *http.Request) {
	filter, request, err := ParsePostQuery(r.URL.Query())
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}

	response, err := h.listPosts(r.Context(), h.client, filter, request)
	if err != nil {
		status := entapi.Status(err, http.StatusBadRequest)
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	_ = entapi.WriteJSON(w, http.StatusOK, response)
}

// CreatePostFn is byte-identical to CreatePost.
type CreatePostFn func(context.Context, *Client, *ValidPostCreateRequest) (*PostResponse, error)

func (f CreatePostFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: CreatePostFn is nil")
	}
	h.createPost = f
}

func (h *APIHandler) handleCreatePost(w http.ResponseWriter, r *http.Request) {
	var request PostCreateRequest
	if err := entapi.BindJSON(w, r, postCreateRequestTags, &request); err != nil {
		status := entapi.Status(err, http.StatusBadRequest)
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}
	validated, err := request.Validate()
	if err != nil {
		entapi.WriteProblem(w, http.StatusUnprocessableEntity, http.StatusText(http.StatusUnprocessableEntity), err)
		return
	}

	response, err := h.createPost(r.Context(), h.client, validated)
	if err != nil {
		status := entapi.Status(err, http.StatusUnprocessableEntity)
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	_ = entapi.WriteJSON(w, http.StatusCreated, response)
}

// GetPostFn is byte-identical to GetPost.
type GetPostFn func(context.Context, *Client, uuid.UUID) (*PostResponse, error)

func (f GetPostFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: GetPostFn is nil")
	}
	h.getPost = f
}

func (h *APIHandler) handleGetPost(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(r.PathValue("id"))
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}

	response, err := h.getPost(r.Context(), h.client, id)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(err):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(err):
			status = http.StatusConflict
		}
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	_ = entapi.WriteJSON(w, http.StatusOK, response)
}

// PatchPostFn is byte-identical to PatchPost.
type PatchPostFn func(context.Context, *Client, uuid.UUID, *ValidPostPatchRequest) (*PostResponse, error)

func (f PatchPostFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: PatchPostFn is nil")
	}
	h.patchPost = f
}

func (h *APIHandler) handlePatchPost(w http.ResponseWriter, r *http.Request) {
	var request PostPatchRequest
	if err := entapi.BindJSON(w, r, postPatchRequestTags, &request); err != nil {
		status := entapi.Status(err, http.StatusBadRequest)
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}
	validated, err := request.Validate()
	if err != nil {
		entapi.WriteProblem(w, http.StatusUnprocessableEntity, http.StatusText(http.StatusUnprocessableEntity), err)
		return
	}
	id, err := uuid.Parse(r.PathValue("id"))
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}

	response, err := h.patchPost(r.Context(), h.client, id, validated)
	if err != nil {
		status := entapi.Status(err, http.StatusUnprocessableEntity)
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	_ = entapi.WriteJSON(w, http.StatusOK, response)
}

// DeletePostFn is byte-identical to DeletePost.
type DeletePostFn func(context.Context, *Client, uuid.UUID) error

func (f DeletePostFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: DeletePostFn is nil")
	}
	h.deletePost = f
}

func (h *APIHandler) handleDeletePost(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(r.PathValue("id"))
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}

	deleteErr := h.deletePost(r.Context(), h.client, id)
	if deleteErr != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(deleteErr):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(deleteErr):
			status = http.StatusConflict
		}
		entapi.WriteProblem(w, status, http.StatusText(status), deleteErr)
		return
	}

	w.WriteHeader(http.StatusNoContent)
}
