// Code generated by entapi extension from schema "Post". DO NOT EDIT.
// Source template: templates/handler.tmpl
// Regenerate with: make generate

package edgesent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime"
	"net/http"

	"github.com/google/uuid"

	// Runtime helpers are kept distinct from identifier-type dependencies.
	entapi "github.com/githonllc/entapi/runtime"
)

// ListPostsFn is byte-identical to ListPosts.
type ListPostsFn func(context.Context, *Client, *PostFilter, entapi.ListRequest) (*entapi.Page[PostResponse], error)

func (f ListPostsFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: ListPostsFn is nil")
	}
	h.listPosts = f
}

func (h *APIHandler) handleListPosts(w http.ResponseWriter, r *http.Request) {
	filter, request, err := ParsePostQuery(r.URL.Query())
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}

	response, err := h.listPosts(r.Context(), h.client, filter, request)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(err):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(err):
			status = http.StatusConflict
		case entapi.IsValidation(err):
			status = http.StatusBadRequest
		}
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	body, err := json.Marshal(response)
	if err != nil {
		entapi.WriteProblem(w, http.StatusInternalServerError, http.StatusText(http.StatusInternalServerError), err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(append(body, '\n'))
}

// CreatePostFn is byte-identical to CreatePost.
type CreatePostFn func(context.Context, *Client, *ValidPostCreateRequest) (*PostResponse, error)

func (f CreatePostFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: CreatePostFn is nil")
	}
	h.createPost = f
}

func (h *APIHandler) handleCreatePost(w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
	mediaType, _, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
	if err != nil || mediaType != "application/json" {
		entapi.WriteProblem(w, http.StatusUnsupportedMediaType, http.StatusText(http.StatusUnsupportedMediaType),
			errors.New("content type must be application/json"))
		return
	}
	body, err := io.ReadAll(r.Body)
	if err != nil {
		var maxBytesErr *http.MaxBytesError
		if errors.As(err, &maxBytesErr) {
			entapi.WriteProblem(w, http.StatusRequestEntityTooLarge, http.StatusText(http.StatusRequestEntityTooLarge), err)
			return
		}
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(body, &raw); err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	unknownField := ""
	for key := range raw {
		known := false
		for _, tag := range postCreateRequestTags {
			if key == tag {
				known = true
				break
			}
		}
		if !known && (unknownField == "" || key < unknownField) {
			unknownField = key
		}
	}
	if unknownField != "" {
		err := &entapi.FieldError{
			Field: unknownField,
			Err:   fmt.Errorf("%w: unknown field %q", entapi.ErrValidation, unknownField),
		}
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	var request PostCreateRequest
	if err := json.Unmarshal(body, &request); err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	validated, err := request.Validate()
	if err != nil {
		entapi.WriteProblem(w, http.StatusUnprocessableEntity, http.StatusText(http.StatusUnprocessableEntity), err)
		return
	}

	response, err := h.createPost(r.Context(), h.client, validated)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(err):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(err):
			status = http.StatusConflict
		case entapi.IsValidation(err):
			status = http.StatusUnprocessableEntity
		}
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	body, err = json.Marshal(response)
	if err != nil {
		entapi.WriteProblem(w, http.StatusInternalServerError, http.StatusText(http.StatusInternalServerError), err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(append(body, '\n'))
}

// GetPostFn is byte-identical to GetPost.
type GetPostFn func(context.Context, *Client, uuid.UUID) (*PostResponse, error)

func (f GetPostFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: GetPostFn is nil")
	}
	h.getPost = f
}

func (h *APIHandler) handleGetPost(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(r.PathValue("id"))
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}

	response, err := h.getPost(r.Context(), h.client, id)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(err):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(err):
			status = http.StatusConflict
		}
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	body, err := json.Marshal(response)
	if err != nil {
		entapi.WriteProblem(w, http.StatusInternalServerError, http.StatusText(http.StatusInternalServerError), err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(append(body, '\n'))
}

// PatchPostFn is byte-identical to PatchPost.
type PatchPostFn func(context.Context, *Client, uuid.UUID, *ValidPostPatchRequest) (*PostResponse, error)

func (f PatchPostFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: PatchPostFn is nil")
	}
	h.patchPost = f
}

func (h *APIHandler) handlePatchPost(w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
	mediaType, _, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
	if err != nil || mediaType != "application/json" {
		entapi.WriteProblem(w, http.StatusUnsupportedMediaType, http.StatusText(http.StatusUnsupportedMediaType),
			errors.New("content type must be application/json"))
		return
	}
	body, err := io.ReadAll(r.Body)
	if err != nil {
		var maxBytesErr *http.MaxBytesError
		if errors.As(err, &maxBytesErr) {
			entapi.WriteProblem(w, http.StatusRequestEntityTooLarge, http.StatusText(http.StatusRequestEntityTooLarge), err)
			return
		}
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(body, &raw); err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	unknownField := ""
	for key := range raw {
		known := false
		for _, tag := range postPatchRequestTags {
			if key == tag {
				known = true
				break
			}
		}
		if !known && (unknownField == "" || key < unknownField) {
			unknownField = key
		}
	}
	if unknownField != "" {
		err := &entapi.FieldError{
			Field: unknownField,
			Err:   fmt.Errorf("%w: unknown field %q", entapi.ErrValidation, unknownField),
		}
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	var request PostPatchRequest
	if err := json.Unmarshal(body, &request); err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	validated, err := request.Validate()
	if err != nil {
		entapi.WriteProblem(w, http.StatusUnprocessableEntity, http.StatusText(http.StatusUnprocessableEntity), err)
		return
	}
	id, err := uuid.Parse(r.PathValue("id"))
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}

	response, err := h.patchPost(r.Context(), h.client, id, validated)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(err):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(err):
			status = http.StatusConflict
		case entapi.IsValidation(err):
			status = http.StatusUnprocessableEntity
		}
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	body, err = json.Marshal(response)
	if err != nil {
		entapi.WriteProblem(w, http.StatusInternalServerError, http.StatusText(http.StatusInternalServerError), err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(append(body, '\n'))
}

// DeletePostFn is byte-identical to DeletePost.
type DeletePostFn func(context.Context, *Client, uuid.UUID) error

func (f DeletePostFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: DeletePostFn is nil")
	}
	h.deletePost = f
}

func (h *APIHandler) handleDeletePost(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(r.PathValue("id"))
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}

	deleteErr := h.deletePost(r.Context(), h.client, id)
	if deleteErr != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(deleteErr):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(deleteErr):
			status = http.StatusConflict
		}
		entapi.WriteProblem(w, status, http.StatusText(status), deleteErr)
		return
	}

	w.WriteHeader(http.StatusNoContent)
}
