// Code generated by entapi extension from schema "Author". DO NOT EDIT.
// Source template: templates/handler.tmpl
// Regenerate with: make generate

package wiringent

import (
	"context"
	"fmt"
	"net/http"

	"github.com/google/uuid"

	// Runtime helpers are kept distinct from identifier-type dependencies.
	entapi "github.com/githonllc/entapi/runtime"
)

// ListAuthorsFn is byte-identical to ListAuthors.
type ListAuthorsFn func(context.Context, *Client, *AuthorFilter, entapi.ListRequest) (*entapi.Page[AuthorResponse], error)

func (f ListAuthorsFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: ListAuthorsFn is nil")
	}
	h.listAuthors = f
}

func (h *APIHandler) handleListAuthors(w http.ResponseWriter, r *http.Request) {
	filter, request, err := ParseAuthorQuery(r.URL.Query())
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}

	response, err := h.listAuthors(r.Context(), h.client, filter, request)
	if err != nil {
		status := entapi.Status(err, http.StatusBadRequest)
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	_ = entapi.WriteJSON(w, http.StatusOK, response)
}

// CreateAuthorFn is byte-identical to CreateAuthor.
type CreateAuthorFn func(context.Context, *Client, *ValidAuthorCreateRequest) (*AuthorResponse, error)

func (f CreateAuthorFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: CreateAuthorFn is nil")
	}
	h.createAuthor = f
}

func (h *APIHandler) handleCreateAuthor(w http.ResponseWriter, r *http.Request) {
	var request AuthorCreateRequest
	if err := entapi.BindJSON(w, r, authorCreateRequestTags, &request); err != nil {
		status := entapi.Status(err, http.StatusBadRequest)
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}
	validated, err := request.Validate()
	if err != nil {
		entapi.WriteProblem(w, http.StatusUnprocessableEntity, http.StatusText(http.StatusUnprocessableEntity), err)
		return
	}

	response, err := h.createAuthor(r.Context(), h.client, validated)
	if err != nil {
		status := entapi.Status(err, http.StatusUnprocessableEntity)
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	_ = entapi.WriteJSON(w, http.StatusCreated, response)
}

// GetAuthorFn is byte-identical to GetAuthor.
type GetAuthorFn func(context.Context, *Client, uuid.UUID) (*AuthorResponse, error)

func (f GetAuthorFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: GetAuthorFn is nil")
	}
	h.getAuthor = f
}

func (h *APIHandler) handleGetAuthor(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(r.PathValue("id"))
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}

	response, err := h.getAuthor(r.Context(), h.client, id)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(err):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(err):
			status = http.StatusConflict
		}
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	_ = entapi.WriteJSON(w, http.StatusOK, response)
}

// PatchAuthorFn is byte-identical to PatchAuthor.
type PatchAuthorFn func(context.Context, *Client, uuid.UUID, *ValidAuthorPatchRequest) (*AuthorResponse, error)

func (f PatchAuthorFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: PatchAuthorFn is nil")
	}
	h.patchAuthor = f
}

func (h *APIHandler) handlePatchAuthor(w http.ResponseWriter, r *http.Request) {
	var request AuthorPatchRequest
	if err := entapi.BindJSON(w, r, authorPatchRequestTags, &request); err != nil {
		status := entapi.Status(err, http.StatusBadRequest)
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}
	validated, err := request.Validate()
	if err != nil {
		entapi.WriteProblem(w, http.StatusUnprocessableEntity, http.StatusText(http.StatusUnprocessableEntity), err)
		return
	}
	id, err := uuid.Parse(r.PathValue("id"))
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}

	response, err := h.patchAuthor(r.Context(), h.client, id, validated)
	if err != nil {
		status := entapi.Status(err, http.StatusUnprocessableEntity)
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	_ = entapi.WriteJSON(w, http.StatusOK, response)
}

// DeleteAuthorFn is byte-identical to DeleteAuthor.
type DeleteAuthorFn func(context.Context, *Client, uuid.UUID) error

func (f DeleteAuthorFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: DeleteAuthorFn is nil")
	}
	h.deleteAuthor = f
}

func (h *APIHandler) handleDeleteAuthor(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(r.PathValue("id"))
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}

	deleteErr := h.deleteAuthor(r.Context(), h.client, id)
	if deleteErr != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(deleteErr):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(deleteErr):
			status = http.StatusConflict
		}
		entapi.WriteProblem(w, status, http.StatusText(status), deleteErr)
		return
	}

	w.WriteHeader(http.StatusNoContent)
}
