// Code generated by entapi extension for this schema as a whole. DO NOT EDIT.
// Source template: templates/http.tmpl
// Regenerate with: make generate

package wiringent

import (
	"fmt"
	"net/http"

	entapi "github.com/githonllc/entapi/runtime"
)

// APIOption replaces one generated operation implementation.
type APIOption interface{ applyOption(*APIHandler) }

// APIHandler is the generated CRUD HTTP surface.
type APIHandler struct {
	client          *Client
	mux             *http.ServeMux
	routes          []entapi.Route
	listArticles    ListArticlesFn
	createArticle   CreateArticleFn
	getArticle      GetArticleFn
	patchArticle    PatchArticleFn
	listAuthors     ListAuthorsFn
	createAuthor    CreateAuthorFn
	getAuthor       GetAuthorFn
	patchAuthor     PatchAuthorFn
	deleteAuthor    DeleteAuthorFn
	listNotes       ListNotesFn
	createNote      CreateNoteFn
	getNote         GetNoteFn
	patchNote       PatchNoteFn
	deleteNote      DeleteNoteFn
	listPatchlesses ListPatchlessesFn
	createPatchless CreatePatchlessFn
	getPatchless    GetPatchlessFn
	deletePatchless DeletePatchlessFn
}

// API builds the generated CRUD HTTP surface for client.
func API(client *Client) *APIHandler {
	if !ErrorMap.HasUniqueViolation() {
		if f, ok := entapi.UniqueViolation(client.driver.Dialect()); ok {
			ErrorMap = ErrorMap.WithUniqueViolation(f)
		}
	}
	h := &APIHandler{
		client:          client,
		mux:             http.NewServeMux(),
		listArticles:    ListArticles,
		createArticle:   CreateArticle,
		getArticle:      GetArticle,
		patchArticle:    PatchArticle,
		listAuthors:     ListAuthors,
		createAuthor:    CreateAuthor,
		getAuthor:       GetAuthor,
		patchAuthor:     PatchAuthor,
		deleteAuthor:    DeleteAuthor,
		listNotes:       ListNotes,
		createNote:      CreateNote,
		getNote:         GetNote,
		patchNote:       PatchNote,
		deleteNote:      DeleteNote,
		listPatchlesses: ListPatchlesses,
		createPatchless: CreatePatchless,
		getPatchless:    GetPatchless,
		deletePatchless: DeletePatchless,
	}
	h.routes = []entapi.Route{
		{
			Method:  "GET",
			Path:    "/articles",
			Handler: http.HandlerFunc(h.handleListArticles),
			Entity:  "Article",
			Op:      "list",
		},
		{
			Method:  "POST",
			Path:    "/articles",
			Handler: http.HandlerFunc(h.handleCreateArticle),
			Entity:  "Article",
			Op:      "create",
		},
		{
			Method:  "GET",
			Path:    "/articles/{id}",
			Handler: http.HandlerFunc(h.handleGetArticle),
			Entity:  "Article",
			Op:      "get",
		},
		{
			Method:  "PATCH",
			Path:    "/articles/{id}",
			Handler: http.HandlerFunc(h.handlePatchArticle),
			Entity:  "Article",
			Op:      "patch",
		},
		{
			Method:  "GET",
			Path:    "/authors",
			Handler: http.HandlerFunc(h.handleListAuthors),
			Entity:  "Author",
			Op:      "list",
		},
		{
			Method:  "POST",
			Path:    "/authors",
			Handler: http.HandlerFunc(h.handleCreateAuthor),
			Entity:  "Author",
			Op:      "create",
		},
		{
			Method:  "GET",
			Path:    "/authors/{id}",
			Handler: http.HandlerFunc(h.handleGetAuthor),
			Entity:  "Author",
			Op:      "get",
		},
		{
			Method:  "PATCH",
			Path:    "/authors/{id}",
			Handler: http.HandlerFunc(h.handlePatchAuthor),
			Entity:  "Author",
			Op:      "patch",
		},
		{
			Method:  "DELETE",
			Path:    "/authors/{id}",
			Handler: http.HandlerFunc(h.handleDeleteAuthor),
			Entity:  "Author",
			Op:      "delete",
		},
		{
			Method:  "GET",
			Path:    "/notes",
			Handler: http.HandlerFunc(h.handleListNotes),
			Entity:  "Note",
			Op:      "list",
		},
		{
			Method:  "POST",
			Path:    "/notes",
			Handler: http.HandlerFunc(h.handleCreateNote),
			Entity:  "Note",
			Op:      "create",
		},
		{
			Method:  "GET",
			Path:    "/notes/{id}",
			Handler: http.HandlerFunc(h.handleGetNote),
			Entity:  "Note",
			Op:      "get",
		},
		{
			Method:  "PATCH",
			Path:    "/notes/{id}",
			Handler: http.HandlerFunc(h.handlePatchNote),
			Entity:  "Note",
			Op:      "patch",
		},
		{
			Method:  "DELETE",
			Path:    "/notes/{id}",
			Handler: http.HandlerFunc(h.handleDeleteNote),
			Entity:  "Note",
			Op:      "delete",
		},
		{
			Method:  "GET",
			Path:    "/patchlesses",
			Handler: http.HandlerFunc(h.handleListPatchlesses),
			Entity:  "Patchless",
			Op:      "list",
		},
		{
			Method:  "POST",
			Path:    "/patchlesses",
			Handler: http.HandlerFunc(h.handleCreatePatchless),
			Entity:  "Patchless",
			Op:      "create",
		},
		{
			Method:  "GET",
			Path:    "/patchlesses/{id}",
			Handler: http.HandlerFunc(h.handleGetPatchless),
			Entity:  "Patchless",
			Op:      "get",
		},
		{
			Method:  "DELETE",
			Path:    "/patchlesses/{id}",
			Handler: http.HandlerFunc(h.handleDeletePatchless),
			Entity:  "Patchless",
			Op:      "delete",
		},
		// The document describing everything above. It is in the manifest, not
		// beside it, so Routes() sees it and a consumer can wrap or drop it with
		// the same loop they use for the CRUD routes. It is the one route the
		// document does not describe: it is not part of the resource surface.
		{
			Method:  "GET",
			Path:    "/openapi.yaml",
			Handler: http.HandlerFunc(serveOpenAPI),
		},
	}
	for _, rt := range h.routes {
		h.mux.Handle(rt.Method+" "+rt.Path, rt.Handler)
	}
	return h
}

// With replaces generated operation implementations before serving begins.
func (h *APIHandler) With(opts ...APIOption) *APIHandler {
	for i, opt := range opts {
		if opt == nil {
			panic(fmt.Sprintf("entapi: APIOption at index %d is nil", i))
		}
		opt.applyOption(h)
	}
	return h
}

// Routes returns generated routes in deterministic registration order.
func (h *APIHandler) Routes() []entapi.Route {
	return append([]entapi.Route(nil), h.routes...)
}

// ServeHTTP serves the generated route tree.
func (h *APIHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h.mux.ServeHTTP(w, r)
}

// Mount registers every generated route on mux.
func (h *APIHandler) Mount(mux *http.ServeMux) {
	for _, rt := range h.routes {
		mux.Handle(rt.Method+" "+rt.Path, rt.Handler)
	}
}
