// Code generated by entdomain extension from schema "Node". DO NOT EDIT.
// Source template: templates/filter.tmpl
// Regenerate with: make generate

package ent

import (
	"entgo.io/ent/dialect/sql"
	entdomain "github.com/githonllc/entdomain"
	"github.com/githonllc/entdomain/internal/fixtures/selfrefpartial/ent/node"
	"github.com/githonllc/entdomain/internal/fixtures/selfrefpartial/ent/predicate"
)

// ============================================================================
// Query surface for Node — filters, free-text search and the sort
// allow-list. They are three dimensions of one list endpoint, not three
// features, so they are one artifact.
//
// Every field below carries ScopeQuery AND the marker for its dimension. A
// field with neither is absent from all three, and there is no runtime switch
// that can bring it back.
// ============================================================================

// NodeFilter is the structured query surface for Node.
//
// One parameter per operator per Filterable field, with the operator set taken
// from ent's own per-type table ($field.Ops) rather than from a curated
// selection: emitting an operator costs nothing here, whereas adding one later
// means changing a template, regenerating and possibly breaking a URL contract
// consumers already depend on.
//
// Every parameter is a pointer or a slice, because "absent" and "the zero
// value" are different requests.
type NodeFilter struct {
}

// Predicates converts the filter into ent predicates.
//
// The result is applied with Where(...), which combines conjunctively, so every
// parameter the caller set narrows the result further. The free-text term is
// the one disjunction: it ORs across the searchable fields and joins the rest
// as a single conjunct.
//
// A nil receiver yields no predicates, so an endpoint with no filter bound does
// not need a branch of its own.
func (f *NodeFilter) Predicates() []predicate.Node {
	if f == nil {
		return nil
	}
	var ps []predicate.Node
	return ps
}

// nodeSortOptions maps an allowed sort key to ent's own order
// builder for that column. It is unexported: the mapping is reached through
// NodeOrder, which checks the key first.
var nodeSortOptions = map[string]func(...sql.OrderTermOption) node.OrderOption{}

// NodeSortKeys is the sort allow-list: exactly the fields annotated
// Sortable, and nothing else.
//
// This is the load-bearing part of the query surface. An unchecked sort field
// is an injection site, an unindexed-scan trigger and — combined with paging —
// an ordering oracle over columns the caller was never meant to read. An entity
// that marks nothing is orderable by nothing, which is the safe end of the
// default rather than an oversight.
var NodeSortKeys = []string{}

// NodeOrder turns a list request into ent order options.
//
// The caller's string is checked against NodeSortKeys and then thrown
// away: what reaches the query is the order builder ent generated for that
// column, looked up by an already-validated key. No caller-supplied string is
// ever interpolated into SQL.
//
// A key outside the allow-list is a validation error, not a silent fallback —
// a request to sort by a column that is out of bounds has no correct answer,
// and quietly serving a differently-ordered page is worse than refusing.
//
// There is no default sort key. Which column to order by when the caller names
// none is a policy the schema does not contain, so generation does not invent
// one; a consumer that wants a default passes SortBy itself.
func NodeOrder(r entdomain.ListRequest) ([]node.OrderOption, error) {
	key, desc, err := r.SortKey(NodeSortKeys, "")
	if err != nil {
		return nil, err
	}
	by, ok := nodeSortOptions[key]
	if !ok {
		// Only reachable when no sort was requested and no default applies.
		return nil, nil
	}
	if desc {
		return []node.OrderOption{by(sql.OrderDesc())}, nil
	}
	return []node.OrderOption{by(sql.OrderAsc())}, nil
}
