package e2e

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/pb33f/libopenapi"
	"github.com/pb33f/libopenapi-validator/schema_validation"
	v3 "github.com/pb33f/libopenapi/datamodel/high/v3"
	"github.com/pb33f/libopenapi/orderedmap"

	ent "github.com/githonllc/entapi/internal/fixtures/httpdemo/httpdemoent"
)

// This file is the behavioural half of #76. A compile proof cannot answer any
// of its questions: whether the served bytes are the file on disk, whether the
// document parses as OpenAPI 3.1 at all, or — the one that matters most —
// whether what it SAYS is what the generated code DOES.
//
// The last one is three separate assertions, and the document is only
// trustworthy with all three: the schemas match the generated structs by
// reflection, the paths match the live route manifest, and the operator
// prefixes match what the live parser accepts. Any one of them alone proves
// only that the file parses.

// documentPath is the generated document as it sits in the repository. Reading
// it here rather than trusting the embed is the whole point of the byte
// comparison below.
const documentPath = "../httpdemoent/openapi.yaml"

// openapiRoute is the one route the document deliberately does not describe.
// It is not part of the resource surface, and describing it would make the
// document a description of itself.
const openapiRoute = "/openapi.yaml"

func onDisk(t *testing.T) []byte {
	t.Helper()
	content, err := os.ReadFile(documentPath)
	if err != nil {
		t.Fatalf("reading the generated document: %v", err)
	}
	return content
}

// loadDocument parses the committed document and returns the built v3 model.
func loadDocument(t *testing.T) (libopenapi.Document, *v3.Document) {
	t.Helper()
	doc, err := libopenapi.NewDocument(onDisk(t))
	if err != nil {
		t.Fatalf("the generated document is not a parseable OpenAPI specification: %v", err)
	}
	model, err := doc.BuildV3Model()
	if err != nil {
		t.Fatalf("the generated document does not build as an OpenAPI 3 model: %v", err)
	}
	return doc, &model.Model
}

// TestOpenAPIServedBytesAreTheFileOnDisk is the anti-drift criterion. The
// handler writes an embedded copy, so the only way the two can disagree is if
// the file changed without a regeneration — which is exactly the state the
// embed exists to make impossible.
func TestOpenAPIServedBytesAreTheFileOnDisk(t *testing.T) {
	server := newTestServer(t, ent.API(newClient(t)))
	t.Cleanup(server.Close)

	response, body := request(t, server.Client(), http.MethodGet, server.URL+openapiRoute, "", nil)
	requireStatus(t, response, body, http.StatusOK)
	if got := response.Header.Get("Content-Type"); got != "application/yaml" {
		t.Errorf("Content-Type = %q, want application/yaml (RFC 9512)", got)
	}
	disk := onDisk(t)
	if string(body) != string(disk) {
		t.Fatalf("the served document is not the file on disk: served %d bytes, disk holds %d", len(body), len(disk))
	}
	if !strings.HasPrefix(string(disk), "# Code generated by entapi extension") {
		t.Error("the document's first line is not the ownership marker in comment form")
	}
}

// TestOpenAPIDocumentValidatesAgainstThe31MetaSchema is the criterion that
// needs a real validator, which is why it lives in this module: the root module
// must stay free of a YAML parser, so nothing there can answer it.
func TestOpenAPIDocumentValidatesAgainstThe31MetaSchema(t *testing.T) {
	doc, model := loadDocument(t)

	if model.Version != "3.1.0" {
		t.Errorf("openapi = %q, want 3.1.0", model.Version)
	}
	if len(model.Servers) != 0 {
		t.Errorf("the document declares %d servers; the mount prefix is a deployment fact", len(model.Servers))
	}
	if model.Info == nil || model.Info.Title == "" || model.Info.Version == "" {
		t.Fatalf("info = %+v, want a title and a version", model.Info)
	}

	valid, errs := schema_validation.ValidateOpenAPIDocument(doc)
	if !valid {
		for _, err := range errs {
			t.Errorf("OpenAPI 3.1 validation: %s — %s", err.Message, err.Reason)
		}
		t.Fatal("the generated document does not validate as OpenAPI 3.1")
	}
}

// TestEveryGeneratedDocumentValidatesAs31 widens the criterion above from this
// fixture to every one in the repository, and it is not redundant with it.
//
// httpdemo has no edges and no enum, so the template lines that render an
// expanded edge (a "oneOf" over a $ref and a "null") and an enum's value list
// are exercised only by the edges and fieldshapes fixtures — whose documents
// nothing else ever hands to a YAML parser, because the codegen harness only
// compiles Go and the root module's assertions are substring checks. A syntax
// bug on one of those lines would reach disk, be committed, and pass every
// other gate. This is the one place it cannot.
func TestEveryGeneratedDocumentValidatesAs31(t *testing.T) {
	documents, err := filepath.Glob("../../*/*ent/openapi.yaml")
	if err != nil {
		t.Fatalf("globbing generated documents: %v", err)
	}
	// More than one, or the widening above bought nothing and this test would
	// be TestOpenAPIDocumentValidatesAgainstThe31MetaSchema under a longer name.
	if len(documents) < 2 {
		t.Fatalf("found %d generated documents under internal/fixtures; this test would pass vacuously", len(documents))
	}
	for _, path := range documents {
		t.Run(path, func(t *testing.T) {
			content, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("reading %s: %v", path, err)
			}
			doc, err := libopenapi.NewDocument(content)
			if err != nil {
				t.Fatalf("%s is not a parseable OpenAPI specification: %v", path, err)
			}
			if _, err := doc.BuildV3Model(); err != nil {
				t.Fatalf("%s does not build as an OpenAPI 3 model: %v", path, err)
			}
			valid, errs := schema_validation.ValidateOpenAPIDocument(doc)
			if !valid {
				for _, verr := range errs {
					t.Errorf("%s: %s — %s", path, verr.Message, verr.Reason)
				}
				t.Fatalf("%s does not validate as OpenAPI 3.1", path)
			}
		})
	}
}

// TestOpenAPIPathsMatchTheLiveRouteTree is the first of the three "says what it
// does" assertions. It compares sets rather than probing, because a probe can
// only find a documented path that 404s — it cannot find a live route the
// document forgot.
func TestOpenAPIPathsMatchTheLiveRouteTree(t *testing.T) {
	_, model := loadDocument(t)

	documented := map[string]bool{}
	for pair := range orderedmap.Iterate(context.Background(), model.Paths.PathItems) {
		for op := range orderedmap.Iterate(context.Background(), pair.Value().GetOperations()) {
			documented[strings.ToUpper(op.Key())+" "+pair.Key()] = true
		}
	}
	// The document does not describe itself (see openapiRoute), so it is the
	// one exemption — spelled out here rather than left as a set difference
	// nobody reads.
	documented[http.MethodGet+" "+openapiRoute] = true

	live := map[string]bool{}
	for _, route := range ent.API(newClient(t)).Routes() {
		live[route.Method+" "+route.Path] = true
	}

	for _, key := range sortedKeys(documented) {
		if !live[key] {
			t.Errorf("the document describes %s, which the route manifest does not serve", key)
		}
	}
	for _, key := range sortedKeys(live) {
		if !documented[key] {
			t.Errorf("the route manifest serves %s, which the document does not describe", key)
		}
	}

	// The set comparison above cannot see a route whose handler is not actually
	// reachable through the mux, so probe every documented path once and reject
	// the stdlib router's own text/plain residue.
	server := newTestServer(t, ent.API(newClient(t)))
	t.Cleanup(server.Close)
	const missingID = "00000000-0000-0000-0000-000000000001"
	for _, key := range sortedKeys(documented) {
		method, path, _ := strings.Cut(key, " ")
		var body *strings.Reader
		contentType := ""
		if method == http.MethodPost || method == http.MethodPatch {
			body = strings.NewReader(`{}`)
			contentType = "application/json"
		}
		url := server.URL + strings.ReplaceAll(path, "{id}", missingID)
		var response *http.Response
		var raw []byte
		if body == nil {
			response, raw = request(t, server.Client(), method, url, contentType, nil)
		} else {
			response, raw = request(t, server.Client(), method, url, contentType, body)
		}
		residue := response.StatusCode == http.StatusNotFound || response.StatusCode == http.StatusMethodNotAllowed
		if residue && strings.HasPrefix(response.Header.Get("Content-Type"), "text/plain") {
			t.Errorf("%s reached the stdlib router's residue rather than a generated handler: %d %s",
				key, response.StatusCode, raw)
		}
	}
}

// TestOpenAPISchemasMatchTheGeneratedStructs is the second. A path set that
// agrees says nothing about what crosses the wire; this walks the generated Go
// structs by reflection and requires the documented property names to be
// exactly their JSON keys.
func TestOpenAPISchemasMatchTheGeneratedStructs(t *testing.T) {
	_, model := loadDocument(t)

	cases := []struct {
		schema string
		value  any
	}{
		{"ArticleResponse", ent.ArticleResponse{}},
		{"ArticleSummary", ent.ArticleSummary{}},
		{"ArticleCreateRequest", ent.ArticleCreateRequest{}},
		{"ArticlePatchRequest", ent.ArticlePatchRequest{}},
		{"ArticleListResponse", ent.ArticleListResponse{}},
		{"AuditLogResponse", ent.AuditLogResponse{}},
		{"AuditLogSummary", ent.AuditLogSummary{}},
		{"AuditLogCreateRequest", ent.AuditLogCreateRequest{}},
		{"AuditLogPatchRequest", ent.AuditLogPatchRequest{}},
		{"AuditLogListResponse", ent.AuditLogListResponse{}},
	}
	for _, tc := range cases {
		t.Run(tc.schema, func(t *testing.T) {
			documented := schemaProperties(t, model, tc.schema)
			actual := jsonKeys(t, tc.value)
			if !reflect.DeepEqual(documented, actual) {
				t.Errorf("%s documents %v, the generated struct carries %v", tc.schema, documented, actual)
			}
		})
	}
}

// TestOpenAPISensitiveFieldIsScopedToRequests states the rule in both
// directions on purpose. "Absent everywhere" would be the wrong claim: an
// ent Sensitive field is still settable, so silence about the request schemas
// would document an API the generated code does not offer.
func TestOpenAPISensitiveFieldIsScopedToRequests(t *testing.T) {
	_, model := loadDocument(t)

	const sensitive = "internal_note"
	for _, name := range []string{"ArticleResponse", "ArticleSummary"} {
		if contains(schemaProperties(t, model, name), sensitive) {
			t.Errorf("%s documents the Sensitive field %q", name, sensitive)
		}
	}
	for _, name := range []string{"ArticleCreateRequest", "ArticlePatchRequest"} {
		if !contains(schemaProperties(t, model, name), sensitive) {
			t.Errorf("%s omits %q, which the generated request struct accepts", name, sensitive)
		}
	}
}

// TestOpenAPIFilterOperatorsMatchTheLiveParser is the third, and the one that
// keeps this file honest about #83: it never asserts that a particular prefix
// is or is not present. It reads whatever the document lists for a field and
// requires the live parser to agree — accept every listed prefix, reject every
// prefix the document lists for some OTHER field and not for this one.
//
// Both classes are covered: title is Searchable, so it earns the substring
// operators; rank is Filterable only, so it must not.
func TestOpenAPIFilterOperatorsMatchTheLiveParser(t *testing.T) {
	_, model := loadDocument(t)

	listed := map[string][]string{}
	vocabulary := map[string]bool{}
	listPath := model.Paths.PathItems.GetOrZero("/articles")
	if listPath == nil || listPath.Get == nil {
		t.Fatal("the document has no GET /articles operation to read filter parameters from")
	}
	for _, param := range listPath.Get.Parameters {
		if strings.HasPrefix(param.Name, "_") || param.Schema == nil {
			continue
		}
		prefixes := patternPrefixes(param.Schema.Schema().Pattern)
		listed[param.Name] = prefixes
		for _, prefix := range prefixes {
			vocabulary[prefix] = true
		}
	}
	if len(vocabulary) == 0 {
		t.Fatal("no filter parameter carries an operator pattern; this test would pass vacuously")
	}

	server := newTestServer(t, ent.API(newClient(t)))
	t.Cleanup(server.Close)

	samples := map[string]string{"title": "abc", "rank": "7"}
	for _, name := range []string{"title", "rank"} {
		prefixes, ok := listed[name]
		if !ok {
			t.Fatalf("the document has no %q filter parameter", name)
		}
		allowed := map[string]bool{}
		for _, prefix := range prefixes {
			allowed[prefix] = true
		}
		for _, prefix := range prefixes {
			t.Run(name+"/"+prefix+"/accepted", func(t *testing.T) {
				response, body := request(t, server.Client(), http.MethodGet,
					fmt.Sprintf("%s/articles?%s=%s", server.URL, name, operatorValue(prefix, samples[name])), "", nil)
				requireStatus(t, response, body, http.StatusOK)
			})
		}
		for _, prefix := range sortedKeys(vocabulary) {
			if allowed[prefix] {
				continue
			}
			t.Run(name+"/"+prefix+"/rejected", func(t *testing.T) {
				response, body := request(t, server.Client(), http.MethodGet,
					fmt.Sprintf("%s/articles?%s=%s", server.URL, name, operatorValue(prefix, samples[name])), "", nil)
				requireStatus(t, response, body, http.StatusBadRequest)
			})
		}
	}
}

// patternPrefixes reads the operator alternation back out of a filter
// parameter's pattern. The document is the only input, so the test cannot
// smuggle in an expectation of its own.
var patternAlternation = regexp.MustCompile(`^\^\(\?:\(([^)]*)\):\)\?$`)

func patternPrefixes(pattern string) []string {
	match := patternAlternation.FindStringSubmatch(pattern)
	if match == nil {
		return nil
	}
	return strings.Split(match[1], "|")
}

// operatorValue builds a wire value for one operator that is well-formed for
// its arity: the null pair takes none, the list operators take a comma list.
func operatorValue(prefix, sample string) string {
	switch prefix {
	case "is_null", "not_null":
		return prefix + ":"
	case "in", "not_in", "between":
		return prefix + ":" + sample + "," + sample
	default:
		return prefix + ":" + sample
	}
}

// schemaProperties returns the documented property names of one component
// schema, sorted.
func schemaProperties(t *testing.T, model *v3.Document, name string) []string {
	t.Helper()
	if model.Components == nil || model.Components.Schemas == nil {
		t.Fatal("the document declares no component schemas")
	}
	proxy := model.Components.Schemas.GetOrZero(name)
	if proxy == nil {
		t.Fatalf("the document declares no %q schema", name)
	}
	var out []string
	for pair := range orderedmap.Iterate(context.Background(), proxy.Schema().Properties) {
		out = append(out, pair.Key())
	}
	sort.Strings(out)
	return out
}

// jsonKeys returns the JSON wire keys of a generated struct, sorted. Unexported
// fields — the presence map the request types carry — are skipped, as is any
// field tagged "-".
func jsonKeys(t *testing.T, v any) []string {
	t.Helper()
	rt := reflect.TypeOf(v)
	if rt.Kind() != reflect.Struct {
		t.Fatalf("%T is not a struct", v)
	}
	var out []string
	for i := 0; i < rt.NumField(); i++ {
		field := rt.Field(i)
		if field.PkgPath != "" {
			continue
		}
		name, _, _ := strings.Cut(field.Tag.Get("json"), ",")
		if name == "" || name == "-" {
			continue
		}
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

func contains(list []string, want string) bool {
	for _, item := range list {
		if item == want {
			return true
		}
	}
	return false
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for key := range m {
		out = append(out, key)
	}
	sort.Strings(out)
	return out
}
