// Code generated by entapi extension for this schema as a whole. DO NOT EDIT.
// Source template: templates/http.tmpl
// Regenerate with: make generate

package selfrefpartialent

import (
	"fmt"
	"net/http"

	entapi "github.com/githonllc/entapi/runtime"
)

// APIOption replaces one generated operation implementation.
type APIOption interface{ applyOption(*APIHandler) }

// APIHandler is the generated CRUD HTTP surface.
type APIHandler struct {
	client     *Client
	mux        *http.ServeMux
	endpoints  []entapi.Endpoint
	listNodes  ListNodesFn
	createNode CreateNodeFn
	getNode    GetNodeFn
	patchNode  PatchNodeFn
	deleteNode DeleteNodeFn
}

// API builds the generated CRUD HTTP surface for client.
func API(client *Client) *APIHandler {
	if !ErrorMap.HasUniqueViolation() {
		if f, ok := entapi.UniqueViolation(client.driver.Dialect()); ok {
			ErrorMap = ErrorMap.WithUniqueViolation(f)
		}
	}
	h := &APIHandler{
		client:     client,
		mux:        http.NewServeMux(),
		listNodes:  ListNodes,
		createNode: CreateNode,
		getNode:    GetNode,
		patchNode:  PatchNode,
		deleteNode: DeleteNode,
	}
	// The manifest is assembled from the per-operation accessors below, so the
	// two can never describe different endpoints: there is one construction and
	// no second table.
	h.endpoints = []entapi.Endpoint{
		h.ListNodesEndpoint(),
		h.CreateNodeEndpoint(),
		h.GetNodeEndpoint(),
		h.PatchNodeEndpoint(),
		h.DeleteNodeEndpoint(),
		// The document describing everything above. It is in the manifest, not
		// beside it, so Endpoints() sees it and a consumer can wrap or drop it
		// with the same loop they use for the CRUD endpoints. It is the one
		// endpoint the document does not describe: it is not part of the
		// resource surface.
		h.OpenAPIEndpoint(),
	}
	for _, ep := range h.endpoints {
		h.mux.Handle(ep.Method+" "+ep.Path, ep.Handler)
	}
	return h
}

// With replaces generated operation implementations before serving begins.
func (h *APIHandler) With(opts ...APIOption) *APIHandler {
	for i, opt := range opts {
		if opt == nil {
			panic(fmt.Sprintf("entapi: APIOption at index %d is nil", i))
		}
		opt.applyOption(h)
	}
	return h
}

// Endpoints returns the generated endpoint manifest in deterministic
// registration order. It is data to compose into a router of your choosing;
// ServeHTTP and Mount are the convenience built from the same manifest.
//
// It is the batch half of the composition surface. The per-operation accessors
// below are the take-one-by-name half: they are the values this slice is built
// from, and Except removes the method along with the endpoint, so naming an
// operation that is not exposed is a compile error rather than a lookup that
// finds nothing.
func (h *APIHandler) Endpoints() []entapi.Endpoint {
	return append([]entapi.Endpoint(nil), h.endpoints...)
}

// ListNodesEndpoint returns the generated GET /nodes endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) ListNodesEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "GET",
		Path:    "/nodes",
		Handler: http.HandlerFunc(h.handleListNodes),
		Entity:  "Node",
		Op:      "list",
	}
}

// CreateNodeEndpoint returns the generated POST /nodes endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) CreateNodeEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "POST",
		Path:    "/nodes",
		Handler: http.HandlerFunc(h.handleCreateNode),
		Entity:  "Node",
		Op:      "create",
	}
}

// GetNodeEndpoint returns the generated GET /nodes/{id} endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) GetNodeEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "GET",
		Path:    "/nodes/{id}",
		Handler: http.HandlerFunc(h.handleGetNode),
		Entity:  "Node",
		Op:      "get",
	}
}

// PatchNodeEndpoint returns the generated PATCH /nodes/{id} endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) PatchNodeEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "PATCH",
		Path:    "/nodes/{id}",
		Handler: http.HandlerFunc(h.handlePatchNode),
		Entity:  "Node",
		Op:      "patch",
	}
}

// DeleteNodeEndpoint returns the generated DELETE /nodes/{id} endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) DeleteNodeEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "DELETE",
		Path:    "/nodes/{id}",
		Handler: http.HandlerFunc(h.handleDeleteNode),
		Entity:  "Node",
		Op:      "delete",
	}
}

// OpenAPIEndpoint returns the generated GET /openapi.yaml endpoint serving the
// generated document. It is the manifest's one entry with no Entity and no Op:
// it describes the resource surface rather than belonging to it.
func (h *APIHandler) OpenAPIEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "GET",
		Path:    "/openapi.yaml",
		Handler: http.HandlerFunc(serveOpenAPI),
	}
}

// ServeHTTP serves the generated route tree.
func (h *APIHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h.mux.ServeHTTP(w, r)
}

// Mount registers every generated endpoint on mux.
func (h *APIHandler) Mount(mux *http.ServeMux) {
	for _, ep := range h.endpoints {
		mux.Handle(ep.Method+" "+ep.Path, ep.Handler)
	}
}
