// Code generated by entapi extension from schema "Node". DO NOT EDIT.
// Source template: templates/handler.tmpl
// Regenerate with: make generate

package selfrefpartialent

import (
	"context"
	"fmt"
	"net/http"

	"github.com/google/uuid"

	// Runtime helpers are kept distinct from identifier-type dependencies.
	entapi "github.com/githonllc/entapi/runtime"
)

// ListNodesFn is byte-identical to ListNodes.
type ListNodesFn func(context.Context, *Client, *NodeFilter, entapi.ListRequest) (*entapi.Page[NodeResponse], error)

func (f ListNodesFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: ListNodesFn is nil")
	}
	h.listNodes = f
}

func (h *APIHandler) handleListNodes(w http.ResponseWriter, r *http.Request) {
	filter, request, err := ParseNodeQuery(r.URL.Query())
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}

	response, err := h.listNodes(r.Context(), h.client, filter, request)
	if err != nil {
		status := entapi.Status(err, http.StatusBadRequest)
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	_ = entapi.WriteJSON(w, http.StatusOK, response)
}

// CreateNodeFn is byte-identical to CreateNode.
type CreateNodeFn func(context.Context, *Client, *ValidNodeCreateRequest) (*NodeResponse, error)

func (f CreateNodeFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: CreateNodeFn is nil")
	}
	h.createNode = f
}

func (h *APIHandler) handleCreateNode(w http.ResponseWriter, r *http.Request) {
	var request NodeCreateRequest
	if err := entapi.BindJSON(w, r, nodeCreateRequestTags, &request); err != nil {
		status := entapi.Status(err, http.StatusBadRequest)
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}
	validated, err := request.Validate()
	if err != nil {
		entapi.WriteProblem(w, http.StatusUnprocessableEntity, http.StatusText(http.StatusUnprocessableEntity), err)
		return
	}

	response, err := h.createNode(r.Context(), h.client, validated)
	if err != nil {
		status := entapi.Status(err, http.StatusUnprocessableEntity)
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	_ = entapi.WriteJSON(w, http.StatusCreated, response)
}

// GetNodeFn is byte-identical to GetNode.
type GetNodeFn func(context.Context, *Client, uuid.UUID) (*NodeResponse, error)

func (f GetNodeFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: GetNodeFn is nil")
	}
	h.getNode = f
}

func (h *APIHandler) handleGetNode(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(r.PathValue("id"))
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}

	response, err := h.getNode(r.Context(), h.client, id)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(err):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(err):
			status = http.StatusConflict
		}
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	_ = entapi.WriteJSON(w, http.StatusOK, response)
}

// PatchNodeFn is byte-identical to PatchNode.
type PatchNodeFn func(context.Context, *Client, uuid.UUID, *ValidNodePatchRequest) (*NodeResponse, error)

func (f PatchNodeFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: PatchNodeFn is nil")
	}
	h.patchNode = f
}

func (h *APIHandler) handlePatchNode(w http.ResponseWriter, r *http.Request) {
	var request NodePatchRequest
	if err := entapi.BindJSON(w, r, nodePatchRequestTags, &request); err != nil {
		status := entapi.Status(err, http.StatusBadRequest)
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}
	validated, err := request.Validate()
	if err != nil {
		entapi.WriteProblem(w, http.StatusUnprocessableEntity, http.StatusText(http.StatusUnprocessableEntity), err)
		return
	}
	id, err := uuid.Parse(r.PathValue("id"))
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}

	response, err := h.patchNode(r.Context(), h.client, id, validated)
	if err != nil {
		status := entapi.Status(err, http.StatusUnprocessableEntity)
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	_ = entapi.WriteJSON(w, http.StatusOK, response)
}

// DeleteNodeFn is byte-identical to DeleteNode.
type DeleteNodeFn func(context.Context, *Client, uuid.UUID) error

func (f DeleteNodeFn) applyOption(h *APIHandler) {
	if f == nil {
		panic("entapi: DeleteNodeFn is nil")
	}
	h.deleteNode = f
}

func (h *APIHandler) handleDeleteNode(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(r.PathValue("id"))
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}

	deleteErr := h.deleteNode(r.Context(), h.client, id)
	if deleteErr != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(deleteErr):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(deleteErr):
			status = http.StatusConflict
		}
		entapi.WriteProblem(w, status, http.StatusText(status), deleteErr)
		return
	}

	w.WriteHeader(http.StatusNoContent)
}
