// Code generated by entapi extension for this schema as a whole. DO NOT EDIT.
// Source template: templates/http.tmpl
// Regenerate with: make generate

package strictqueryent

import (
	"fmt"
	"net/http"

	entapi "github.com/githonllc/entapi/runtime"
)

// APIOption replaces one generated operation implementation.
type APIOption interface{ applyOption(*APIHandler) }

// APIHandler is the generated CRUD HTTP surface.
type APIHandler struct {
	client       *Client
	mux          *http.ServeMux
	endpoints    []entapi.Endpoint
	listRecords  ListRecordsFn
	createRecord CreateRecordFn
	getRecord    GetRecordFn
	patchRecord  PatchRecordFn
	deleteRecord DeleteRecordFn
}

// API builds the generated CRUD HTTP surface for client.
func API(client *Client) *APIHandler {
	if !ErrorMap.HasUniqueViolation() {
		if f, ok := entapi.UniqueViolation(client.driver.Dialect()); ok {
			ErrorMap = ErrorMap.WithUniqueViolation(f)
		}
	}
	h := &APIHandler{
		client:       client,
		mux:          http.NewServeMux(),
		listRecords:  ListRecords,
		createRecord: CreateRecord,
		getRecord:    GetRecord,
		patchRecord:  PatchRecord,
		deleteRecord: DeleteRecord,
	}
	// The manifest is assembled from the per-operation accessors below, so the
	// two can never describe different endpoints: there is one construction and
	// no second table.
	h.endpoints = []entapi.Endpoint{
		h.ListRecordsEndpoint(),
		h.CreateRecordEndpoint(),
		h.GetRecordEndpoint(),
		h.PatchRecordEndpoint(),
		h.DeleteRecordEndpoint(),
		// The document describing everything above. It is in the manifest, not
		// beside it, so Endpoints() sees it and a consumer can wrap or drop it
		// with the same loop they use for the CRUD endpoints. It is the one
		// endpoint the document does not describe: it is not part of the
		// resource surface.
		h.OpenAPIEndpoint(),
	}
	for _, ep := range h.endpoints {
		h.mux.Handle(ep.Method+" "+ep.Path, ep.Handler)
	}
	return h
}

// With replaces generated operation implementations before serving begins.
func (h *APIHandler) With(opts ...APIOption) *APIHandler {
	for i, opt := range opts {
		if opt == nil {
			panic(fmt.Sprintf("entapi: APIOption at index %d is nil", i))
		}
		opt.applyOption(h)
	}
	return h
}

// Endpoints returns the generated endpoint manifest in deterministic
// registration order. It is data to compose into a router of your choosing;
// ServeHTTP and Mount are the convenience built from the same manifest.
//
// It is the batch half of the composition surface. The per-operation accessors
// below are the take-one-by-name half: they are the values this slice is built
// from, and Except removes the method along with the endpoint, so naming an
// operation that is not exposed is a compile error rather than a lookup that
// finds nothing.
func (h *APIHandler) Endpoints() []entapi.Endpoint {
	return append([]entapi.Endpoint(nil), h.endpoints...)
}

// ListRecordsEndpoint returns the generated GET /records endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) ListRecordsEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "GET",
		Path:    "/records",
		Handler: http.HandlerFunc(h.handleListRecords),
		Entity:  "Record",
		Op:      "list",
	}
}

// CreateRecordEndpoint returns the generated POST /records endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) CreateRecordEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "POST",
		Path:    "/records",
		Handler: http.HandlerFunc(h.handleCreateRecord),
		Entity:  "Record",
		Op:      "create",
	}
}

// GetRecordEndpoint returns the generated GET /records/{id} endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) GetRecordEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "GET",
		Path:    "/records/{id}",
		Handler: http.HandlerFunc(h.handleGetRecord),
		Entity:  "Record",
		Op:      "get",
	}
}

// PatchRecordEndpoint returns the generated PATCH /records/{id} endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) PatchRecordEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "PATCH",
		Path:    "/records/{id}",
		Handler: http.HandlerFunc(h.handlePatchRecord),
		Entity:  "Record",
		Op:      "patch",
	}
}

// DeleteRecordEndpoint returns the generated DELETE /records/{id} endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) DeleteRecordEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "DELETE",
		Path:    "/records/{id}",
		Handler: http.HandlerFunc(h.handleDeleteRecord),
		Entity:  "Record",
		Op:      "delete",
	}
}

// OpenAPIEndpoint returns the generated GET /openapi.yaml endpoint serving the
// generated document. It is the manifest's one entry with no Entity and no Op:
// it describes the resource surface rather than belonging to it.
func (h *APIHandler) OpenAPIEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "GET",
		Path:    "/openapi.yaml",
		Handler: http.HandlerFunc(serveOpenAPI),
	}
}

// ServeHTTP serves the generated route tree.
func (h *APIHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h.mux.ServeHTTP(w, r)
}

// Mount registers every generated endpoint on mux.
func (h *APIHandler) Mount(mux *http.ServeMux) {
	for _, ep := range h.endpoints {
		mux.Handle(ep.Method+" "+ep.Path, ep.Handler)
	}
}
