// Code generated by entapi extension from schema "Record". DO NOT EDIT.
// Source template: templates/filter.tmpl
// Regenerate with: make generate

package strictqueryent

import (
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/githonllc/entapi/internal/fixtures/strictquery/strictqueryent/predicate"
	"github.com/githonllc/entapi/internal/fixtures/strictquery/strictqueryent/record"
	entapi "github.com/githonllc/entapi/runtime"
)

// RecordFilter is the typed query representation for Record.
// Repeated URL parameters occupy repeated slots and Predicates ANDs them.
type RecordFilter struct {
	// id: int
	ID      []int   `json:"id,omitempty"`
	IDNEQ   []int   `json:"id_neq,omitempty"`
	IDIn    [][]int `json:"id_in,omitempty"`
	IDNotIn [][]int `json:"id_not_in,omitempty"`
	IDGT    []int   `json:"id_gt,omitempty"`
	IDGTE   []int   `json:"id_gte,omitempty"`
	IDLT    []int   `json:"id_lt,omitempty"`
	IDLTE   []int   `json:"id_lte,omitempty"`
	// key: string
	Key      []string   `json:"key,omitempty"`
	KeyNEQ   []string   `json:"key_neq,omitempty"`
	KeyIn    [][]string `json:"key_in,omitempty"`
	KeyNotIn [][]string `json:"key_not_in,omitempty"`
	KeyGT    []string   `json:"key_gt,omitempty"`
	KeyGTE   []string   `json:"key_gte,omitempty"`
	KeyLT    []string   `json:"key_lt,omitempty"`
	KeyLTE   []string   `json:"key_lte,omitempty"`
	// created_at: time.Time
	CreatedAt      []time.Time   `json:"created_at,omitempty"`
	CreatedAtNEQ   []time.Time   `json:"created_at_neq,omitempty"`
	CreatedAtIn    [][]time.Time `json:"created_at_in,omitempty"`
	CreatedAtNotIn [][]time.Time `json:"created_at_not_in,omitempty"`
	CreatedAtGT    []time.Time   `json:"created_at_gt,omitempty"`
	CreatedAtGTE   []time.Time   `json:"created_at_gte,omitempty"`
	CreatedAtLT    []time.Time   `json:"created_at_lt,omitempty"`
	CreatedAtLTE   []time.Time   `json:"created_at_lte,omitempty"`
}

// Predicates converts the typed filter into conjunctive ent predicates.
func (f *RecordFilter) Predicates() []predicate.Record {
	if f == nil {
		return nil
	}
	var ps []predicate.Record
	entapi.AppendEach(&ps, f.ID, record.IDEQ)
	entapi.AppendEach(&ps, f.IDNEQ, record.IDNEQ)
	entapi.AppendEachSlice(&ps, f.IDIn, record.IDIn)
	entapi.AppendEachSlice(&ps, f.IDNotIn, record.IDNotIn)
	entapi.AppendEach(&ps, f.IDGT, record.IDGT)
	entapi.AppendEach(&ps, f.IDGTE, record.IDGTE)
	entapi.AppendEach(&ps, f.IDLT, record.IDLT)
	entapi.AppendEach(&ps, f.IDLTE, record.IDLTE)
	entapi.AppendEach(&ps, f.Key, record.KeyEQ)
	entapi.AppendEach(&ps, f.KeyNEQ, record.KeyNEQ)
	entapi.AppendEachSlice(&ps, f.KeyIn, record.KeyIn)
	entapi.AppendEachSlice(&ps, f.KeyNotIn, record.KeyNotIn)
	entapi.AppendEach(&ps, f.KeyGT, record.KeyGT)
	entapi.AppendEach(&ps, f.KeyGTE, record.KeyGTE)
	entapi.AppendEach(&ps, f.KeyLT, record.KeyLT)
	entapi.AppendEach(&ps, f.KeyLTE, record.KeyLTE)
	entapi.AppendEach(&ps, f.CreatedAt, record.CreatedAtEQ)
	entapi.AppendEach(&ps, f.CreatedAtNEQ, record.CreatedAtNEQ)
	entapi.AppendEachSlice(&ps, f.CreatedAtIn, record.CreatedAtIn)
	entapi.AppendEachSlice(&ps, f.CreatedAtNotIn, record.CreatedAtNotIn)
	entapi.AppendEach(&ps, f.CreatedAtGT, record.CreatedAtGT)
	entapi.AppendEach(&ps, f.CreatedAtGTE, record.CreatedAtGTE)
	entapi.AppendEach(&ps, f.CreatedAtLT, record.CreatedAtLT)
	entapi.AppendEach(&ps, f.CreatedAtLTE, record.CreatedAtLTE)
	return ps
}

func parseRecordIDQueryValue(raw, whole string) (int, error) {
	parsed, err := strconv.ParseInt(raw, 10, 0)
	if err != nil {
		var zero int
		return zero, fmt.Errorf("%w: field %q value %q is not a valid int: %v", entapi.ErrValidation, "id", whole, err)
	}
	return int(parsed), nil
}

func parseRecordKeyQueryValue(raw, whole string) (string, error) {
	return string(raw), nil
}

func parseRecordCreatedAtQueryValue(raw, whole string) (time.Time, error) {
	parsed, err := time.Parse(time.RFC3339, raw)
	if err != nil {
		var zero time.Time
		return zero, fmt.Errorf("%w: field %q value %q is not RFC 3339: %v", entapi.ErrValidation, "created_at", whole, err)
	}
	return time.Time(parsed), nil
}

// ParseRecordQuery parses the complete URL query contract in sorted-key
// order. Runtime code owns lexical grammar; this generated switch owns the
// field-local operator set, conversion and predicate slots.
func ParseRecordQuery(q url.Values) (*RecordFilter, entapi.ListRequest, error) {
	f := &RecordFilter{}
	var request entapi.ListRequest
	keys := make([]string, 0, len(q))
	for key := range q {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		values := q[key]
		reserved, recognized, err := entapi.ReservedQueryValue(key, values)
		if err != nil {
			return nil, entapi.ListRequest{}, err
		}
		if recognized {
			switch key {
			case "_sort":
				request.Sort, err = entapi.ParseSortSpecs(reserved)
			case "_page":
				request.Page, err = entapi.ParsePageParam(key, reserved)
			case "_size":
				request.Size, err = entapi.ParsePageParam(key, reserved)
			case "_q":
				err = fmt.Errorf("%w: _q value %q is invalid because Record has no Searchable fields", entapi.ErrValidation, reserved)
			}
			if err != nil {
				return nil, entapi.ListRequest{}, err
			}
			continue
		}
		if strings.HasPrefix(key, "_") {
			return nil, entapi.ListRequest{}, fmt.Errorf("%w: unknown reserved query parameter %q", entapi.ErrValidation, key)
		}
		switch key {
		case "id":
			for _, whole := range values {
				if whole == "" {
					continue
				}
				op, raw, explicit := entapi.SplitOp(whole)
				if !explicit {
					op = "eq"
				}
				switch op {
				case "eq":
				case "ne":
				case "in":
				case "not_in":
				case "gt":
				case "ge":
				case "lt":
				case "le":
				case "from":
				case "to":
				case "between":
				default:
					if entapi.KnownQueryOperator(op) {
						return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q value %q uses operator %q; legal operators: %s", entapi.ErrValidation, key, whole, op, "eq, ne, in, not_in, gt, ge, lt, le, from, to, between")
					}
					return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q value %q uses unknown operator prefix %q; legal operators: %s; prefix the value with \"eq:\" to filter for a literal value containing a colon", entapi.ErrValidation, key, whole, op, "eq, ne, in, not_in, gt, ge, lt, le, from, to, between")
				}
				switch op {
				case "eq":
					parsed, parseErr := parseRecordIDQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.ID = append(f.ID, parsed)
				case "ne":
					parsed, parseErr := parseRecordIDQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.IDNEQ = append(f.IDNEQ, parsed)
				case "in":
					parts := strings.Split(raw, ",")
					parsedValues := make([]int, 0, len(parts))
					for _, part := range parts {
						parsed, parseErr := parseRecordIDQueryValue(part, whole)
						if parseErr != nil {
							return nil, entapi.ListRequest{}, parseErr
						}
						parsedValues = append(parsedValues, parsed)
					}
					f.IDIn = append(f.IDIn, parsedValues)
				case "not_in":
					parts := strings.Split(raw, ",")
					parsedValues := make([]int, 0, len(parts))
					for _, part := range parts {
						parsed, parseErr := parseRecordIDQueryValue(part, whole)
						if parseErr != nil {
							return nil, entapi.ListRequest{}, parseErr
						}
						parsedValues = append(parsedValues, parsed)
					}
					f.IDNotIn = append(f.IDNotIn, parsedValues)
				case "gt":
					parsed, parseErr := parseRecordIDQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.IDGT = append(f.IDGT, parsed)
				case "ge":
					parsed, parseErr := parseRecordIDQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.IDGTE = append(f.IDGTE, parsed)
				case "lt":
					parsed, parseErr := parseRecordIDQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.IDLT = append(f.IDLT, parsed)
				case "le":
					parsed, parseErr := parseRecordIDQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.IDLTE = append(f.IDLTE, parsed)
				case "from":
					parsed, parseErr := parseRecordIDQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.IDGTE = append(f.IDGTE, parsed)
				case "to":
					parsed, parseErr := parseRecordIDQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.IDLTE = append(f.IDLTE, parsed)
				case "between":
					parts := strings.Split(raw, ",")
					if len(parts) != 2 {
						return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q value %q uses between with %d parts; exactly two are required", entapi.ErrValidation, key, whole, len(parts))
					}
					lower, parseErr := parseRecordIDQueryValue(parts[0], whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					upper, parseErr := parseRecordIDQueryValue(parts[1], whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.IDGTE = append(f.IDGTE, lower)
					f.IDLTE = append(f.IDLTE, upper)
				}
			}
		case "key":
			for _, whole := range values {
				if whole == "" {
					continue
				}
				op, raw, explicit := entapi.SplitOp(whole)
				if !explicit {
					op = "eq"
				}
				switch op {
				case "eq":
				case "ne":
				case "in":
				case "not_in":
				case "gt":
				case "ge":
				case "lt":
				case "le":
				case "from":
				case "to":
				case "between":
				default:
					if entapi.KnownQueryOperator(op) {
						return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q value %q uses operator %q; legal operators: %s", entapi.ErrValidation, key, whole, op, "eq, ne, in, not_in, gt, ge, lt, le, from, to, between")
					}
					return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q value %q uses unknown operator prefix %q; legal operators: %s; prefix the value with \"eq:\" to filter for a literal value containing a colon", entapi.ErrValidation, key, whole, op, "eq, ne, in, not_in, gt, ge, lt, le, from, to, between")
				}
				switch op {
				case "eq":
					parsed, parseErr := parseRecordKeyQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.Key = append(f.Key, parsed)
				case "ne":
					parsed, parseErr := parseRecordKeyQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.KeyNEQ = append(f.KeyNEQ, parsed)
				case "in":
					parts := strings.Split(raw, ",")
					parsedValues := make([]string, 0, len(parts))
					for _, part := range parts {
						parsed, parseErr := parseRecordKeyQueryValue(part, whole)
						if parseErr != nil {
							return nil, entapi.ListRequest{}, parseErr
						}
						parsedValues = append(parsedValues, parsed)
					}
					f.KeyIn = append(f.KeyIn, parsedValues)
				case "not_in":
					parts := strings.Split(raw, ",")
					parsedValues := make([]string, 0, len(parts))
					for _, part := range parts {
						parsed, parseErr := parseRecordKeyQueryValue(part, whole)
						if parseErr != nil {
							return nil, entapi.ListRequest{}, parseErr
						}
						parsedValues = append(parsedValues, parsed)
					}
					f.KeyNotIn = append(f.KeyNotIn, parsedValues)
				case "gt":
					parsed, parseErr := parseRecordKeyQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.KeyGT = append(f.KeyGT, parsed)
				case "ge":
					parsed, parseErr := parseRecordKeyQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.KeyGTE = append(f.KeyGTE, parsed)
				case "lt":
					parsed, parseErr := parseRecordKeyQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.KeyLT = append(f.KeyLT, parsed)
				case "le":
					parsed, parseErr := parseRecordKeyQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.KeyLTE = append(f.KeyLTE, parsed)
				case "from":
					parsed, parseErr := parseRecordKeyQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.KeyGTE = append(f.KeyGTE, parsed)
				case "to":
					parsed, parseErr := parseRecordKeyQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.KeyLTE = append(f.KeyLTE, parsed)
				case "between":
					parts := strings.Split(raw, ",")
					if len(parts) != 2 {
						return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q value %q uses between with %d parts; exactly two are required", entapi.ErrValidation, key, whole, len(parts))
					}
					lower, parseErr := parseRecordKeyQueryValue(parts[0], whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					upper, parseErr := parseRecordKeyQueryValue(parts[1], whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.KeyGTE = append(f.KeyGTE, lower)
					f.KeyLTE = append(f.KeyLTE, upper)
				}
			}
		case "created_at":
			for _, whole := range values {
				if whole == "" {
					continue
				}
				op, raw, explicit := entapi.SplitOp(whole)
				if !explicit {
					op = "eq"
				}
				switch op {
				case "eq":
				case "ne":
				case "in":
				case "not_in":
				case "gt":
				case "ge":
				case "lt":
				case "le":
				case "from":
				case "to":
				case "between":
				default:
					if entapi.KnownQueryOperator(op) {
						return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q value %q uses operator %q; legal operators: %s", entapi.ErrValidation, key, whole, op, "eq, ne, in, not_in, gt, ge, lt, le, from, to, between")
					}
					return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q value %q uses unknown operator prefix %q; legal operators: %s; prefix the value with \"eq:\" to filter for a literal value containing a colon", entapi.ErrValidation, key, whole, op, "eq, ne, in, not_in, gt, ge, lt, le, from, to, between")
				}
				switch op {
				case "eq":
					parsed, parseErr := parseRecordCreatedAtQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.CreatedAt = append(f.CreatedAt, parsed)
				case "ne":
					parsed, parseErr := parseRecordCreatedAtQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.CreatedAtNEQ = append(f.CreatedAtNEQ, parsed)
				case "in":
					parts := strings.Split(raw, ",")
					parsedValues := make([]time.Time, 0, len(parts))
					for _, part := range parts {
						parsed, parseErr := parseRecordCreatedAtQueryValue(part, whole)
						if parseErr != nil {
							return nil, entapi.ListRequest{}, parseErr
						}
						parsedValues = append(parsedValues, parsed)
					}
					f.CreatedAtIn = append(f.CreatedAtIn, parsedValues)
				case "not_in":
					parts := strings.Split(raw, ",")
					parsedValues := make([]time.Time, 0, len(parts))
					for _, part := range parts {
						parsed, parseErr := parseRecordCreatedAtQueryValue(part, whole)
						if parseErr != nil {
							return nil, entapi.ListRequest{}, parseErr
						}
						parsedValues = append(parsedValues, parsed)
					}
					f.CreatedAtNotIn = append(f.CreatedAtNotIn, parsedValues)
				case "gt":
					parsed, parseErr := parseRecordCreatedAtQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.CreatedAtGT = append(f.CreatedAtGT, parsed)
				case "ge":
					parsed, parseErr := parseRecordCreatedAtQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.CreatedAtGTE = append(f.CreatedAtGTE, parsed)
				case "lt":
					parsed, parseErr := parseRecordCreatedAtQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.CreatedAtLT = append(f.CreatedAtLT, parsed)
				case "le":
					parsed, parseErr := parseRecordCreatedAtQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.CreatedAtLTE = append(f.CreatedAtLTE, parsed)
				case "from":
					parsed, parseErr := parseRecordCreatedAtQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.CreatedAtGTE = append(f.CreatedAtGTE, parsed)
				case "to":
					parsed, parseErr := parseRecordCreatedAtQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.CreatedAtLTE = append(f.CreatedAtLTE, parsed)
				case "between":
					parts := strings.Split(raw, ",")
					if len(parts) != 2 {
						return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q value %q uses between with %d parts; exactly two are required", entapi.ErrValidation, key, whole, len(parts))
					}
					lower, parseErr := parseRecordCreatedAtQueryValue(parts[0], whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					upper, parseErr := parseRecordCreatedAtQueryValue(parts[1], whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.CreatedAtGTE = append(f.CreatedAtGTE, lower)
					f.CreatedAtLTE = append(f.CreatedAtLTE, upper)
				}
			}
		default:
			switch key {
			default:
				return nil, entapi.ListRequest{}, fmt.Errorf("%w: unknown query field %q with value %q", entapi.ErrValidation, key, values)
			}
		}
	}
	return f, request, nil
}

var recordSortOptions = map[string]func(...sql.OrderTermOption) record.OrderOption{
	"id": record.ByID,
}

// RecordSortKeys is the complete sort allow-list. The primary key is
// naturally Sortable; every other key requires api.Sortable().
var RecordSortKeys = []string{
	"id",
}

// RecordOrder is the single sort allow-list seam.
func RecordOrder(r entapi.ListRequest) ([]record.OrderOption, error) {
	if len(r.Sort) == 0 {
		return []record.OrderOption{record.ByID(sql.OrderAsc())}, nil
	}
	order := make([]record.OrderOption, 0, len(r.Sort)+1)
	idPresent := false
	lastDir := sql.OrderAsc()
	for _, spec := range r.Sort {
		by, ok := recordSortOptions[spec.Key]
		if !ok {
			return nil, fmt.Errorf("%w: cannot sort by %q; legal keys: %s", entapi.ErrValidation, spec.Key, strings.Join(RecordSortKeys, ", "))
		}
		dir := sql.OrderAsc()
		if spec.Desc {
			dir = sql.OrderDesc()
		}
		order = append(order, by(dir))
		lastDir = dir
		if spec.Key == "id" {
			idPresent = true
		}
	}
	if !idPresent {
		order = append(order, record.ByID(lastDir))
	}
	return order, nil
}
