// Code generated by entapi extension from schema "AuditLog". DO NOT EDIT.
// Source template: templates/handler.tmpl
// Regenerate with: make generate

package httpdemoent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime"
	"net/http"

	"github.com/google/uuid"

	// Runtime helpers are kept distinct from identifier-type dependencies.
	entapi "github.com/githonllc/entapi/runtime"
)

// ListAuditLogsFn is byte-identical to ListAuditLogs.
type ListAuditLogsFn func(context.Context, *Client, *AuditLogFilter, entapi.ListRequest) (*entapi.Page[AuditLogResponse], error)

func (h *APIHandler) handleListAuditLogs(w http.ResponseWriter, r *http.Request) {
	filter, request, err := ParseAuditLogQuery(r.URL.Query())
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}

	response, err := h.listAuditLogs(r.Context(), h.client, filter, request)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(err):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(err):
			status = http.StatusConflict
		case entapi.IsValidation(err):
			status = http.StatusBadRequest
		}
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	body, err := json.Marshal(response)
	if err != nil {
		entapi.WriteProblem(w, http.StatusInternalServerError, http.StatusText(http.StatusInternalServerError), err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(append(body, '\n'))
}

// CreateAuditLogFn is byte-identical to CreateAuditLog.
type CreateAuditLogFn func(context.Context, *Client, *ValidAuditLogCreateRequest) (*AuditLogResponse, error)

func (h *APIHandler) handleCreateAuditLog(w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
	mediaType, _, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
	if err != nil || mediaType != "application/json" {
		entapi.WriteProblem(w, http.StatusUnsupportedMediaType, http.StatusText(http.StatusUnsupportedMediaType),
			errors.New("content type must be application/json"))
		return
	}
	body, err := io.ReadAll(r.Body)
	if err != nil {
		var maxBytesErr *http.MaxBytesError
		if errors.As(err, &maxBytesErr) {
			entapi.WriteProblem(w, http.StatusRequestEntityTooLarge, http.StatusText(http.StatusRequestEntityTooLarge), err)
			return
		}
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(body, &raw); err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	unknownField := ""
	for key := range raw {
		known := false
		for _, tag := range auditLogCreateRequestTags {
			if key == tag {
				known = true
				break
			}
		}
		if !known && (unknownField == "" || key < unknownField) {
			unknownField = key
		}
	}
	if unknownField != "" {
		err := &entapi.FieldError{
			Field: unknownField,
			Err:   fmt.Errorf("%w: unknown field %q", entapi.ErrValidation, unknownField),
		}
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	var request AuditLogCreateRequest
	if err := json.Unmarshal(body, &request); err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	validated, err := request.Validate()
	if err != nil {
		entapi.WriteProblem(w, http.StatusUnprocessableEntity, http.StatusText(http.StatusUnprocessableEntity), err)
		return
	}

	response, err := h.createAuditLog(r.Context(), h.client, validated)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(err):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(err):
			status = http.StatusConflict
		case entapi.IsValidation(err):
			status = http.StatusUnprocessableEntity
		}
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	body, err = json.Marshal(response)
	if err != nil {
		entapi.WriteProblem(w, http.StatusInternalServerError, http.StatusText(http.StatusInternalServerError), err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(append(body, '\n'))
}

// GetAuditLogFn is byte-identical to GetAuditLog.
type GetAuditLogFn func(context.Context, *Client, uuid.UUID) (*AuditLogResponse, error)

func (h *APIHandler) handleGetAuditLog(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(r.PathValue("id"))
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}

	response, err := h.getAuditLog(r.Context(), h.client, id)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(err):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(err):
			status = http.StatusConflict
		}
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	body, err := json.Marshal(response)
	if err != nil {
		entapi.WriteProblem(w, http.StatusInternalServerError, http.StatusText(http.StatusInternalServerError), err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(append(body, '\n'))
}

// PatchAuditLogFn is byte-identical to PatchAuditLog.
type PatchAuditLogFn func(context.Context, *Client, uuid.UUID, *ValidAuditLogPatchRequest) (*AuditLogResponse, error)

func (h *APIHandler) handlePatchAuditLog(w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
	mediaType, _, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
	if err != nil || mediaType != "application/json" {
		entapi.WriteProblem(w, http.StatusUnsupportedMediaType, http.StatusText(http.StatusUnsupportedMediaType),
			errors.New("content type must be application/json"))
		return
	}
	body, err := io.ReadAll(r.Body)
	if err != nil {
		var maxBytesErr *http.MaxBytesError
		if errors.As(err, &maxBytesErr) {
			entapi.WriteProblem(w, http.StatusRequestEntityTooLarge, http.StatusText(http.StatusRequestEntityTooLarge), err)
			return
		}
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(body, &raw); err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	unknownField := ""
	for key := range raw {
		known := false
		for _, tag := range auditLogPatchRequestTags {
			if key == tag {
				known = true
				break
			}
		}
		if !known && (unknownField == "" || key < unknownField) {
			unknownField = key
		}
	}
	if unknownField != "" {
		err := &entapi.FieldError{
			Field: unknownField,
			Err:   fmt.Errorf("%w: unknown field %q", entapi.ErrValidation, unknownField),
		}
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	var request AuditLogPatchRequest
	if err := json.Unmarshal(body, &request); err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest), err)
		return
	}
	validated, err := request.Validate()
	if err != nil {
		entapi.WriteProblem(w, http.StatusUnprocessableEntity, http.StatusText(http.StatusUnprocessableEntity), err)
		return
	}
	id, err := uuid.Parse(r.PathValue("id"))
	if err != nil {
		entapi.WriteProblem(w, http.StatusBadRequest, http.StatusText(http.StatusBadRequest),
			fmt.Errorf("invalid path id %q: %w", r.PathValue("id"), err))
		return
	}

	response, err := h.patchAuditLog(r.Context(), h.client, id, validated)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case entapi.IsNotFound(err):
			status = http.StatusNotFound
		case entapi.IsAlreadyExists(err):
			status = http.StatusConflict
		case entapi.IsValidation(err):
			status = http.StatusUnprocessableEntity
		}
		entapi.WriteProblem(w, status, http.StatusText(status), err)
		return
	}

	body, err = json.Marshal(response)
	if err != nil {
		entapi.WriteProblem(w, http.StatusInternalServerError, http.StatusText(http.StatusInternalServerError), err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(append(body, '\n'))
}
