// Code generated by ent, DO NOT EDIT.

package account

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the account type in the database.
	Label = "account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldSeats holds the string denoting the seats field in the database.
	FieldSeats = "seats"
	// FieldAcceptedTerms holds the string denoting the accepted_terms field in the database.
	FieldAcceptedTerms = "accepted_terms"
	// FieldPlan holds the string denoting the plan field in the database.
	FieldPlan = "plan"
	// FieldNickname holds the string denoting the nickname field in the database.
	FieldNickname = "nickname"
	// FieldQuota holds the string denoting the quota field in the database.
	FieldQuota = "quota"
	// FieldOrigin holds the string denoting the origin field in the database.
	FieldOrigin = "origin"
	// Table holds the table name of the account in the database.
	Table = "accounts"
)

// Columns holds all SQL columns for account fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldSeats,
	FieldAcceptedTerms,
	FieldPlan,
	FieldNickname,
	FieldQuota,
	FieldOrigin,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Plan defines the type for the "plan" enum field.
type Plan string

// PlanFree is the default value of the Plan enum.
const DefaultPlan = PlanFree

// Plan values.
const (
	PlanFree Plan = "free"
	PlanPro  Plan = "pro"
)

func (pl Plan) String() string {
	return string(pl)
}

// PlanValidator is a validator for the "plan" field enum values. It is called by the builders before save.
func PlanValidator(pl Plan) error {
	switch pl {
	case PlanFree, PlanPro:
		return nil
	default:
		return fmt.Errorf("account: invalid enum value for plan field: %q", pl)
	}
}

// OrderOption defines the ordering options for the Account queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// BySeats orders the results by the seats field.
func BySeats(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeats, opts...).ToFunc()
}

// ByAcceptedTerms orders the results by the accepted_terms field.
func ByAcceptedTerms(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAcceptedTerms, opts...).ToFunc()
}

// ByPlan orders the results by the plan field.
func ByPlan(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlan, opts...).ToFunc()
}

// ByNickname orders the results by the nickname field.
func ByNickname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNickname, opts...).ToFunc()
}

// ByQuota orders the results by the quota field.
func ByQuota(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuota, opts...).ToFunc()
}

// ByOrigin orders the results by the origin field.
func ByOrigin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrigin, opts...).ToFunc()
}
