// Code generated by entapi extension for this schema as a whole. DO NOT EDIT.
// Source template: templates/http.tmpl
// Regenerate with: make generate

package softdeleteent

import (
	"fmt"
	"net/http"

	entapi "github.com/githonllc/entapi/runtime"
)

// APIOption replaces one generated operation implementation.
type APIOption interface{ applyOption(*APIHandler) }

// APIHandler is the generated CRUD HTTP surface.
type APIHandler struct {
	client       *Client
	mux          *http.ServeMux
	endpoints    []entapi.Endpoint
	listDocs     ListDocsFn
	createDoc    CreateDocFn
	getDoc       GetDocFn
	patchDoc     PatchDocFn
	deleteDoc    DeleteDocFn
	listDrafts   ListDraftsFn
	getDraft     GetDraftFn
	deleteDraft  DeleteDraftFn
	listLedgers  ListLedgersFn
	createLedger CreateLedgerFn
	getLedger    GetLedgerFn
	patchLedger  PatchLedgerFn
	deleteLedger DeleteLedgerFn
	listNotes    ListNotesFn
	createNote   CreateNoteFn
	getNote      GetNoteFn
	patchNote    PatchNoteFn
	deleteNote   DeleteNoteFn
}

// API builds the generated CRUD HTTP surface for client.
func API(client *Client) *APIHandler {
	if !ErrorMap.HasUniqueViolation() {
		if f, ok := entapi.UniqueViolation(client.driver.Dialect()); ok {
			ErrorMap = ErrorMap.WithUniqueViolation(f)
		}
	}
	h := &APIHandler{
		client:       client,
		mux:          http.NewServeMux(),
		listDocs:     ListDocs,
		createDoc:    CreateDoc,
		getDoc:       GetDoc,
		patchDoc:     PatchDoc,
		deleteDoc:    DeleteDoc,
		listDrafts:   ListDrafts,
		getDraft:     GetDraft,
		deleteDraft:  DeleteDraft,
		listLedgers:  ListLedgers,
		createLedger: CreateLedger,
		getLedger:    GetLedger,
		patchLedger:  PatchLedger,
		deleteLedger: DeleteLedger,
		listNotes:    ListNotes,
		createNote:   CreateNote,
		getNote:      GetNote,
		patchNote:    PatchNote,
		deleteNote:   DeleteNote,
	}
	h.endpoints = []entapi.Endpoint{
		{
			Method:  "GET",
			Path:    "/docs",
			Handler: http.HandlerFunc(h.handleListDocs),
			Entity:  "Doc",
			Op:      "list",
		},
		{
			Method:  "POST",
			Path:    "/docs",
			Handler: http.HandlerFunc(h.handleCreateDoc),
			Entity:  "Doc",
			Op:      "create",
		},
		{
			Method:  "GET",
			Path:    "/docs/{id}",
			Handler: http.HandlerFunc(h.handleGetDoc),
			Entity:  "Doc",
			Op:      "get",
		},
		{
			Method:  "PATCH",
			Path:    "/docs/{id}",
			Handler: http.HandlerFunc(h.handlePatchDoc),
			Entity:  "Doc",
			Op:      "patch",
		},
		{
			Method:  "DELETE",
			Path:    "/docs/{id}",
			Handler: http.HandlerFunc(h.handleDeleteDoc),
			Entity:  "Doc",
			Op:      "delete",
		},
		{
			Method:  "GET",
			Path:    "/drafts",
			Handler: http.HandlerFunc(h.handleListDrafts),
			Entity:  "Draft",
			Op:      "list",
		},
		{
			Method:  "GET",
			Path:    "/drafts/{id}",
			Handler: http.HandlerFunc(h.handleGetDraft),
			Entity:  "Draft",
			Op:      "get",
		},
		{
			Method:  "DELETE",
			Path:    "/drafts/{id}",
			Handler: http.HandlerFunc(h.handleDeleteDraft),
			Entity:  "Draft",
			Op:      "delete",
		},
		{
			Method:  "GET",
			Path:    "/ledgers",
			Handler: http.HandlerFunc(h.handleListLedgers),
			Entity:  "Ledger",
			Op:      "list",
		},
		{
			Method:  "POST",
			Path:    "/ledgers",
			Handler: http.HandlerFunc(h.handleCreateLedger),
			Entity:  "Ledger",
			Op:      "create",
		},
		{
			Method:  "GET",
			Path:    "/ledgers/{id}",
			Handler: http.HandlerFunc(h.handleGetLedger),
			Entity:  "Ledger",
			Op:      "get",
		},
		{
			Method:  "PATCH",
			Path:    "/ledgers/{id}",
			Handler: http.HandlerFunc(h.handlePatchLedger),
			Entity:  "Ledger",
			Op:      "patch",
		},
		{
			Method:  "DELETE",
			Path:    "/ledgers/{id}",
			Handler: http.HandlerFunc(h.handleDeleteLedger),
			Entity:  "Ledger",
			Op:      "delete",
		},
		{
			Method:  "GET",
			Path:    "/notes",
			Handler: http.HandlerFunc(h.handleListNotes),
			Entity:  "Note",
			Op:      "list",
		},
		{
			Method:  "POST",
			Path:    "/notes",
			Handler: http.HandlerFunc(h.handleCreateNote),
			Entity:  "Note",
			Op:      "create",
		},
		{
			Method:  "GET",
			Path:    "/notes/{id}",
			Handler: http.HandlerFunc(h.handleGetNote),
			Entity:  "Note",
			Op:      "get",
		},
		{
			Method:  "PATCH",
			Path:    "/notes/{id}",
			Handler: http.HandlerFunc(h.handlePatchNote),
			Entity:  "Note",
			Op:      "patch",
		},
		{
			Method:  "DELETE",
			Path:    "/notes/{id}",
			Handler: http.HandlerFunc(h.handleDeleteNote),
			Entity:  "Note",
			Op:      "delete",
		},
		// The document describing everything above. It is in the manifest, not
		// beside it, so Endpoints() sees it and a consumer can wrap or drop it
		// with the same loop they use for the CRUD endpoints. It is the one
		// endpoint the document does not describe: it is not part of the
		// resource surface.
		{
			Method:  "GET",
			Path:    "/openapi.yaml",
			Handler: http.HandlerFunc(serveOpenAPI),
		},
	}
	for _, ep := range h.endpoints {
		h.mux.Handle(ep.Method+" "+ep.Path, ep.Handler)
	}
	return h
}

// With replaces generated operation implementations before serving begins.
func (h *APIHandler) With(opts ...APIOption) *APIHandler {
	for i, opt := range opts {
		if opt == nil {
			panic(fmt.Sprintf("entapi: APIOption at index %d is nil", i))
		}
		opt.applyOption(h)
	}
	return h
}

// Endpoints returns the generated endpoint manifest in deterministic
// registration order. It is data to compose into a router of your choosing;
// ServeHTTP and Mount are the convenience built from the same manifest.
func (h *APIHandler) Endpoints() []entapi.Endpoint {
	return append([]entapi.Endpoint(nil), h.endpoints...)
}

// ServeHTTP serves the generated route tree.
func (h *APIHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h.mux.ServeHTTP(w, r)
}

// Mount registers every generated endpoint on mux.
func (h *APIHandler) Mount(mux *http.ServeMux) {
	for _, ep := range h.endpoints {
		mux.Handle(ep.Method+" "+ep.Path, ep.Handler)
	}
}
