// Code generated by entapi extension for this schema as a whole. DO NOT EDIT.
// Source template: templates/http.tmpl
// Regenerate with: make generate

package softdeleteent

import (
	"fmt"
	"net/http"

	entapi "github.com/githonllc/entapi/runtime"
)

// APIOption replaces one generated operation implementation.
type APIOption interface{ applyOption(*APIHandler) }

// APIHandler is the generated CRUD HTTP surface.
type APIHandler struct {
	client       *Client
	mux          *http.ServeMux
	endpoints    []entapi.Endpoint
	listDocs     ListDocsFn
	createDoc    CreateDocFn
	getDoc       GetDocFn
	patchDoc     PatchDocFn
	deleteDoc    DeleteDocFn
	listDrafts   ListDraftsFn
	getDraft     GetDraftFn
	deleteDraft  DeleteDraftFn
	listLedgers  ListLedgersFn
	createLedger CreateLedgerFn
	getLedger    GetLedgerFn
	patchLedger  PatchLedgerFn
	deleteLedger DeleteLedgerFn
	listNotes    ListNotesFn
	createNote   CreateNoteFn
	getNote      GetNoteFn
	patchNote    PatchNoteFn
	deleteNote   DeleteNoteFn
}

// API builds the generated CRUD HTTP surface for client.
func API(client *Client) *APIHandler {
	if !ErrorMap.HasUniqueViolation() {
		if f, ok := entapi.UniqueViolation(client.driver.Dialect()); ok {
			ErrorMap = ErrorMap.WithUniqueViolation(f)
		}
	}
	h := &APIHandler{
		client:       client,
		mux:          http.NewServeMux(),
		listDocs:     ListDocs,
		createDoc:    CreateDoc,
		getDoc:       GetDoc,
		patchDoc:     PatchDoc,
		deleteDoc:    DeleteDoc,
		listDrafts:   ListDrafts,
		getDraft:     GetDraft,
		deleteDraft:  DeleteDraft,
		listLedgers:  ListLedgers,
		createLedger: CreateLedger,
		getLedger:    GetLedger,
		patchLedger:  PatchLedger,
		deleteLedger: DeleteLedger,
		listNotes:    ListNotes,
		createNote:   CreateNote,
		getNote:      GetNote,
		patchNote:    PatchNote,
		deleteNote:   DeleteNote,
	}
	// The manifest is assembled from the per-operation accessors below, so the
	// two can never describe different endpoints: there is one construction and
	// no second table.
	h.endpoints = []entapi.Endpoint{
		h.ListDocsEndpoint(),
		h.CreateDocEndpoint(),
		h.GetDocEndpoint(),
		h.PatchDocEndpoint(),
		h.DeleteDocEndpoint(),
		h.ListDraftsEndpoint(),
		h.GetDraftEndpoint(),
		h.DeleteDraftEndpoint(),
		h.ListLedgersEndpoint(),
		h.CreateLedgerEndpoint(),
		h.GetLedgerEndpoint(),
		h.PatchLedgerEndpoint(),
		h.DeleteLedgerEndpoint(),
		h.ListNotesEndpoint(),
		h.CreateNoteEndpoint(),
		h.GetNoteEndpoint(),
		h.PatchNoteEndpoint(),
		h.DeleteNoteEndpoint(),
		// The document describing everything above. It is in the manifest, not
		// beside it, so Endpoints() sees it and a consumer can wrap or drop it
		// with the same loop they use for the CRUD endpoints. It is the one
		// endpoint the document does not describe: it is not part of the
		// resource surface.
		h.OpenAPIEndpoint(),
	}
	for _, ep := range h.endpoints {
		h.mux.Handle(ep.Method+" "+ep.Path, ep.Handler)
	}
	return h
}

// With replaces generated operation implementations before serving begins.
func (h *APIHandler) With(opts ...APIOption) *APIHandler {
	for i, opt := range opts {
		if opt == nil {
			panic(fmt.Sprintf("entapi: APIOption at index %d is nil", i))
		}
		opt.applyOption(h)
	}
	return h
}

// Endpoints returns the generated endpoint manifest in deterministic
// registration order. It is data to compose into a router of your choosing;
// ServeHTTP and Mount are the convenience built from the same manifest.
//
// It is the batch half of the composition surface. The per-operation accessors
// below are the take-one-by-name half: they are the values this slice is built
// from, and Except removes the method along with the endpoint, so naming an
// operation that is not exposed is a compile error rather than a lookup that
// finds nothing.
func (h *APIHandler) Endpoints() []entapi.Endpoint {
	return append([]entapi.Endpoint(nil), h.endpoints...)
}

// ListDocsEndpoint returns the generated GET /docs endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) ListDocsEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "GET",
		Path:    "/docs",
		Handler: http.HandlerFunc(h.handleListDocs),
		Entity:  "Doc",
		Op:      "list",
	}
}

// CreateDocEndpoint returns the generated POST /docs endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) CreateDocEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "POST",
		Path:    "/docs",
		Handler: http.HandlerFunc(h.handleCreateDoc),
		Entity:  "Doc",
		Op:      "create",
	}
}

// GetDocEndpoint returns the generated GET /docs/{id} endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) GetDocEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "GET",
		Path:    "/docs/{id}",
		Handler: http.HandlerFunc(h.handleGetDoc),
		Entity:  "Doc",
		Op:      "get",
	}
}

// PatchDocEndpoint returns the generated PATCH /docs/{id} endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) PatchDocEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "PATCH",
		Path:    "/docs/{id}",
		Handler: http.HandlerFunc(h.handlePatchDoc),
		Entity:  "Doc",
		Op:      "patch",
	}
}

// DeleteDocEndpoint returns the generated DELETE /docs/{id} endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) DeleteDocEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "DELETE",
		Path:    "/docs/{id}",
		Handler: http.HandlerFunc(h.handleDeleteDoc),
		Entity:  "Doc",
		Op:      "delete",
	}
}

// ListDraftsEndpoint returns the generated GET /drafts endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) ListDraftsEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "GET",
		Path:    "/drafts",
		Handler: http.HandlerFunc(h.handleListDrafts),
		Entity:  "Draft",
		Op:      "list",
	}
}

// GetDraftEndpoint returns the generated GET /drafts/{id} endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) GetDraftEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "GET",
		Path:    "/drafts/{id}",
		Handler: http.HandlerFunc(h.handleGetDraft),
		Entity:  "Draft",
		Op:      "get",
	}
}

// DeleteDraftEndpoint returns the generated DELETE /drafts/{id} endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) DeleteDraftEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "DELETE",
		Path:    "/drafts/{id}",
		Handler: http.HandlerFunc(h.handleDeleteDraft),
		Entity:  "Draft",
		Op:      "delete",
	}
}

// ListLedgersEndpoint returns the generated GET /ledgers endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) ListLedgersEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "GET",
		Path:    "/ledgers",
		Handler: http.HandlerFunc(h.handleListLedgers),
		Entity:  "Ledger",
		Op:      "list",
	}
}

// CreateLedgerEndpoint returns the generated POST /ledgers endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) CreateLedgerEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "POST",
		Path:    "/ledgers",
		Handler: http.HandlerFunc(h.handleCreateLedger),
		Entity:  "Ledger",
		Op:      "create",
	}
}

// GetLedgerEndpoint returns the generated GET /ledgers/{id} endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) GetLedgerEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "GET",
		Path:    "/ledgers/{id}",
		Handler: http.HandlerFunc(h.handleGetLedger),
		Entity:  "Ledger",
		Op:      "get",
	}
}

// PatchLedgerEndpoint returns the generated PATCH /ledgers/{id} endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) PatchLedgerEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "PATCH",
		Path:    "/ledgers/{id}",
		Handler: http.HandlerFunc(h.handlePatchLedger),
		Entity:  "Ledger",
		Op:      "patch",
	}
}

// DeleteLedgerEndpoint returns the generated DELETE /ledgers/{id} endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) DeleteLedgerEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "DELETE",
		Path:    "/ledgers/{id}",
		Handler: http.HandlerFunc(h.handleDeleteLedger),
		Entity:  "Ledger",
		Op:      "delete",
	}
}

// ListNotesEndpoint returns the generated GET /notes endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) ListNotesEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "GET",
		Path:    "/notes",
		Handler: http.HandlerFunc(h.handleListNotes),
		Entity:  "Note",
		Op:      "list",
	}
}

// CreateNoteEndpoint returns the generated POST /notes endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) CreateNoteEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "POST",
		Path:    "/notes",
		Handler: http.HandlerFunc(h.handleCreateNote),
		Entity:  "Note",
		Op:      "create",
	}
}

// GetNoteEndpoint returns the generated GET /notes/{id} endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) GetNoteEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "GET",
		Path:    "/notes/{id}",
		Handler: http.HandlerFunc(h.handleGetNote),
		Entity:  "Note",
		Op:      "get",
	}
}

// PatchNoteEndpoint returns the generated PATCH /notes/{id} endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) PatchNoteEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "PATCH",
		Path:    "/notes/{id}",
		Handler: http.HandlerFunc(h.handlePatchNote),
		Entity:  "Note",
		Op:      "patch",
	}
}

// DeleteNoteEndpoint returns the generated DELETE /notes/{id} endpoint,
// the same value the manifest carries. Its handler reads the current
// implementation through h, so a With after this call still takes effect.
func (h *APIHandler) DeleteNoteEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "DELETE",
		Path:    "/notes/{id}",
		Handler: http.HandlerFunc(h.handleDeleteNote),
		Entity:  "Note",
		Op:      "delete",
	}
}

// OpenAPIEndpoint returns the generated GET /openapi.yaml endpoint serving the
// generated document. It is the manifest's one entry with no Entity and no Op:
// it describes the resource surface rather than belonging to it.
func (h *APIHandler) OpenAPIEndpoint() entapi.Endpoint {
	return entapi.Endpoint{
		Method:  "GET",
		Path:    "/openapi.yaml",
		Handler: http.HandlerFunc(serveOpenAPI),
	}
}

// ServeHTTP serves the generated route tree.
func (h *APIHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h.mux.ServeHTTP(w, r)
}

// Mount registers every generated endpoint on mux.
func (h *APIHandler) Mount(mux *http.ServeMux) {
	for _, ep := range h.endpoints {
		mux.Handle(ep.Method+" "+ep.Path, ep.Handler)
	}
}
