// Code generated by entapi extension from schema "Ledger". DO NOT EDIT.
// Source template: templates/filter.tmpl
// Regenerate with: make generate

package softdeleteent

import (
	"encoding"
	"fmt"
	"net/url"
	"sort"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/githonllc/entapi/internal/fixtures/softdelete/softdeleteent/ledger"
	"github.com/githonllc/entapi/internal/fixtures/softdelete/softdeleteent/predicate"
	entapi "github.com/githonllc/entapi/runtime"
	"github.com/google/uuid"
)

// LedgerFilter is the typed query representation for Ledger.
// Repeated URL parameters occupy repeated slots and Predicates ANDs them.
type LedgerFilter struct {
	// id: uuid.UUID
	ID      []uuid.UUID   `json:"id,omitempty"`
	IDNEQ   []uuid.UUID   `json:"id_neq,omitempty"`
	IDIn    [][]uuid.UUID `json:"id_in,omitempty"`
	IDNotIn [][]uuid.UUID `json:"id_not_in,omitempty"`
	IDGT    []uuid.UUID   `json:"id_gt,omitempty"`
	IDGTE   []uuid.UUID   `json:"id_gte,omitempty"`
	IDLT    []uuid.UUID   `json:"id_lt,omitempty"`
	IDLTE   []uuid.UUID   `json:"id_lte,omitempty"`
}

// Predicates converts the typed filter into conjunctive ent predicates.
func (f *LedgerFilter) Predicates() []predicate.Ledger {
	if f == nil {
		return nil
	}
	var ps []predicate.Ledger
	entapi.AppendEach(&ps, f.ID, ledger.IDEQ)
	entapi.AppendEach(&ps, f.IDNEQ, ledger.IDNEQ)
	entapi.AppendEachSlice(&ps, f.IDIn, ledger.IDIn)
	entapi.AppendEachSlice(&ps, f.IDNotIn, ledger.IDNotIn)
	entapi.AppendEach(&ps, f.IDGT, ledger.IDGT)
	entapi.AppendEach(&ps, f.IDGTE, ledger.IDGTE)
	entapi.AppendEach(&ps, f.IDLT, ledger.IDLT)
	entapi.AppendEach(&ps, f.IDLTE, ledger.IDLTE)
	return ps
}

func parseLedgerIDQueryValue(raw, whole string) (uuid.UUID, error) {
	var parsed uuid.UUID
	if err := encoding.TextUnmarshaler(&parsed).UnmarshalText([]byte(raw)); err != nil {
		return parsed, fmt.Errorf("%w: field %q value %q is invalid: %v", entapi.ErrValidation, "id", whole, err)
	}
	return parsed, nil
}

// ParseLedgerQuery parses the complete URL query contract in sorted-key
// order. Runtime code owns lexical grammar; this generated switch owns the
// field-local operator set, conversion and predicate slots.
func ParseLedgerQuery(q url.Values) (*LedgerFilter, entapi.ListRequest, error) {
	f := &LedgerFilter{}
	var request entapi.ListRequest
	keys := make([]string, 0, len(q))
	for key := range q {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		values := q[key]
		reserved, recognized, err := entapi.ReservedQueryValue(key, values)
		if err != nil {
			return nil, entapi.ListRequest{}, err
		}
		if recognized {
			switch key {
			case "_sort":
				request.Sort, err = entapi.ParseSortSpecs(reserved)
			case "_page":
				request.Page, err = entapi.ParsePageParam(key, reserved)
			case "_size":
				request.Size, err = entapi.ParsePageParam(key, reserved)
			case "_q":
				err = fmt.Errorf("%w: _q value %q is invalid because Ledger has no Searchable fields", entapi.ErrValidation, reserved)
			}
			if err != nil {
				return nil, entapi.ListRequest{}, err
			}
			continue
		}
		if strings.HasPrefix(key, "_") {
			return nil, entapi.ListRequest{}, fmt.Errorf("%w: unknown reserved query parameter %q", entapi.ErrValidation, key)
		}
		switch key {
		case "id":
			for _, whole := range values {
				if whole == "" {
					continue
				}
				op, raw, explicit := entapi.SplitOp(whole)
				if !explicit {
					op = "eq"
				}
				switch op {
				case "eq":
				case "ne":
				case "in":
				case "not_in":
				case "gt":
				case "ge":
				case "lt":
				case "le":
				case "from":
				case "to":
				case "between":
				default:
					if entapi.KnownQueryOperator(op) {
						return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q value %q uses operator %q; legal operators: %s", entapi.ErrValidation, key, whole, op, "eq, ne, in, not_in, gt, ge, lt, le, from, to, between")
					}
					op, raw = "eq", whole
				}
				switch op {
				case "eq":
					parsed, parseErr := parseLedgerIDQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.ID = append(f.ID, parsed)
				case "ne":
					parsed, parseErr := parseLedgerIDQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.IDNEQ = append(f.IDNEQ, parsed)
				case "in":
					parts := strings.Split(raw, ",")
					parsedValues := make([]uuid.UUID, 0, len(parts))
					for _, part := range parts {
						parsed, parseErr := parseLedgerIDQueryValue(part, whole)
						if parseErr != nil {
							return nil, entapi.ListRequest{}, parseErr
						}
						parsedValues = append(parsedValues, parsed)
					}
					f.IDIn = append(f.IDIn, parsedValues)
				case "not_in":
					parts := strings.Split(raw, ",")
					parsedValues := make([]uuid.UUID, 0, len(parts))
					for _, part := range parts {
						parsed, parseErr := parseLedgerIDQueryValue(part, whole)
						if parseErr != nil {
							return nil, entapi.ListRequest{}, parseErr
						}
						parsedValues = append(parsedValues, parsed)
					}
					f.IDNotIn = append(f.IDNotIn, parsedValues)
				case "gt":
					parsed, parseErr := parseLedgerIDQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.IDGT = append(f.IDGT, parsed)
				case "ge":
					parsed, parseErr := parseLedgerIDQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.IDGTE = append(f.IDGTE, parsed)
				case "lt":
					parsed, parseErr := parseLedgerIDQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.IDLT = append(f.IDLT, parsed)
				case "le":
					parsed, parseErr := parseLedgerIDQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.IDLTE = append(f.IDLTE, parsed)
				case "from":
					parsed, parseErr := parseLedgerIDQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.IDGTE = append(f.IDGTE, parsed)
				case "to":
					parsed, parseErr := parseLedgerIDQueryValue(raw, whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.IDLTE = append(f.IDLTE, parsed)
				case "between":
					parts := strings.Split(raw, ",")
					if len(parts) != 2 {
						return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q value %q uses between with %d parts; exactly two are required", entapi.ErrValidation, key, whole, len(parts))
					}
					lower, parseErr := parseLedgerIDQueryValue(parts[0], whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					upper, parseErr := parseLedgerIDQueryValue(parts[1], whole)
					if parseErr != nil {
						return nil, entapi.ListRequest{}, parseErr
					}
					f.IDGTE = append(f.IDGTE, lower)
					f.IDLTE = append(f.IDLTE, upper)
				}
			}
		default:
			switch key {
			case "entry":
				return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q with value %q is not Filterable", entapi.ErrValidation, key, values)
			case "deleted_at":
				return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q with value %q is not Filterable", entapi.ErrValidation, key, values)
			default:
				return nil, entapi.ListRequest{}, fmt.Errorf("%w: unknown query field %q with value %q", entapi.ErrValidation, key, values)
			}
		}
	}
	return f, request, nil
}

var ledgerSortOptions = map[string]func(...sql.OrderTermOption) ledger.OrderOption{
	"id": ledger.ByID,
}

// LedgerSortKeys is the complete sort allow-list. The primary key is
// naturally Sortable; every other key requires api.Sortable().
var LedgerSortKeys = []string{
	"id",
}

// LedgerOrder is the single sort allow-list seam.
func LedgerOrder(r entapi.ListRequest) ([]ledger.OrderOption, error) {
	if len(r.Sort) == 0 {
		return []ledger.OrderOption{ledger.ByID(sql.OrderAsc())}, nil
	}
	orderBy := make([]ledger.OrderOption, 0, len(r.Sort)+1)
	idPresent := false
	lastDir := sql.OrderAsc()
	for _, spec := range r.Sort {
		by, ok := ledgerSortOptions[spec.Key]
		if !ok {
			return nil, fmt.Errorf("%w: cannot sort by %q; legal keys: %s", entapi.ErrValidation, spec.Key, strings.Join(LedgerSortKeys, ", "))
		}
		dir := sql.OrderAsc()
		if spec.Desc {
			dir = sql.OrderDesc()
		}
		orderBy = append(orderBy, by(dir))
		lastDir = dir
		if spec.Key == "id" {
			idPresent = true
		}
	}
	if !idPresent {
		orderBy = append(orderBy, ledger.ByID(lastDir))
	}
	return orderBy, nil
}
