// Code generated by entapi extension from schema "Account". DO NOT EDIT.
// Source template: templates/filter.tmpl
// Regenerate with: make generate

package presenceent

import (
	"encoding"
	"fmt"
	"net/url"
	"sort"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/githonllc/entapi/internal/fixtures/presence/presenceent/account"
	"github.com/githonllc/entapi/internal/fixtures/presence/presenceent/predicate"
	entapi "github.com/githonllc/entapi/runtime"
	"github.com/google/uuid"
)

// AccountFilter is the typed query representation for Account.
// Repeated URL parameters occupy repeated slots and Predicates ANDs them.
type AccountFilter struct {
	// id: uuid.UUID
	ID      []uuid.UUID   `json:"id,omitempty"`
	IDNEQ   []uuid.UUID   `json:"id_neq,omitempty"`
	IDIn    [][]uuid.UUID `json:"id_in,omitempty"`
	IDNotIn [][]uuid.UUID `json:"id_not_in,omitempty"`
	IDGT    []uuid.UUID   `json:"id_gt,omitempty"`
	IDGTE   []uuid.UUID   `json:"id_gte,omitempty"`
	IDLT    []uuid.UUID   `json:"id_lt,omitempty"`
	IDLTE   []uuid.UUID   `json:"id_lte,omitempty"`
}

// Predicates converts the typed filter into conjunctive ent predicates.
func (f *AccountFilter) Predicates() []predicate.Account {
	if f == nil {
		return nil
	}
	var ps []predicate.Account
	entapi.AppendEach(&ps, f.ID, account.IDEQ)
	entapi.AppendEach(&ps, f.IDNEQ, account.IDNEQ)
	entapi.AppendEachSlice(&ps, f.IDIn, account.IDIn)
	entapi.AppendEachSlice(&ps, f.IDNotIn, account.IDNotIn)
	entapi.AppendEach(&ps, f.IDGT, account.IDGT)
	entapi.AppendEach(&ps, f.IDGTE, account.IDGTE)
	entapi.AppendEach(&ps, f.IDLT, account.IDLT)
	entapi.AppendEach(&ps, f.IDLTE, account.IDLTE)
	return ps
}

func parseAccountIDQueryValue(raw, whole string) (uuid.UUID, error) {
	var parsed uuid.UUID
	if err := encoding.TextUnmarshaler(&parsed).UnmarshalText([]byte(raw)); err != nil {
		return parsed, fmt.Errorf("%w: field %q value %q is invalid: %v", entapi.ErrValidation, "id", whole, err)
	}
	return parsed, nil
}

// ParseAccountQuery parses the complete URL query contract in sorted-key
// order. Runtime code owns lexical grammar; this generated switch owns the
// field-local operator set, conversion and predicate slots.
func ParseAccountQuery(q url.Values) (*AccountFilter, entapi.ListRequest, error) {
	f := &AccountFilter{}
	var request entapi.ListRequest
	keys := make([]string, 0, len(q))
	for key := range q {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		values := q[key]
		reserved, recognized, err := entapi.ReservedQueryValue(key, values)
		if err != nil {
			return nil, entapi.ListRequest{}, err
		}
		if recognized {
			switch key {
			case "_sort":
				request.Sort, err = entapi.ParseSortSpecs(reserved)
			case "_page":
				request.Page, err = entapi.ParsePageParam(key, reserved)
			case "_size":
				request.Size, err = entapi.ParsePageParam(key, reserved)
			case "_q":
				err = fmt.Errorf("%w: _q value %q is invalid because Account has no Searchable fields", entapi.ErrValidation, reserved)
			}
			if err != nil {
				return nil, entapi.ListRequest{}, err
			}
			continue
		}
		if strings.HasPrefix(key, "_") {
			return nil, entapi.ListRequest{}, fmt.Errorf("%w: unknown reserved query parameter %q", entapi.ErrValidation, key)
		}
		switch key {
		case "id":
			if err := entapi.ParseFieldValues("id", values, false, "eq, ne, in, not_in, gt, ge, lt, le, from, to, between", parseAccountIDQueryValue, []entapi.QueryOp[uuid.UUID]{
				{Prefix: "eq", Kind: entapi.OpKindValue, One: &f.ID},
				{Prefix: "ne", Kind: entapi.OpKindValue, One: &f.IDNEQ},
				{Prefix: "in", Kind: entapi.OpKindList, Many: &f.IDIn},
				{Prefix: "not_in", Kind: entapi.OpKindList, Many: &f.IDNotIn},
				{Prefix: "gt", Kind: entapi.OpKindValue, One: &f.IDGT},
				{Prefix: "ge", Kind: entapi.OpKindValue, One: &f.IDGTE},
				{Prefix: "lt", Kind: entapi.OpKindValue, One: &f.IDLT},
				{Prefix: "le", Kind: entapi.OpKindValue, One: &f.IDLTE},
				{Prefix: "from", Kind: entapi.OpKindValue, One: &f.IDGTE},
				{Prefix: "to", Kind: entapi.OpKindValue, One: &f.IDLTE},
				{Prefix: "between", Kind: entapi.OpKindRange, One: &f.IDGTE, Second: &f.IDLTE},
			}); err != nil {
				return nil, entapi.ListRequest{}, err
			}
		default:
			switch key {
			case "email":
				return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q with value %q is not Filterable", entapi.ErrValidation, key, values)
			case "seats":
				return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q with value %q is not Filterable", entapi.ErrValidation, key, values)
			case "accepted_terms":
				return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q with value %q is not Filterable", entapi.ErrValidation, key, values)
			case "plan":
				return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q with value %q is not Filterable", entapi.ErrValidation, key, values)
			case "nickname":
				return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q with value %q is not Filterable", entapi.ErrValidation, key, values)
			case "quota":
				return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q with value %q is not Filterable", entapi.ErrValidation, key, values)
			case "origin":
				return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q with value %q is not Filterable", entapi.ErrValidation, key, values)
			default:
				return nil, entapi.ListRequest{}, fmt.Errorf("%w: unknown query field %q with value %q", entapi.ErrValidation, key, values)
			}
		}
	}
	return f, request, nil
}

var accountSortOptions = map[string]func(...sql.OrderTermOption) account.OrderOption{
	"id": account.ByID,
}

// AccountSortKeys is the complete sort allow-list. The primary key is
// naturally Sortable; every other key requires api.Sortable().
var AccountSortKeys = []string{
	"id",
}

// AccountOrder is the single sort allow-list seam.
func AccountOrder(r entapi.ListRequest) ([]account.OrderOption, error) {
	if len(r.Sort) == 0 {
		return []account.OrderOption{account.ByID(sql.OrderAsc())}, nil
	}
	orderBy := make([]account.OrderOption, 0, len(r.Sort)+1)
	idPresent := false
	lastDir := sql.OrderAsc()
	for _, spec := range r.Sort {
		by, ok := accountSortOptions[spec.Key]
		if !ok {
			return nil, fmt.Errorf("%w: cannot sort by %q; legal keys: %s", entapi.ErrValidation, spec.Key, strings.Join(AccountSortKeys, ", "))
		}
		dir := sql.OrderAsc()
		if spec.Desc {
			dir = sql.OrderDesc()
		}
		orderBy = append(orderBy, by(dir))
		lastDir = dir
		if spec.Key == "id" {
			idPresent = true
		}
	}
	if !idPresent {
		orderBy = append(orderBy, account.ByID(lastDir))
	}
	return orderBy, nil
}
