// Code generated by entdomain extension from schema "Doc". DO NOT EDIT.
// Source template: templates/wiring.tmpl
// Regenerate with: make generate

package ent

import (
	"context"

	entdomain "github.com/githonllc/entdomain"
	"github.com/githonllc/entdomain/internal/fixtures/softdelete/ent/doc"
	"github.com/google/uuid"
)

// ============================================================================
// Wiring for Doc — one free function per operation.
//
// Free functions, not methods on a generated struct: there is nothing to embed,
// no self-reference to install and no fixed set of override points. A consumer
// who needs different behaviour writes their own function and stops calling the
// generated one, which is a stronger escape hatch than any hook contract — and
// it is why the hook question becomes moot rather than merely redesigned.
//
// The ratio is the point. A generated thirty-line method body is thirty lines in
// which the generator can have guessed wrong and the caller cannot intervene. A
// single call into a routine written once, in Go, for every entity is not.
//
// The identifier type is uuid.UUID because that is what the schema says.
// Nothing below is written for a particular one.
//
// Error classification is deliberately absent: mapping a driver error to
// not-found or already-exists belongs to the runtime and is issue #13. These
// functions return what ent returned.
// ============================================================================

// docByID fetches one Doc through the eager-load plan.
//
// It goes through Query rather than DocClient.Get, which is the same
// query with no plan applied and therefore cannot serve a response type that
// declares edges.
func docByID(db *Client) func(context.Context, uuid.UUID) (*Doc, error) {
	return func(ctx context.Context, id uuid.UUID) (*Doc, error) {
		return DocQueryWithResponseEdges(db.Doc.Query()).Where(doc.IDEQ(id)).Only(ctx)
	}
}

// docReloaded converts a just-saved Doc by reading it
// back through the eager-load plan.
//
// A mutation builder's Save returns the entity with no edges loaded, and
// DocResponse declares edges, so converting that value directly would
// report them as not loaded. The extra round trip is what makes a mutation
// response the same shape as a read.
func docReloaded(ctx context.Context, db *Client) func(*Doc) (*DocResponse, error) {
	return func(e *Doc) (*DocResponse, error) {
		return GetDoc(ctx, db, e.ID)
	}
}

// GetDoc reads one Doc and converts it to its response.
func GetDoc(ctx context.Context, db *Client, id uuid.UUID) (*DocResponse, error) {
	return entdomain.GetOne(ctx, docByID(db), NewDocResponse, id)
}

// ListDocs runs a filtered, ordered, paginated query.
//
// This is the one operation whose body is not a single call, and the reason is
// worth stating rather than hiding: DocOrder can fail, because a sort
// key outside DocSortKeys has no correct answer and serving a
// differently-ordered page instead is worse than refusing. entdomain.ListPage
// takes resolved order options, not a fallible producer of them, so the check
// happens here.
//
// A nil filter contributes no predicates, so a caller with nothing to filter by
// does not need a branch of its own.
func ListDocs(ctx context.Context, db *Client, f *DocFilter, r entdomain.ListRequest) (*entdomain.Page[DocResponse], error) {
	order, err := DocOrder(r)
	if err != nil {
		return nil, err
	}
	return entdomain.ListPage(ctx, DocQueryWithResponseEdges(db.Doc.Query()), f.Predicates(), order, r, NewDocResponse)
}

// CreateDoc inserts one Doc and returns its response.
//
// It takes the VALIDATED request. Apply is defined on that type and nowhere
// else, so validation is a compile-time requirement here rather than a step
// this function could forget on the caller's behalf.
func CreateDoc(ctx context.Context, db *Client, v *ValidDocCreateRequest) (*DocResponse, error) {
	return entdomain.SaveOne(ctx, v.Apply(db.Doc.Create()), docReloaded(ctx, db))
}

// UpdateDoc applies a validated patch to one Doc.
//
// Fields the patch did not carry are not written at all, so a partial update
// stays partial — that property belongs to Apply, and this function does not
// re-decide it.
func UpdateDoc(ctx context.Context, db *Client, id uuid.UUID, v *ValidDocPatchRequest) (*DocResponse, error) {
	return entdomain.SaveOne(ctx, v.Apply(db.Doc.UpdateOneID(id)), docReloaded(ctx, db))
}

// DeleteDoc removes one Doc.
//
// No runtime routine is involved: ent's own builder is already the single line,
// and there is nothing to convert. What "delete" means for an entity with a
// soft-delete column is decided by an ent interceptor or mixin, not by a
// filename convention read out of the schema.
func DeleteDoc(ctx context.Context, db *Client, id uuid.UUID) error {
	return db.Doc.DeleteOneID(id).Exec(ctx)
}

// DeleteBatchDocs removes several Docs in one statement and
// returns how many rows it deleted.
//
// The count is returned rather than discarded because ent computes it and the
// caller cannot recover it afterwards: a batch delete reports no error for an
// id that matched nothing, so "how many of the ids existed" is answerable here
// and nowhere else.
//
// An empty list deletes nothing. That is ent's own reading of IDIn with no
// arguments, not a guard written here — a guard would be a second place for the
// rule to live, and the failure it protects against is unrecoverable.
func DeleteBatchDocs(ctx context.Context, db *Client, ids []uuid.UUID) (int, error) {
	return db.Doc.Delete().Where(doc.IDIn(ids...)).Exec(ctx)
}
