// Code generated by entdomain extension from the entdomain.SoftDeleteMixin embedded in this schema. DO NOT EDIT.
// Source template: templates/softdelete.tmpl
// Regenerate with: make generate

package ent

import (
	"context"
	"time"

	"github.com/githonllc/entdomain/internal/fixtures/softdelete/ent/doc"
	entdomain "github.com/githonllc/entdomain/runtime"
)

// RegisterSoftDelete installs soft delete on c. It is the one line a consumer
// writes, and it is the whole wiring:
//
//	client := ent.NewClient(ent.Driver(drv))
//	ent.RegisterSoftDelete(client)
//
// Both halves are installed on the client rather than on the schema, so
// adopting soft delete does not change which runtime format ent generates for
// this project and adds no empty import to the consumer's main package.
//
// The cost, stated rather than hidden: a client built WITHOUT this line
// filters nothing, and a delete on it removes the row. Call it wherever the
// client is constructed, including in tests.
func RegisterSoftDelete(c *Client) {
	c.Intercept(softDeleteTraverser())
	c.Use(softDeleteHook())
}

// softDeleteTraverser excludes soft-deleted rows from every query, including
// one built by hand off the client and one built for an eager-loaded edge:
// both reach prepareQuery, which is where interceptors run.
//
// This is the half that cannot live in a generated service. A service can only
// filter the queries it issues itself, and Base<X>Service.DB is an exported
// *Client — so one line of ordinary consumer code, `s.DB.<Entity>.Query()`,
// reaches the database with nothing generated in the call path.
func softDeleteTraverser() Interceptor {
	return TraverseFunc(func(ctx context.Context, q Query) error {
		if entdomain.SoftDeletedIncluded(ctx) {
			return nil
		}
		switch q := q.(type) {
		case *DocQuery:
			q.Where(doc.DeletedAtIsNil())
		}
		return nil
	})
}

// softDeleteHook rewrites a delete into an update that stamps the tombstone.
//
// It re-dispatches through the mutation's own client instead of calling next:
// the next mutator in a delete builder's chain is its sqlExec, which issues a
// DELETE whatever the mutation's Op says. Client().Mutate switches on the Op,
// which is why SetOp comes first. The rewritten update runs the hooks again
// with Op = OpUpdate, so this branch is not re-entered.
//
// The same DeletedAtIsNil predicate the read side uses is attached to the
// update, so deleting an already-deleted row affects no rows and surfaces as a
// not-found rather than as a silent re-stamp.
func softDeleteHook() Hook {
	return func(next Mutator) Mutator {
		return MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			if !m.Op().Is(OpDelete|OpDeleteOne) || entdomain.HardDeleteRequested(ctx) {
				return next.Mutate(ctx, m)
			}
			switch m := m.(type) {
			case *DocMutation:
				m.WhereP(doc.DeletedAtIsNil())
				m.SetOp(OpUpdate)
				m.SetDeletedAt(time.Now())
				return m.Client().Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}
