// Code generated by entapi extension from schema "Category". DO NOT EDIT.
// Source template: templates/filter.tmpl
// Regenerate with: make generate

package petstoreent

import (
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/githonllc/entapi/examples/petstore/petstoreent/category"
	"github.com/githonllc/entapi/examples/petstore/petstoreent/predicate"
	entapi "github.com/githonllc/entapi/runtime"
)

// CategoryFilter is the typed query representation for Category.
// Repeated URL parameters occupy repeated slots and Predicates ANDs them.
type CategoryFilter struct {
	// id: int
	ID      []int   `json:"id,omitempty"`
	IDNEQ   []int   `json:"id_neq,omitempty"`
	IDIn    [][]int `json:"id_in,omitempty"`
	IDNotIn [][]int `json:"id_not_in,omitempty"`
	IDGT    []int   `json:"id_gt,omitempty"`
	IDGTE   []int   `json:"id_gte,omitempty"`
	IDLT    []int   `json:"id_lt,omitempty"`
	IDLTE   []int   `json:"id_lte,omitempty"`
	// name: string
	Name             []string   `json:"name,omitempty"`
	NameNEQ          []string   `json:"name_neq,omitempty"`
	NameIn           [][]string `json:"name_in,omitempty"`
	NameNotIn        [][]string `json:"name_not_in,omitempty"`
	NameGT           []string   `json:"name_gt,omitempty"`
	NameGTE          []string   `json:"name_gte,omitempty"`
	NameLT           []string   `json:"name_lt,omitempty"`
	NameLTE          []string   `json:"name_lte,omitempty"`
	NameContains     []string   `json:"name_contains,omitempty"`
	NameHasPrefix    []string   `json:"name_prefix,omitempty"`
	NameHasSuffix    []string   `json:"name_suffix,omitempty"`
	NameContainsFold []string   `json:"name_icontains,omitempty"`
	// Q is the single free-text term matched across Searchable fields.
	Q *string `json:"_q,omitempty"`
}

// Predicates converts the typed filter into conjunctive ent predicates.
func (f *CategoryFilter) Predicates() []predicate.Category {
	if f == nil {
		return nil
	}
	var ps []predicate.Category
	entapi.AppendEach(&ps, f.ID, category.IDEQ)
	entapi.AppendEach(&ps, f.IDNEQ, category.IDNEQ)
	entapi.AppendEachSlice(&ps, f.IDIn, category.IDIn)
	entapi.AppendEachSlice(&ps, f.IDNotIn, category.IDNotIn)
	entapi.AppendEach(&ps, f.IDGT, category.IDGT)
	entapi.AppendEach(&ps, f.IDGTE, category.IDGTE)
	entapi.AppendEach(&ps, f.IDLT, category.IDLT)
	entapi.AppendEach(&ps, f.IDLTE, category.IDLTE)
	entapi.AppendEach(&ps, f.Name, category.NameEQ)
	entapi.AppendEach(&ps, f.NameNEQ, category.NameNEQ)
	entapi.AppendEachSlice(&ps, f.NameIn, category.NameIn)
	entapi.AppendEachSlice(&ps, f.NameNotIn, category.NameNotIn)
	entapi.AppendEach(&ps, f.NameGT, category.NameGT)
	entapi.AppendEach(&ps, f.NameGTE, category.NameGTE)
	entapi.AppendEach(&ps, f.NameLT, category.NameLT)
	entapi.AppendEach(&ps, f.NameLTE, category.NameLTE)
	entapi.AppendEach(&ps, f.NameContains, category.NameContains)
	entapi.AppendEach(&ps, f.NameHasPrefix, category.NameHasPrefix)
	entapi.AppendEach(&ps, f.NameHasSuffix, category.NameHasSuffix)
	entapi.AppendEach(&ps, f.NameContainsFold, category.NameContainsFold)
	if f.Q != nil && *f.Q != "" {
		ps = append(ps, category.Or(
			category.NameContains(*f.Q),
		))
	}
	return ps
}

func parseCategoryIDQueryValue(raw, whole string) (int, error) {
	parsed, err := strconv.ParseInt(raw, 10, 0)
	if err != nil {
		var zero int
		return zero, fmt.Errorf("%w: field %q value %q is not a valid int: %v", entapi.ErrValidation, "id", whole, err)
	}
	return int(parsed), nil
}

func parseCategoryNameQueryValue(raw, whole string) (string, error) {
	return string(raw), nil
}

// ParseCategoryQuery parses the complete URL query contract in sorted-key
// order. Runtime code owns lexical grammar; the generated operator tables own
// the field-local operator set, conversion and predicate slots.
func ParseCategoryQuery(q url.Values) (*CategoryFilter, entapi.ListRequest, error) {
	f := &CategoryFilter{}
	var request entapi.ListRequest
	keys := make([]string, 0, len(q))
	for key := range q {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		values := q[key]
		reserved, recognized, err := entapi.ReservedQueryValue(key, values)
		if err != nil {
			return nil, entapi.ListRequest{}, err
		}
		if recognized {
			switch key {
			case "_sort":
				request.Sort, err = entapi.ParseSortSpecs(reserved)
			case "_page":
				request.Page, err = entapi.ParsePageParam(key, reserved)
			case "_size":
				request.Size, err = entapi.ParsePageParam(key, reserved)
			case "_q":
				term := reserved
				f.Q = &term
			}
			if err != nil {
				return nil, entapi.ListRequest{}, err
			}
			continue
		}
		if strings.HasPrefix(key, "_") {
			return nil, entapi.ListRequest{}, fmt.Errorf("%w: unknown reserved query parameter %q", entapi.ErrValidation, key)
		}
		switch key {
		case "id":
			if err := entapi.ParseFieldValues("id", values, false, "eq, ne, in, not_in, gt, ge, lt, le, from, to, between", parseCategoryIDQueryValue, []entapi.QueryOp[int]{
				{Prefix: "eq", Kind: entapi.OpKindValue, One: &f.ID},
				{Prefix: "ne", Kind: entapi.OpKindValue, One: &f.IDNEQ},
				{Prefix: "in", Kind: entapi.OpKindList, Many: &f.IDIn},
				{Prefix: "not_in", Kind: entapi.OpKindList, Many: &f.IDNotIn},
				{Prefix: "gt", Kind: entapi.OpKindValue, One: &f.IDGT},
				{Prefix: "ge", Kind: entapi.OpKindValue, One: &f.IDGTE},
				{Prefix: "lt", Kind: entapi.OpKindValue, One: &f.IDLT},
				{Prefix: "le", Kind: entapi.OpKindValue, One: &f.IDLTE},
				{Prefix: "from", Kind: entapi.OpKindValue, One: &f.IDGTE},
				{Prefix: "to", Kind: entapi.OpKindValue, One: &f.IDLTE},
				{Prefix: "between", Kind: entapi.OpKindRange, One: &f.IDGTE, Second: &f.IDLTE},
			}); err != nil {
				return nil, entapi.ListRequest{}, err
			}
		case "name":
			if err := entapi.ParseFieldValues("name", values, false, "eq, ne, in, not_in, gt, ge, lt, le, like, prefix, suffix, ilike, from, to, between", parseCategoryNameQueryValue, []entapi.QueryOp[string]{
				{Prefix: "eq", Kind: entapi.OpKindValue, One: &f.Name},
				{Prefix: "ne", Kind: entapi.OpKindValue, One: &f.NameNEQ},
				{Prefix: "in", Kind: entapi.OpKindList, Many: &f.NameIn},
				{Prefix: "not_in", Kind: entapi.OpKindList, Many: &f.NameNotIn},
				{Prefix: "gt", Kind: entapi.OpKindValue, One: &f.NameGT},
				{Prefix: "ge", Kind: entapi.OpKindValue, One: &f.NameGTE},
				{Prefix: "lt", Kind: entapi.OpKindValue, One: &f.NameLT},
				{Prefix: "le", Kind: entapi.OpKindValue, One: &f.NameLTE},
				{Prefix: "like", Kind: entapi.OpKindValue, One: &f.NameContains},
				{Prefix: "prefix", Kind: entapi.OpKindValue, One: &f.NameHasPrefix},
				{Prefix: "suffix", Kind: entapi.OpKindValue, One: &f.NameHasSuffix},
				{Prefix: "ilike", Kind: entapi.OpKindValue, One: &f.NameContainsFold},
				{Prefix: "from", Kind: entapi.OpKindValue, One: &f.NameGTE},
				{Prefix: "to", Kind: entapi.OpKindValue, One: &f.NameLTE},
				{Prefix: "between", Kind: entapi.OpKindRange, One: &f.NameGTE, Second: &f.NameLTE},
			}); err != nil {
				return nil, entapi.ListRequest{}, err
			}
		default:
			return nil, entapi.ListRequest{}, fmt.Errorf("%w: unknown query field %q with value %q", entapi.ErrValidation, key, values)
		}
	}
	return f, request, nil
}

var categorySortOptions = map[string]func(...sql.OrderTermOption) category.OrderOption{
	"id":   category.ByID,
	"name": category.ByName,
}

// CategorySortKeys is the complete sort allow-list. The primary key is
// naturally Sortable; every other key requires api.Sortable().
var CategorySortKeys = []string{
	"id", "name",
}

// CategoryOrder is the single sort allow-list seam.
func CategoryOrder(r entapi.ListRequest) ([]category.OrderOption, error) {
	if len(r.Sort) == 0 {
		return []category.OrderOption{category.ByID(sql.OrderAsc())}, nil
	}
	orderBy := make([]category.OrderOption, 0, len(r.Sort)+1)
	idPresent := false
	lastDir := sql.OrderAsc()
	for _, spec := range r.Sort {
		by, ok := categorySortOptions[spec.Key]
		if !ok {
			return nil, fmt.Errorf("%w: cannot sort by %q; legal keys: %s", entapi.ErrValidation, spec.Key, strings.Join(CategorySortKeys, ", "))
		}
		dir := sql.OrderAsc()
		if spec.Desc {
			dir = sql.OrderDesc()
		}
		orderBy = append(orderBy, by(dir))
		lastDir = dir
		if spec.Key == "id" {
			idPresent = true
		}
	}
	if !idPresent {
		orderBy = append(orderBy, category.ByID(lastDir))
	}
	return orderBy, nil
}
