// Code generated by entapi extension from schema "Pet". DO NOT EDIT.
// Source template: templates/filter.tmpl
// Regenerate with: make generate

package petstoreent

import (
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"entgo.io/ent/dialect/sql"

	"github.com/githonllc/entapi/examples/petstore/petstoreent/pet"
	"github.com/githonllc/entapi/examples/petstore/petstoreent/predicate"
	entapi "github.com/githonllc/entapi/runtime"
)

// PetFilter is the typed query representation for Pet.
// Repeated URL parameters occupy repeated slots and Predicates ANDs them.
type PetFilter struct {
	// id: int
	ID      []int   `json:"id,omitempty"`
	IDNEQ   []int   `json:"id_neq,omitempty"`
	IDIn    [][]int `json:"id_in,omitempty"`
	IDNotIn [][]int `json:"id_not_in,omitempty"`
	IDGT    []int   `json:"id_gt,omitempty"`
	IDGTE   []int   `json:"id_gte,omitempty"`
	IDLT    []int   `json:"id_lt,omitempty"`
	IDLTE   []int   `json:"id_lte,omitempty"`
	// name: string
	Name             []string   `json:"name,omitempty"`
	NameNEQ          []string   `json:"name_neq,omitempty"`
	NameIn           [][]string `json:"name_in,omitempty"`
	NameNotIn        [][]string `json:"name_not_in,omitempty"`
	NameGT           []string   `json:"name_gt,omitempty"`
	NameGTE          []string   `json:"name_gte,omitempty"`
	NameLT           []string   `json:"name_lt,omitempty"`
	NameLTE          []string   `json:"name_lte,omitempty"`
	NameContains     []string   `json:"name_contains,omitempty"`
	NameHasPrefix    []string   `json:"name_prefix,omitempty"`
	NameHasSuffix    []string   `json:"name_suffix,omitempty"`
	NameContainsFold []string   `json:"name_icontains,omitempty"`
	// status: pet.Status
	Status      []pet.Status   `json:"status,omitempty"`
	StatusNEQ   []pet.Status   `json:"status_neq,omitempty"`
	StatusIn    [][]pet.Status `json:"status_in,omitempty"`
	StatusNotIn [][]pet.Status `json:"status_not_in,omitempty"`
	// price: float64, optional
	Price       []float64   `json:"price,omitempty"`
	PriceNEQ    []float64   `json:"price_neq,omitempty"`
	PriceIn     [][]float64 `json:"price_in,omitempty"`
	PriceNotIn  [][]float64 `json:"price_not_in,omitempty"`
	PriceGT     []float64   `json:"price_gt,omitempty"`
	PriceGTE    []float64   `json:"price_gte,omitempty"`
	PriceLT     []float64   `json:"price_lt,omitempty"`
	PriceLTE    []float64   `json:"price_lte,omitempty"`
	PriceIsNull []bool      `json:"price_is_null,omitempty"`
	// Q is the single free-text term matched across Searchable fields.
	Q *string `json:"_q,omitempty"`
}

// Predicates converts the typed filter into conjunctive ent predicates.
func (f *PetFilter) Predicates() []predicate.Pet {
	if f == nil {
		return nil
	}
	var ps []predicate.Pet
	entapi.AppendEach(&ps, f.ID, pet.IDEQ)
	entapi.AppendEach(&ps, f.IDNEQ, pet.IDNEQ)
	entapi.AppendEachSlice(&ps, f.IDIn, pet.IDIn)
	entapi.AppendEachSlice(&ps, f.IDNotIn, pet.IDNotIn)
	entapi.AppendEach(&ps, f.IDGT, pet.IDGT)
	entapi.AppendEach(&ps, f.IDGTE, pet.IDGTE)
	entapi.AppendEach(&ps, f.IDLT, pet.IDLT)
	entapi.AppendEach(&ps, f.IDLTE, pet.IDLTE)
	entapi.AppendEach(&ps, f.Name, pet.NameEQ)
	entapi.AppendEach(&ps, f.NameNEQ, pet.NameNEQ)
	entapi.AppendEachSlice(&ps, f.NameIn, pet.NameIn)
	entapi.AppendEachSlice(&ps, f.NameNotIn, pet.NameNotIn)
	entapi.AppendEach(&ps, f.NameGT, pet.NameGT)
	entapi.AppendEach(&ps, f.NameGTE, pet.NameGTE)
	entapi.AppendEach(&ps, f.NameLT, pet.NameLT)
	entapi.AppendEach(&ps, f.NameLTE, pet.NameLTE)
	entapi.AppendEach(&ps, f.NameContains, pet.NameContains)
	entapi.AppendEach(&ps, f.NameHasPrefix, pet.NameHasPrefix)
	entapi.AppendEach(&ps, f.NameHasSuffix, pet.NameHasSuffix)
	entapi.AppendEach(&ps, f.NameContainsFold, pet.NameContainsFold)
	entapi.AppendEach(&ps, f.Status, pet.StatusEQ)
	entapi.AppendEach(&ps, f.StatusNEQ, pet.StatusNEQ)
	entapi.AppendEachSlice(&ps, f.StatusIn, pet.StatusIn)
	entapi.AppendEachSlice(&ps, f.StatusNotIn, pet.StatusNotIn)
	entapi.AppendEach(&ps, f.Price, pet.PriceEQ)
	entapi.AppendEach(&ps, f.PriceNEQ, pet.PriceNEQ)
	entapi.AppendEachSlice(&ps, f.PriceIn, pet.PriceIn)
	entapi.AppendEachSlice(&ps, f.PriceNotIn, pet.PriceNotIn)
	entapi.AppendEach(&ps, f.PriceGT, pet.PriceGT)
	entapi.AppendEach(&ps, f.PriceGTE, pet.PriceGTE)
	entapi.AppendEach(&ps, f.PriceLT, pet.PriceLT)
	entapi.AppendEach(&ps, f.PriceLTE, pet.PriceLTE)
	for _, isNull := range f.PriceIsNull {
		if isNull {
			ps = append(ps, pet.PriceIsNil())
		} else {
			ps = append(ps, pet.PriceNotNil())
		}
	}
	if f.Q != nil && *f.Q != "" {
		ps = append(ps, pet.Or(
			pet.NameContains(*f.Q),
		))
	}
	return ps
}

func parsePetIDQueryValue(raw, whole string) (int, error) {
	parsed, err := strconv.ParseInt(raw, 10, 0)
	if err != nil {
		var zero int
		return zero, fmt.Errorf("%w: field %q value %q is not a valid int: %v", entapi.ErrValidation, "id", whole, err)
	}
	return int(parsed), nil
}

func parsePetNameQueryValue(raw, whole string) (string, error) {
	return string(raw), nil
}

func parsePetStatusQueryValue(raw, whole string) (pet.Status, error) {
	switch raw {
	case "available", "pending", "sold":
		return pet.Status(raw), nil
	default:
		var zero pet.Status
		return zero, fmt.Errorf("%w: field %q value %q is not an enum member; legal members: %s", entapi.ErrValidation, "status", whole, strings.Join([]string{
			"available",
			"pending",
			"sold",
		}, ", "))
	}
}

func parsePetPriceQueryValue(raw, whole string) (float64, error) {
	parsed, err := strconv.ParseFloat(raw, 64)
	if err != nil {
		var zero float64
		return zero, fmt.Errorf("%w: field %q value %q is not a valid float64: %v", entapi.ErrValidation, "price", whole, err)
	}
	return float64(parsed), nil
}

// ParsePetQuery parses the complete URL query contract in sorted-key
// order. Runtime code owns lexical grammar; the generated operator tables own
// the field-local operator set, conversion and predicate slots.
func ParsePetQuery(q url.Values) (*PetFilter, entapi.ListRequest, error) {
	f := &PetFilter{}
	var request entapi.ListRequest
	keys := make([]string, 0, len(q))
	for key := range q {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		values := q[key]
		reserved, recognized, err := entapi.ReservedQueryValue(key, values)
		if err != nil {
			return nil, entapi.ListRequest{}, err
		}
		if recognized {
			switch key {
			case "_sort":
				request.Sort, err = entapi.ParseSortSpecs(reserved)
			case "_page":
				request.Page, err = entapi.ParsePageParam(key, reserved)
			case "_size":
				request.Size, err = entapi.ParsePageParam(key, reserved)
			case "_q":
				term := reserved
				f.Q = &term
			}
			if err != nil {
				return nil, entapi.ListRequest{}, err
			}
			continue
		}
		if strings.HasPrefix(key, "_") {
			return nil, entapi.ListRequest{}, fmt.Errorf("%w: unknown reserved query parameter %q", entapi.ErrValidation, key)
		}
		switch key {
		case "id":
			if err := entapi.ParseFieldValues("id", values, false, "eq, ne, in, not_in, gt, ge, lt, le, from, to, between", parsePetIDQueryValue, []entapi.QueryOp[int]{
				{Prefix: "eq", Kind: entapi.OpKindValue, One: &f.ID},
				{Prefix: "ne", Kind: entapi.OpKindValue, One: &f.IDNEQ},
				{Prefix: "in", Kind: entapi.OpKindList, Many: &f.IDIn},
				{Prefix: "not_in", Kind: entapi.OpKindList, Many: &f.IDNotIn},
				{Prefix: "gt", Kind: entapi.OpKindValue, One: &f.IDGT},
				{Prefix: "ge", Kind: entapi.OpKindValue, One: &f.IDGTE},
				{Prefix: "lt", Kind: entapi.OpKindValue, One: &f.IDLT},
				{Prefix: "le", Kind: entapi.OpKindValue, One: &f.IDLTE},
				{Prefix: "from", Kind: entapi.OpKindValue, One: &f.IDGTE},
				{Prefix: "to", Kind: entapi.OpKindValue, One: &f.IDLTE},
				{Prefix: "between", Kind: entapi.OpKindRange, One: &f.IDGTE, Second: &f.IDLTE},
			}); err != nil {
				return nil, entapi.ListRequest{}, err
			}
		case "name":
			if err := entapi.ParseFieldValues("name", values, false, "eq, ne, in, not_in, gt, ge, lt, le, like, prefix, suffix, ilike, from, to, between", parsePetNameQueryValue, []entapi.QueryOp[string]{
				{Prefix: "eq", Kind: entapi.OpKindValue, One: &f.Name},
				{Prefix: "ne", Kind: entapi.OpKindValue, One: &f.NameNEQ},
				{Prefix: "in", Kind: entapi.OpKindList, Many: &f.NameIn},
				{Prefix: "not_in", Kind: entapi.OpKindList, Many: &f.NameNotIn},
				{Prefix: "gt", Kind: entapi.OpKindValue, One: &f.NameGT},
				{Prefix: "ge", Kind: entapi.OpKindValue, One: &f.NameGTE},
				{Prefix: "lt", Kind: entapi.OpKindValue, One: &f.NameLT},
				{Prefix: "le", Kind: entapi.OpKindValue, One: &f.NameLTE},
				{Prefix: "like", Kind: entapi.OpKindValue, One: &f.NameContains},
				{Prefix: "prefix", Kind: entapi.OpKindValue, One: &f.NameHasPrefix},
				{Prefix: "suffix", Kind: entapi.OpKindValue, One: &f.NameHasSuffix},
				{Prefix: "ilike", Kind: entapi.OpKindValue, One: &f.NameContainsFold},
				{Prefix: "from", Kind: entapi.OpKindValue, One: &f.NameGTE},
				{Prefix: "to", Kind: entapi.OpKindValue, One: &f.NameLTE},
				{Prefix: "between", Kind: entapi.OpKindRange, One: &f.NameGTE, Second: &f.NameLTE},
			}); err != nil {
				return nil, entapi.ListRequest{}, err
			}
		case "status":
			if err := entapi.ParseFieldValues("status", values, false, "eq, ne, in, not_in", parsePetStatusQueryValue, []entapi.QueryOp[pet.Status]{
				{Prefix: "eq", Kind: entapi.OpKindValue, One: &f.Status},
				{Prefix: "ne", Kind: entapi.OpKindValue, One: &f.StatusNEQ},
				{Prefix: "in", Kind: entapi.OpKindList, Many: &f.StatusIn},
				{Prefix: "not_in", Kind: entapi.OpKindList, Many: &f.StatusNotIn},
			}); err != nil {
				return nil, entapi.ListRequest{}, err
			}
		case "price":
			if err := entapi.ParseFieldValues("price", values, false, "eq, ne, in, not_in, gt, ge, lt, le, is_null, not_null, from, to, between", parsePetPriceQueryValue, []entapi.QueryOp[float64]{
				{Prefix: "eq", Kind: entapi.OpKindValue, One: &f.Price},
				{Prefix: "ne", Kind: entapi.OpKindValue, One: &f.PriceNEQ},
				{Prefix: "in", Kind: entapi.OpKindList, Many: &f.PriceIn},
				{Prefix: "not_in", Kind: entapi.OpKindList, Many: &f.PriceNotIn},
				{Prefix: "gt", Kind: entapi.OpKindValue, One: &f.PriceGT},
				{Prefix: "ge", Kind: entapi.OpKindValue, One: &f.PriceGTE},
				{Prefix: "lt", Kind: entapi.OpKindValue, One: &f.PriceLT},
				{Prefix: "le", Kind: entapi.OpKindValue, One: &f.PriceLTE},
				{Prefix: "is_null", Kind: entapi.OpKindFlag, Null: &f.PriceIsNull, BoolValue: true},
				{Prefix: "not_null", Kind: entapi.OpKindFlag, Null: &f.PriceIsNull, BoolValue: false},
				{Prefix: "from", Kind: entapi.OpKindValue, One: &f.PriceGTE},
				{Prefix: "to", Kind: entapi.OpKindValue, One: &f.PriceLTE},
				{Prefix: "between", Kind: entapi.OpKindRange, One: &f.PriceGTE, Second: &f.PriceLTE},
			}); err != nil {
				return nil, entapi.ListRequest{}, err
			}
		default:
			switch key {
			case "deleted_at":
				return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q with value %q is not Filterable", entapi.ErrValidation, key, values)
			case "photo_urls":
				return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q with value %q is not Filterable", entapi.ErrValidation, key, values)
			case "created_at":
				return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q with value %q is not Filterable", entapi.ErrValidation, key, values)
			case "category_id":
				return nil, entapi.ListRequest{}, fmt.Errorf("%w: field %q with value %q is not Filterable", entapi.ErrValidation, key, values)
			default:
				return nil, entapi.ListRequest{}, fmt.Errorf("%w: unknown query field %q with value %q", entapi.ErrValidation, key, values)
			}
		}
	}
	return f, request, nil
}

var petSortOptions = map[string]func(...sql.OrderTermOption) pet.OrderOption{
	"id":         pet.ByID,
	"name":       pet.ByName,
	"status":     pet.ByStatus,
	"price":      pet.ByPrice,
	"created_at": pet.ByCreatedAt,
}

// PetSortKeys is the complete sort allow-list. The primary key is
// naturally Sortable; every other key requires api.Sortable().
var PetSortKeys = []string{
	"id", "name", "status", "price", "created_at",
}

// PetOrder is the single sort allow-list seam.
func PetOrder(r entapi.ListRequest) ([]pet.OrderOption, error) {
	if len(r.Sort) == 0 {
		return []pet.OrderOption{pet.ByID(sql.OrderAsc())}, nil
	}
	orderBy := make([]pet.OrderOption, 0, len(r.Sort)+1)
	idPresent := false
	lastDir := sql.OrderAsc()
	for _, spec := range r.Sort {
		by, ok := petSortOptions[spec.Key]
		if !ok {
			return nil, fmt.Errorf("%w: cannot sort by %q; legal keys: %s", entapi.ErrValidation, spec.Key, strings.Join(PetSortKeys, ", "))
		}
		dir := sql.OrderAsc()
		if spec.Desc {
			dir = sql.OrderDesc()
		}
		orderBy = append(orderBy, by(dir))
		lastDir = dir
		if spec.Key == "id" {
			idPresent = true
		}
	}
	if !idPresent {
		orderBy = append(orderBy, pet.ByID(lastDir))
	}
	return orderBy, nil
}
