// Code generated by entdomain extension from schema "Widget" (entschema/schema/widget.go). DO NOT EDIT.
// Source template: backend/pkg/entdomain/templates/dto.tmpl
// Regenerate with: make generate

package ent

import (
	"fmt"
	"time"

	entdomain "github.com/githonllc/entdomain"
	"github.com/google/uuid"
)

// ============================================================================================
// Layered Architecture Overview:
//
// 1. CreateRequest/UpdateRequest - HTTP-layer request models, restricted by scope.
//    - Only includes fields for the corresponding scope (ScopeCreate/ScopeUpdate).
//    - Used by the Handler layer to receive HTTP requests.
//    - Certain fields (e.g., ID, audit fields) cannot be set via the HTTP API.
//
// 2. Response - HTTP-layer response model, restricted by scope.
//    - Only includes fields in ScopeResponse.
//    - Includes nested edge entities when FK field has ScopeResponse.
//    - Used by the Handler layer to return HTTP responses.
//
// Key Design Principles:
// - Handler (BaseHandler) → Service (BaseService) → ent.Client
// - HTTP scope only affects struct generation for the Handler layer.
// - The Service layer operates directly on ent entities with full ORM capabilities.
// ============================================================================================

// WidgetCreateRequest represents the create request for Widget
type WidgetCreateRequest struct {
	Name        string  `json:"name" validate:"required"`
	Description *string `json:"description,omitempty"`
}

// Validate validates the create request
func (r *WidgetCreateRequest) Validate() error {
	if r == nil {
		return fmt.Errorf("create request cannot be nil")
	}
	if r.Name == "" {
		return fmt.Errorf("name is required")
	}
	return nil
}

// WidgetUpdateRequest represents the update request for Widget
type WidgetUpdateRequest struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

// Validate validates the update request
func (r *WidgetUpdateRequest) Validate() error {
	if r == nil {
		return fmt.Errorf("update request cannot be nil")
	}
	return nil
}

// WidgetResponse represents the response for Widget
type WidgetResponse struct {
	// ID field is always included in responses
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description,omitempty"`
	CreatedAt   time.Time `json:"created_at"`
}

// WidgetListResponse represents the list response for Widget
type WidgetListResponse struct {
	Data     []*WidgetResponse   `json:"data"`
	Total    int                 `json:"total"`
	Page     int                 `json:"page"`
	Size     int                 `json:"size"`
	PageInfo *entdomain.PageInfo `json:"pageInfo,omitempty"`
}
