// Code generated by ent, DO NOT EDIT.

package staleent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/githonllc/entdomain/internal/fixtures/stale/staleent/sprocket"
	"github.com/google/uuid"
)

// Sprocket is the model entity for the Sprocket schema.
type Sprocket struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name         string `json:"name,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Sprocket) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sprocket.FieldName:
			values[i] = new(sql.NullString)
		case sprocket.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Sprocket fields.
func (s *Sprocket) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sprocket.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				s.ID = *value
			}
		case sprocket.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				s.Name = value.String
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Sprocket.
// This includes values selected through modifiers, order, etc.
func (s *Sprocket) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// Update returns a builder for updating this Sprocket.
// Note that you need to call Sprocket.Unwrap() before calling this method if this Sprocket
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Sprocket) Update() *SprocketUpdateOne {
	return NewSprocketClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Sprocket entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Sprocket) Unwrap() *Sprocket {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("staleent: Sprocket is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Sprocket) String() string {
	var builder strings.Builder
	builder.WriteString("Sprocket(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("name=")
	builder.WriteString(s.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Sprockets is a parsable slice of Sprocket.
type Sprockets []*Sprocket
